// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

package nn

import (
	"github.com/ajroetker/go-highway/hwy"
)

func BaseRoPE_fallback_Float16(data []hwy.Float16, cos []hwy.Float16, sin []hwy.Float16, seqLen int, headDim int) {
	if seqLen == 0 || headDim == 0 {
		return
	}
	halfDim := headDim / 2
	lanes := hwy.MaxLanes[hwy.Float16]()
	for pos := range seqLen {
		dataOff := pos * headDim
		csOff := pos * halfDim
		first := data[dataOff : dataOff+halfDim]
		second := data[dataOff+halfDim : dataOff+headDim]
		c := cos[csOff : csOff+halfDim]
		s := sin[csOff : csOff+halfDim]
		ii := 0
		for ; ii+lanes <= halfDim; ii += lanes {
			f := hwy.Load(first[ii:])
			se := hwy.Load(second[ii:])
			cv := hwy.Load(c[ii:])
			sv := hwy.Load(s[ii:])
			newFirst := hwy.Sub(hwy.Mul(f, cv), hwy.Mul(se, sv))
			newSecond := hwy.MulAdd(f, sv, hwy.Mul(se, cv))
			hwy.Store(newFirst, first[ii:])
			hwy.Store(newSecond, second[ii:])
		}
		for d := ii; d < halfDim; d++ {
			f := first[d]
			se := second[d]
			first[d] = hwy.Float32ToFloat16(f.Float32()*c[d].Float32() - se.Float32()*s[d].Float32())
			second[d] = hwy.Float32ToFloat16(f.Float32()*s[d].Float32() + se.Float32()*c[d].Float32())
		}
	}
}

func BaseRoPE_fallback_BFloat16(data []hwy.BFloat16, cos []hwy.BFloat16, sin []hwy.BFloat16, seqLen int, headDim int) {
	if seqLen == 0 || headDim == 0 {
		return
	}
	halfDim := headDim / 2
	lanes := hwy.MaxLanes[hwy.BFloat16]()
	for pos := range seqLen {
		dataOff := pos * headDim
		csOff := pos * halfDim
		first := data[dataOff : dataOff+halfDim]
		second := data[dataOff+halfDim : dataOff+headDim]
		c := cos[csOff : csOff+halfDim]
		s := sin[csOff : csOff+halfDim]
		ii := 0
		for ; ii+lanes <= halfDim; ii += lanes {
			f := hwy.Load(first[ii:])
			se := hwy.Load(second[ii:])
			cv := hwy.Load(c[ii:])
			sv := hwy.Load(s[ii:])
			newFirst := hwy.Sub(hwy.Mul(f, cv), hwy.Mul(se, sv))
			newSecond := hwy.MulAdd(f, sv, hwy.Mul(se, cv))
			hwy.Store(newFirst, first[ii:])
			hwy.Store(newSecond, second[ii:])
		}
		for d := ii; d < halfDim; d++ {
			f := first[d]
			se := second[d]
			first[d] = hwy.Float32ToBFloat16(f.Float32()*c[d].Float32() - se.Float32()*s[d].Float32())
			second[d] = hwy.Float32ToBFloat16(f.Float32()*s[d].Float32() + se.Float32()*c[d].Float32())
		}
	}
}

func BaseRoPE_fallback(data []float32, cos []float32, sin []float32, seqLen int, headDim int) {
	if seqLen == 0 || headDim == 0 {
		return
	}
	halfDim := headDim / 2
	for pos := range seqLen {
		dataOff := pos * headDim
		csOff := pos * halfDim
		first := data[dataOff : dataOff+halfDim]
		second := data[dataOff+halfDim : dataOff+headDim]
		c := cos[csOff : csOff+halfDim]
		s := sin[csOff : csOff+halfDim]
		ii := 0
		for ; ii < halfDim; ii++ {
			f := first[ii]
			se := second[ii]
			cv := c[ii]
			sv := s[ii]
			newFirst := f*cv - se*sv
			newSecond := f*sv + se*cv
			first[ii] = newFirst
			second[ii] = newSecond
		}
		for d := ii; d < halfDim; d++ {
			f := first[d]
			se := second[d]
			first[d] = f*c[d] - se*s[d]
			second[d] = f*s[d] + se*c[d]
		}
	}
}

func BaseRoPE_fallback_Float64(data []float64, cos []float64, sin []float64, seqLen int, headDim int) {
	if seqLen == 0 || headDim == 0 {
		return
	}
	halfDim := headDim / 2
	for pos := range seqLen {
		dataOff := pos * headDim
		csOff := pos * halfDim
		first := data[dataOff : dataOff+halfDim]
		second := data[dataOff+halfDim : dataOff+headDim]
		c := cos[csOff : csOff+halfDim]
		s := sin[csOff : csOff+halfDim]
		ii := 0
		for ; ii < halfDim; ii++ {
			f := first[ii]
			se := second[ii]
			cv := c[ii]
			sv := s[ii]
			newFirst := f*cv - se*sv
			newSecond := f*sv + se*cv
			first[ii] = newFirst
			second[ii] = newSecond
		}
		for d := ii; d < halfDim; d++ {
			f := first[d]
			se := second[d]
			first[d] = f*c[d] - se*s[d]
			second[d] = f*s[d] + se*c[d]
		}
	}
}
