// Copyright 2025 go-highway Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !noasm && arm64

// LayerNorm NEON implementations for ARM64.
// Uses GOAT-transpiled NEON assembly for better performance than hwygen-generated code.
package asm

import "unsafe"

// Generate NEON assembly from C source
//go:generate go tool goat ../c/layernorm_neon_arm64.c -O3 --target arm64

// ============================================================================
// LayerNorm NEON - Float32
// ============================================================================

// LayerNormNEONF32 performs layer normalization with affine transform using NEON.
//
// Parameters:
//   - input: flattened input tensor (size elements)
//   - output: flattened output tensor (size elements)
//   - gamma: scale parameters (normSize elements)
//   - beta: bias parameters (normSize elements)
//   - size: total number of elements
//   - normSize: number of elements per normalization group
//   - epsilon: small constant for numerical stability
func LayerNormNEONF32(input, output, gamma, beta []float32, size, normSize int, epsilon float32) {
	if size == 0 || normSize <= 0 {
		return
	}
	sizeVal := int64(size)
	normSizeVal := int64(normSize)
	layernorm_neon_f32(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&gamma[0]),
		unsafe.Pointer(&beta[0]),
		unsafe.Pointer(&sizeVal),
		unsafe.Pointer(&normSizeVal),
		unsafe.Pointer(&epsilon),
	)
}

// LayerNormNEONF32NoAffine performs layer normalization without affine transform using NEON.
//
// Parameters:
//   - input: flattened input tensor (size elements)
//   - output: flattened output tensor (size elements)
//   - size: total number of elements
//   - normSize: number of elements per normalization group
//   - epsilon: small constant for numerical stability
func LayerNormNEONF32NoAffine(input, output []float32, size, normSize int, epsilon float32) {
	if size == 0 || normSize <= 0 {
		return
	}
	sizeVal := int64(size)
	normSizeVal := int64(normSize)
	layernorm_neon_f32_no_affine(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&sizeVal),
		unsafe.Pointer(&normSizeVal),
		unsafe.Pointer(&epsilon),
	)
}

// ============================================================================
// LayerNorm NEON - Float64
// ============================================================================

// LayerNormNEONF64 performs layer normalization with affine transform using NEON (f64).
func LayerNormNEONF64(input, output, gamma, beta []float64, size, normSize int, epsilon float64) {
	if size == 0 || normSize <= 0 {
		return
	}
	sizeVal := int64(size)
	normSizeVal := int64(normSize)
	layernorm_neon_f64(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&gamma[0]),
		unsafe.Pointer(&beta[0]),
		unsafe.Pointer(&sizeVal),
		unsafe.Pointer(&normSizeVal),
		unsafe.Pointer(&epsilon),
	)
}

// LayerNormNEONF64NoAffine performs layer normalization without affine transform using NEON (f64).
func LayerNormNEONF64NoAffine(input, output []float64, size, normSize int, epsilon float64) {
	if size == 0 || normSize <= 0 {
		return
	}
	sizeVal := int64(size)
	normSizeVal := int64(normSize)
	layernorm_neon_f64_no_affine(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&sizeVal),
		unsafe.Pointer(&normSizeVal),
		unsafe.Pointer(&epsilon),
	)
}

// Assembly function declarations (generated by GoAT from layernorm_neon_arm64.c)
