// Copyright 2025 go-highway Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !noasm && arm64

// Softmax NEON implementations for ARM64.
// Uses GOAT-transpiled NEON assembly for fused subtract-max + exp + normalize.
package asm

import "unsafe"

// Generate NEON assembly from C source
//go:generate go tool goat ../c/softmax_neon_arm64.c -O3 --target arm64

// ============================================================================
// Softmax NEON - Float32
// ============================================================================

// SoftmaxNeonF32 computes softmax using NEON with fused subtract-max + exp.
//
// Three-pass fused algorithm:
//  1. Find max (NEON vmaxq + vmaxvq horizontal reduction)
//  2. Subtract max + exp (fused, avoids separate allocation)
//  3. Normalize by 1/sum
func SoftmaxNeonF32(input, output []float32, size int) {
	if size <= 0 {
		return
	}
	sizeVal := int64(size)
	softmax_neon_f32(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&sizeVal),
	)
}

// ============================================================================
// Softmax NEON - Float64
// ============================================================================

// SoftmaxNeonF64 computes softmax using NEON with fused subtract-max + exp (f64).
func SoftmaxNeonF64(input, output []float64, size int) {
	if size <= 0 {
		return
	}
	sizeVal := int64(size)
	softmax_neon_f64(
		unsafe.Pointer(&input[0]),
		unsafe.Pointer(&output[0]),
		unsafe.Pointer(&sizeVal),
	)
}

// Assembly function declarations (generated by GoAT from softmax_neon_arm64.c)
