// Code generated by hwygen. DO NOT EDIT.
//go:build arm64

package vec

import (
	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
)

func BaseArgmax_neon_Float16(v []hwy.Float16) int {
	if len(v) == 0 {
		panic("vec: Argmax called on empty slice")
	}
	lanes := 8
	if len(v) < lanes {
		return scalarArgmax(v)
	}
	maxVals := hwy.Load(v)
	maxIdxs := hwy.Iota[hwy.Float16]()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := hwy.Load(v[i:])
		curIdxs := hwy.AddF16(hwy.Set(hwy.Float16(i)), hwy.Iota[hwy.Float16]())
		mask := hwy.GreaterThanF16(vals, maxVals)
		maxVals = hwy.IfThenElseF16(mask, vals, maxVals)
		maxIdxs = hwy.IfThenElseF16(mask, curIdxs, maxIdxs)
	}
	valsData := func() []hwy.Float16 {
		var _simd_tmp [8]hwy.Float16
		hwy.Store(maxVals, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []hwy.Float16 {
		var _simd_tmp [8]hwy.Float16
		hwy.Store(maxIdxs, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var maxVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val.Float32() != val.Float32() {
			continue
		}
		idx := int(idxsData[j].Float32())
		if !foundValid || val.Float32() > maxVal || (val.Float32() == maxVal && idx < bestIdx) {
			maxVal = val.Float32()
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i].Float32() != v[i].Float32() {
			continue
		}
		if !foundValid || v[i].Float32() > maxVal || (v[i].Float32() == maxVal && i < bestIdx) {
			maxVal = v[i].Float32()
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmax_neon_BFloat16(v []hwy.BFloat16) int {
	if len(v) == 0 {
		panic("vec: Argmax called on empty slice")
	}
	lanes := 8
	if len(v) < lanes {
		return scalarArgmax(v)
	}
	maxVals := hwy.Load(v)
	maxIdxs := hwy.Iota[hwy.BFloat16]()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := hwy.Load(v[i:])
		curIdxs := hwy.AddBF16(hwy.Set(hwy.BFloat16(i)), hwy.Iota[hwy.BFloat16]())
		mask := hwy.GreaterThanBF16(vals, maxVals)
		maxVals = hwy.IfThenElseBF16(mask, vals, maxVals)
		maxIdxs = hwy.IfThenElseBF16(mask, curIdxs, maxIdxs)
	}
	valsData := func() []hwy.BFloat16 {
		var _simd_tmp [8]hwy.BFloat16
		hwy.Store(maxVals, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []hwy.BFloat16 {
		var _simd_tmp [8]hwy.BFloat16
		hwy.Store(maxIdxs, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var maxVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val.Float32() != val.Float32() {
			continue
		}
		idx := int(idxsData[j].Float32())
		if !foundValid || val.Float32() > maxVal || (val.Float32() == maxVal && idx < bestIdx) {
			maxVal = val.Float32()
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i].Float32() != v[i].Float32() {
			continue
		}
		if !foundValid || v[i].Float32() > maxVal || (v[i].Float32() == maxVal && i < bestIdx) {
			maxVal = v[i].Float32()
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmax_neon(v []float32) int {
	if len(v) == 0 {
		panic("vec: Argmax called on empty slice")
	}
	lanes := 4
	if len(v) < lanes {
		return scalarArgmax(v)
	}
	maxVals := asm.LoadFloat32x4Slice(v)
	maxIdxs := asm.IotaFloat32x4()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := asm.LoadFloat32x4Slice(v[i:])
		curIdxs := asm.BroadcastFloat32x4(float32(i)).Add(asm.IotaFloat32x4())
		mask := vals.GreaterThan(maxVals)
		maxVals = asm.IfThenElse(mask, vals, maxVals)
		maxIdxs = asm.IfThenElse(mask, curIdxs, maxIdxs)
	}
	valsData := func() []float32 {
		var _simd_tmp [4]float32
		maxVals.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []float32 {
		var _simd_tmp [4]float32
		maxIdxs.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var maxVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val != val {
			continue
		}
		idx := int(idxsData[j])
		if !foundValid || val > maxVal || (val == maxVal && idx < bestIdx) {
			maxVal = val
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i] != v[i] {
			continue
		}
		if !foundValid || v[i] > maxVal || (v[i] == maxVal && i < bestIdx) {
			maxVal = v[i]
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmax_neon_Float64(v []float64) int {
	if len(v) == 0 {
		panic("vec: Argmax called on empty slice")
	}
	lanes := 2
	if len(v) < lanes {
		return scalarArgmax(v)
	}
	maxVals := asm.LoadFloat64x2Slice(v)
	maxIdxs := asm.IotaFloat64x2()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := asm.LoadFloat64x2Slice(v[i:])
		curIdxs := asm.BroadcastFloat64x2(float64(i)).Add(asm.IotaFloat64x2())
		mask := vals.GreaterThan(maxVals)
		maxVals = asm.IfThenElseFloat64(mask, vals, maxVals)
		maxIdxs = asm.IfThenElseFloat64(mask, curIdxs, maxIdxs)
	}
	valsData := func() []float64 {
		var _simd_tmp [2]float64
		maxVals.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []float64 {
		var _simd_tmp [2]float64
		maxIdxs.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var maxVal float64
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val != val {
			continue
		}
		idx := int(idxsData[j])
		if !foundValid || val > maxVal || (val == maxVal && idx < bestIdx) {
			maxVal = val
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i] != v[i] {
			continue
		}
		if !foundValid || v[i] > maxVal || (v[i] == maxVal && i < bestIdx) {
			maxVal = v[i]
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmin_neon_Float16(v []hwy.Float16) int {
	if len(v) == 0 {
		panic("vec: Argmin called on empty slice")
	}
	lanes := 8
	if len(v) < lanes {
		return scalarArgmin(v)
	}
	minVals := hwy.Load(v)
	minIdxs := hwy.Iota[hwy.Float16]()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := hwy.Load(v[i:])
		curIdxs := hwy.AddF16(hwy.Set(hwy.Float16(i)), hwy.Iota[hwy.Float16]())
		mask := hwy.LessThanF16(vals, minVals)
		minVals = hwy.IfThenElseF16(mask, vals, minVals)
		minIdxs = hwy.IfThenElseF16(mask, curIdxs, minIdxs)
	}
	valsData := func() []hwy.Float16 {
		var _simd_tmp [8]hwy.Float16
		hwy.Store(minVals, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []hwy.Float16 {
		var _simd_tmp [8]hwy.Float16
		hwy.Store(minIdxs, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var minVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val.Float32() != val.Float32() {
			continue
		}
		idx := int(idxsData[j].Float32())
		if !foundValid || val.Float32() < minVal || (val.Float32() == minVal && idx < bestIdx) {
			minVal = val.Float32()
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i].Float32() != v[i].Float32() {
			continue
		}
		if !foundValid || v[i].Float32() < minVal || (v[i].Float32() == minVal && i < bestIdx) {
			minVal = v[i].Float32()
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmin_neon_BFloat16(v []hwy.BFloat16) int {
	if len(v) == 0 {
		panic("vec: Argmin called on empty slice")
	}
	lanes := 8
	if len(v) < lanes {
		return scalarArgmin(v)
	}
	minVals := hwy.Load(v)
	minIdxs := hwy.Iota[hwy.BFloat16]()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := hwy.Load(v[i:])
		curIdxs := hwy.AddBF16(hwy.Set(hwy.BFloat16(i)), hwy.Iota[hwy.BFloat16]())
		mask := hwy.LessThanBF16(vals, minVals)
		minVals = hwy.IfThenElseBF16(mask, vals, minVals)
		minIdxs = hwy.IfThenElseBF16(mask, curIdxs, minIdxs)
	}
	valsData := func() []hwy.BFloat16 {
		var _simd_tmp [8]hwy.BFloat16
		hwy.Store(minVals, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []hwy.BFloat16 {
		var _simd_tmp [8]hwy.BFloat16
		hwy.Store(minIdxs, _simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var minVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val.Float32() != val.Float32() {
			continue
		}
		idx := int(idxsData[j].Float32())
		if !foundValid || val.Float32() < minVal || (val.Float32() == minVal && idx < bestIdx) {
			minVal = val.Float32()
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i].Float32() != v[i].Float32() {
			continue
		}
		if !foundValid || v[i].Float32() < minVal || (v[i].Float32() == minVal && i < bestIdx) {
			minVal = v[i].Float32()
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmin_neon(v []float32) int {
	if len(v) == 0 {
		panic("vec: Argmin called on empty slice")
	}
	lanes := 4
	if len(v) < lanes {
		return scalarArgmin(v)
	}
	minVals := asm.LoadFloat32x4Slice(v)
	minIdxs := asm.IotaFloat32x4()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := asm.LoadFloat32x4Slice(v[i:])
		curIdxs := asm.BroadcastFloat32x4(float32(i)).Add(asm.IotaFloat32x4())
		mask := vals.LessThan(minVals)
		minVals = asm.IfThenElse(mask, vals, minVals)
		minIdxs = asm.IfThenElse(mask, curIdxs, minIdxs)
	}
	valsData := func() []float32 {
		var _simd_tmp [4]float32
		minVals.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []float32 {
		var _simd_tmp [4]float32
		minIdxs.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var minVal float32
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val != val {
			continue
		}
		idx := int(idxsData[j])
		if !foundValid || val < minVal || (val == minVal && idx < bestIdx) {
			minVal = val
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i] != v[i] {
			continue
		}
		if !foundValid || v[i] < minVal || (v[i] == minVal && i < bestIdx) {
			minVal = v[i]
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}

func BaseArgmin_neon_Float64(v []float64) int {
	if len(v) == 0 {
		panic("vec: Argmin called on empty slice")
	}
	lanes := 2
	if len(v) < lanes {
		return scalarArgmin(v)
	}
	minVals := asm.LoadFloat64x2Slice(v)
	minIdxs := asm.IotaFloat64x2()
	i := lanes
	for ; i+lanes <= len(v); i += lanes {
		vals := asm.LoadFloat64x2Slice(v[i:])
		curIdxs := asm.BroadcastFloat64x2(float64(i)).Add(asm.IotaFloat64x2())
		mask := vals.LessThan(minVals)
		minVals = asm.IfThenElseFloat64(mask, vals, minVals)
		minIdxs = asm.IfThenElseFloat64(mask, curIdxs, minIdxs)
	}
	valsData := func() []float64 {
		var _simd_tmp [2]float64
		minVals.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	idxsData := func() []float64 {
		var _simd_tmp [2]float64
		minIdxs.StoreSlice(_simd_tmp[:])
		return _simd_tmp[:]
	}()
	bestIdx := 0
	var minVal float64
	foundValid := false
	for j := 0; j < lanes; j++ {
		val := valsData[j]
		if val != val {
			continue
		}
		idx := int(idxsData[j])
		if !foundValid || val < minVal || (val == minVal && idx < bestIdx) {
			minVal = val
			bestIdx = idx
			foundValid = true
		}
	}
	for ; i < len(v); i++ {
		if v[i] != v[i] {
			continue
		}
		if !foundValid || v[i] < minVal || (v[i] == minVal && i < bestIdx) {
			minVal = v[i]
			bestIdx = i
			foundValid = true
		}
	}
	return bestIdx
}
