// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package vec

import (
	"simd/archsimd"
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
)

func BaseDot_avx2_Float16(a []hwy.Float16, b []hwy.Float16) hwy.Float16 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum0 := asm.ZeroFloat16x8AVX2()
	sum1 := asm.ZeroFloat16x8AVX2()
	sum2 := asm.ZeroFloat16x8AVX2()
	sum3 := asm.ZeroFloat16x8AVX2()
	lanes := 8
	var i int
	stride := lanes * 4
	for i = 0; i+stride <= n; i += stride {
		va0, va1, va2, va3 := asm.Load4Float16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(a[i:]))), len(a[i:])))
		vb0, vb1, vb2, vb3 := asm.Load4Float16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(b[i:]))), len(b[i:])))
		sum0 = va0.MulAdd(vb0, sum0)
		sum1 = va1.MulAdd(vb1, sum1)
		sum2 = va2.MulAdd(vb2, sum2)
		sum3 = va3.MulAdd(vb3, sum3)
	}
	for i+lanes <= n {
		va := asm.LoadFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(a[i:]))), len(a[i:])))
		vb := asm.LoadFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(b[i:]))), len(b[i:])))
		sum0 = va.MulAdd(vb, sum0)
		i += lanes
	}
	sum0 = sum0.Add(sum1)
	sum2 = sum2.Add(sum3)
	sum0 = sum0.Add(sum2)
	result := sum0.ReduceSum()
	for ; i < n; i++ {
		result += a[i].Float32() * b[i].Float32()
	}
	return hwy.Float32ToFloat16(result)
}

func BaseDot_avx2_BFloat16(a []hwy.BFloat16, b []hwy.BFloat16) hwy.BFloat16 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum0 := asm.ZeroBFloat16x8AVX2()
	sum1 := asm.ZeroBFloat16x8AVX2()
	sum2 := asm.ZeroBFloat16x8AVX2()
	sum3 := asm.ZeroBFloat16x8AVX2()
	lanes := 8
	var i int
	stride := lanes * 4
	for i = 0; i+stride <= n; i += stride {
		va0, va1, va2, va3 := asm.Load4BFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(a[i:]))), len(a[i:])))
		vb0, vb1, vb2, vb3 := asm.Load4BFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(b[i:]))), len(b[i:])))
		sum0 = va0.MulAdd(vb0, sum0)
		sum1 = va1.MulAdd(vb1, sum1)
		sum2 = va2.MulAdd(vb2, sum2)
		sum3 = va3.MulAdd(vb3, sum3)
	}
	for i+lanes <= n {
		va := asm.LoadBFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(a[i:]))), len(a[i:])))
		vb := asm.LoadBFloat16x8AVX2Slice(unsafe.Slice((*uint16)(unsafe.Pointer(unsafe.SliceData(b[i:]))), len(b[i:])))
		sum0 = va.MulAdd(vb, sum0)
		i += lanes
	}
	sum0 = sum0.Add(sum1)
	sum2 = sum2.Add(sum3)
	sum0 = sum0.Add(sum2)
	result := sum0.ReduceSum()
	for ; i < n; i++ {
		result += a[i].Float32() * b[i].Float32()
	}
	return hwy.Float32ToBFloat16(result)
}

func BaseDot_avx2(a []float32, b []float32) float32 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum0 := archsimd.BroadcastFloat32x8(0)
	sum1 := archsimd.BroadcastFloat32x8(0)
	sum2 := archsimd.BroadcastFloat32x8(0)
	sum3 := archsimd.BroadcastFloat32x8(0)
	lanes := 8
	var i int
	stride := lanes * 4
	for i = 0; i+stride <= n; i += stride {
		va0, va1, va2, va3 := hwy.Load4_AVX2_F32x8(a[i:])
		vb0, vb1, vb2, vb3 := hwy.Load4_AVX2_F32x8(b[i:])
		sum0 = va0.MulAdd(vb0, sum0)
		sum1 = va1.MulAdd(vb1, sum1)
		sum2 = va2.MulAdd(vb2, sum2)
		sum3 = va3.MulAdd(vb3, sum3)
	}
	for i+lanes <= n {
		va := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&a[i])))
		vb := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&b[i])))
		sum0 = va.MulAdd(vb, sum0)
		i += lanes
	}
	sum0 = sum0.Add(sum1)
	sum2 = sum2.Add(sum3)
	sum0 = sum0.Add(sum2)
	result := hwy.ReduceSum_AVX2_F32x8(sum0)
	for ; i < n; i++ {
		result += a[i] * b[i]
	}
	return result
}

func BaseDot_avx2_Float64(a []float64, b []float64) float64 {
	if len(a) == 0 || len(b) == 0 {
		return 0
	}
	n := min(len(a), len(b))
	sum0 := archsimd.BroadcastFloat64x4(0)
	sum1 := archsimd.BroadcastFloat64x4(0)
	sum2 := archsimd.BroadcastFloat64x4(0)
	sum3 := archsimd.BroadcastFloat64x4(0)
	lanes := 4
	var i int
	stride := lanes * 4
	for i = 0; i+stride <= n; i += stride {
		va0, va1, va2, va3 := hwy.Load4_AVX2_F64x4(a[i:])
		vb0, vb1, vb2, vb3 := hwy.Load4_AVX2_F64x4(b[i:])
		sum0 = va0.MulAdd(vb0, sum0)
		sum1 = va1.MulAdd(vb1, sum1)
		sum2 = va2.MulAdd(vb2, sum2)
		sum3 = va3.MulAdd(vb3, sum3)
	}
	for i+lanes <= n {
		va := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&a[i])))
		vb := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&b[i])))
		sum0 = va.MulAdd(vb, sum0)
		i += lanes
	}
	sum0 = sum0.Add(sum1)
	sum2 = sum2.Add(sum3)
	sum0 = sum0.Add(sum2)
	result := hwy.ReduceSum_AVX2_F64x4(sum0)
	for ; i < n; i++ {
		result += a[i] * b[i]
	}
	return result
}
