// Code generated by hwygen. DO NOT EDIT.
//go:build arm64

package vec

import (
	"os"

	"github.com/ajroetker/go-highway/hwy"
)

var SquaredNormFloat16 func(v []hwy.Float16) hwy.Float16
var SquaredNormBFloat16 func(v []hwy.BFloat16) hwy.BFloat16
var SquaredNormFloat32 func(v []float32) float32
var SquaredNormFloat64 func(v []float64) float64
var NormFloat16 func(v []hwy.Float16) hwy.Float16
var NormBFloat16 func(v []hwy.BFloat16) hwy.BFloat16
var NormFloat32 func(v []float32) float32
var NormFloat64 func(v []float64) float64

// SquaredNorm is the generic API that dispatches to the appropriate SIMD implementation.
func SquaredNorm[T hwy.Floats](v []T) T {
	switch any(v).(type) {
	case []hwy.Float16:
		return any(SquaredNormFloat16(any(v).([]hwy.Float16))).(T)
	case []hwy.BFloat16:
		return any(SquaredNormBFloat16(any(v).([]hwy.BFloat16))).(T)
	case []float32:
		return any(SquaredNormFloat32(any(v).([]float32))).(T)
	case []float64:
		return any(SquaredNormFloat64(any(v).([]float64))).(T)
	}
	panic("unreachable")
}

// Norm is the generic API that dispatches to the appropriate SIMD implementation.
func Norm[T hwy.Floats](v []T) T {
	switch any(v).(type) {
	case []hwy.Float16:
		return any(NormFloat16(any(v).([]hwy.Float16))).(T)
	case []hwy.BFloat16:
		return any(NormBFloat16(any(v).([]hwy.BFloat16))).(T)
	case []float32:
		return any(NormFloat32(any(v).([]float32))).(T)
	case []float64:
		return any(NormFloat64(any(v).([]float64))).(T)
	}
	panic("unreachable")
}

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initNormFallback()
		return
	}
	initNormNEON()
	return
}

func initNormNEON() {
	SquaredNormFloat16 = BaseSquaredNorm_neon_Float16
	SquaredNormBFloat16 = BaseSquaredNorm_neon_BFloat16
	SquaredNormFloat32 = BaseSquaredNorm_neon
	SquaredNormFloat64 = BaseSquaredNorm_neon_Float64
	NormFloat16 = BaseNorm_neon_Float16
	NormBFloat16 = BaseNorm_neon_BFloat16
	NormFloat32 = BaseNorm_neon
	NormFloat64 = BaseNorm_neon_Float64
}

func initNormFallback() {
	SquaredNormFloat16 = BaseSquaredNorm_fallback_Float16
	SquaredNormBFloat16 = BaseSquaredNorm_fallback_BFloat16
	SquaredNormFloat32 = BaseSquaredNorm_fallback
	SquaredNormFloat64 = BaseSquaredNorm_fallback_Float64
	NormFloat16 = BaseNorm_fallback_Float16
	NormBFloat16 = BaseNorm_fallback_BFloat16
	NormFloat32 = BaseNorm_fallback
	NormFloat64 = BaseNorm_fallback_Float64
}
