// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package vec

import (
	stdmath "math"

	"github.com/ajroetker/go-highway/hwy"
)

func BaseSquaredNorm_avx2_Float16(v []hwy.Float16) hwy.Float16 {
	return BaseDot_avx2_Float16(v, v)
}

func BaseSquaredNorm_avx2_BFloat16(v []hwy.BFloat16) hwy.BFloat16 {
	return BaseDot_avx2_BFloat16(v, v)
}

func BaseSquaredNorm_avx2(v []float32) float32 {
	return BaseDot_avx2(v, v)
}

func BaseSquaredNorm_avx2_Float64(v []float64) float64 {
	return BaseDot_avx2_Float64(v, v)
}

func BaseNorm_avx2_Float16(v []hwy.Float16) hwy.Float16 {
	squaredNorm := BaseSquaredNorm_avx2_Float16(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.Float16)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(hwy.Float16)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.Float16)
	}
}

func BaseNorm_avx2_BFloat16(v []hwy.BFloat16) hwy.BFloat16 {
	squaredNorm := BaseSquaredNorm_avx2_BFloat16(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.BFloat16)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(hwy.BFloat16)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(hwy.BFloat16)
	}
}

func BaseNorm_avx2(v []float32) float32 {
	squaredNorm := BaseSquaredNorm_avx2(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float32)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(float32)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float32)
	}
}

func BaseNorm_avx2_Float64(v []float64) float64 {
	squaredNorm := BaseSquaredNorm_avx2_Float64(v)
	if squaredNorm == 0 {
		return 0
	}
	switch any(squaredNorm).(type) {
	case float32:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float64)
	case float64:
		return any(stdmath.Sqrt(any(squaredNorm).(float64))).(float64)
	default:
		return any(float32(stdmath.Sqrt(float64(any(squaredNorm).(float32))))).(float64)
	}
}
