// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package activation

import (
	stdmath "math"
	"simd/archsimd"
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
	"github.com/ajroetker/go-highway/hwy/contrib/math"
)

// Hoisted constants - pre-broadcasted at package init time
var (
	BaseGeGLU_AVX2_vHalf_f32     = archsimd.BroadcastFloat32x8(0.5)
	BaseGeGLU_AVX2_vHalf_f64     = archsimd.BroadcastFloat64x4(0.5)
	BaseGeGLU_AVX2_vInvSqrt2_f32 = archsimd.BroadcastFloat32x8(0.7071067811865476)
	BaseGeGLU_AVX2_vInvSqrt2_f64 = archsimd.BroadcastFloat64x4(0.7071067811865476)
	BaseGeGLU_AVX2_vOne_f32      = archsimd.BroadcastFloat32x8(1.0)
	BaseGeGLU_AVX2_vOne_f64      = archsimd.BroadcastFloat64x4(1.0)
)

func BaseGeGLU_avx2_Float16(gate []hwy.Float16, up []hwy.Float16, output []hwy.Float16) {
	size := min(len(gate), min(len(up), len(output)))
	if size == 0 {
		return
	}
	vHalf := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(float32(0.5))))
	vOne := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(float32(1.0))))
	vInvSqrt2 := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(float32(0.7071067811865476))))
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		g := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii:][0]))
		u := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii:][0]))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_Float16(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.StorePtr(unsafe.Pointer(&output[ii:][0]))
		g1 := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii+8:][0]))
		u1 := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii+8:][0]))
		gScaled1 := g1.Mul(vInvSqrt2)
		erfG1 := math.BaseErfVec_avx2_Float16(gScaled1)
		onePlusErf1 := vOne.Add(erfG1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		geluG1 := g1.Mul(halfOnePlusErf1)
		result1 := geluG1.Mul(u1)
		result1.StorePtr(unsafe.Pointer(&output[ii+8:][0]))
	}
	for ; ii+lanes <= size; ii += lanes {
		g := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii:][0]))
		u := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii:][0]))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_Float16(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.StorePtr(unsafe.Pointer(&output[ii:][0]))
	}
	for i := ii; i < size; i++ {
		g := float64(gate[i].Float32())
		gelu := g * 0.5 * (1.0 + stdmath.Erf(g*0.7071067811865476))
		output[i] = hwy.Float32ToFloat16(float32(gelu * float64(up[i].Float32())))
	}
}

func BaseGeGLU_avx2_BFloat16(gate []hwy.BFloat16, up []hwy.BFloat16, output []hwy.BFloat16) {
	size := min(len(gate), min(len(up), len(output)))
	if size == 0 {
		return
	}
	vHalf := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(float32(0.5))))
	vOne := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(float32(1.0))))
	vInvSqrt2 := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(float32(0.7071067811865476))))
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		g := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii:][0]))
		u := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii:][0]))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_BFloat16(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.StorePtr(unsafe.Pointer(&output[ii:][0]))
		g1 := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii+8:][0]))
		u1 := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii+8:][0]))
		gScaled1 := g1.Mul(vInvSqrt2)
		erfG1 := math.BaseErfVec_avx2_BFloat16(gScaled1)
		onePlusErf1 := vOne.Add(erfG1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		geluG1 := g1.Mul(halfOnePlusErf1)
		result1 := geluG1.Mul(u1)
		result1.StorePtr(unsafe.Pointer(&output[ii+8:][0]))
	}
	for ; ii+lanes <= size; ii += lanes {
		g := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gate[ii:][0]))
		u := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&up[ii:][0]))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_BFloat16(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.StorePtr(unsafe.Pointer(&output[ii:][0]))
	}
	for i := ii; i < size; i++ {
		g := float64(gate[i].Float32())
		gelu := g * 0.5 * (1.0 + stdmath.Erf(g*0.7071067811865476))
		output[i] = hwy.Float32ToBFloat16(float32(gelu * float64(up[i].Float32())))
	}
}

func BaseGeGLU_avx2(gate []float32, up []float32, output []float32) {
	size := min(len(gate), min(len(up), len(output)))
	if size == 0 {
		return
	}
	vHalf := BaseGeGLU_AVX2_vHalf_f32
	vOne := BaseGeGLU_AVX2_vOne_f32
	vInvSqrt2 := BaseGeGLU_AVX2_vInvSqrt2_f32
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		g := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gate[ii])))
		u := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&up[ii])))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.Store((*[8]float32)(unsafe.Pointer(&output[ii])))
		g1 := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gate[ii+8])))
		u1 := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&up[ii+8])))
		gScaled1 := g1.Mul(vInvSqrt2)
		erfG1 := math.BaseErfVec_avx2(gScaled1)
		onePlusErf1 := vOne.Add(erfG1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		geluG1 := g1.Mul(halfOnePlusErf1)
		result1 := geluG1.Mul(u1)
		result1.Store((*[8]float32)(unsafe.Pointer(&output[ii+8])))
	}
	for ; ii+lanes <= size; ii += lanes {
		g := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gate[ii])))
		u := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&up[ii])))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.Store((*[8]float32)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		g := float64(gate[i])
		gelu := g * 0.5 * (1.0 + stdmath.Erf(g*0.7071067811865476))
		output[i] = float32(gelu * float64(up[i]))
	}
}

func BaseGeGLU_avx2_Float64(gate []float64, up []float64, output []float64) {
	size := min(len(gate), min(len(up), len(output)))
	if size == 0 {
		return
	}
	vHalf := BaseGeGLU_AVX2_vHalf_f64
	vOne := BaseGeGLU_AVX2_vOne_f64
	vInvSqrt2 := BaseGeGLU_AVX2_vInvSqrt2_f64
	lanes := 4
	ii := 0
	for ; ii+lanes*2 <= size; ii += lanes * 2 {
		g := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gate[ii])))
		u := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&up[ii])))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_Float64(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.Store((*[4]float64)(unsafe.Pointer(&output[ii])))
		g1 := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gate[ii+4])))
		u1 := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&up[ii+4])))
		gScaled1 := g1.Mul(vInvSqrt2)
		erfG1 := math.BaseErfVec_avx2_Float64(gScaled1)
		onePlusErf1 := vOne.Add(erfG1)
		halfOnePlusErf1 := vHalf.Mul(onePlusErf1)
		geluG1 := g1.Mul(halfOnePlusErf1)
		result1 := geluG1.Mul(u1)
		result1.Store((*[4]float64)(unsafe.Pointer(&output[ii+4])))
	}
	for ; ii+lanes <= size; ii += lanes {
		g := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gate[ii])))
		u := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&up[ii])))
		gScaled := g.Mul(vInvSqrt2)
		erfG := math.BaseErfVec_avx2_Float64(gScaled)
		onePlusErf := vOne.Add(erfG)
		halfOnePlusErf := vHalf.Mul(onePlusErf)
		geluG := g.Mul(halfOnePlusErf)
		result := geluG.Mul(u)
		result.Store((*[4]float64)(unsafe.Pointer(&output[ii])))
	}
	for i := ii; i < size; i++ {
		g := float64(gate[i])
		gelu := g * 0.5 * (1.0 + stdmath.Erf(g*0.7071067811865476))
		output[i] = float64(gelu * float64(up[i]))
	}
}
