// Copyright 2025 go-highway Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !noasm && arm64

// SME FMOPA Block Kernel wrappers for ARM64
// C += A^T * B using SME FMOPA outer product for square blocks.
package asm

import "unsafe"

// Generate assembly from C using goat
// -march=armv9-a+sme+sme-f64f64 enables SME with f32/f64 support
//go:generate go tool goat ../c/block_kernel_fmopa_arm64.c -O3 --target arm64 --target-os darwin -e="-march=armv9-a+sme+sme-f64f64" -e="-fno-unroll-loops"

// BlockMulAddFMOPAF32 computes C += A^T * B for square blocks using SME FMOPA (float32).
// aT must be pre-transposed (rows are original A columns).
// b is normal row-major.
// All matrices are blockDim × blockDim.
// Requires blockDim to be a multiple of 16 (SVL = 512 bits = 16 × float32).
func BlockMulAddFMOPAF32(aT, b, c []float32, blockDim int) {
	if blockDim == 0 {
		return
	}
	n := blockDim * blockDim
	if len(aT) < n {
		panic("BlockMulAddFMOPAF32: aT slice too short")
	}
	if len(b) < n {
		panic("BlockMulAddFMOPAF32: b slice too short")
	}
	if len(c) < n {
		panic("BlockMulAddFMOPAF32: c slice too short")
	}
	block_muladd_fmopa_f32(
		unsafe.Pointer(&aT[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		int64(blockDim),
	)
}

// BlockMulAddFMOPAF64 computes C += A^T * B for square blocks using SME FMOPA (float64).
// aT must be pre-transposed (rows are original A columns).
// b is normal row-major.
// All matrices are blockDim × blockDim.
// Requires blockDim to be a multiple of 8 (SVL = 512 bits = 8 × float64).
func BlockMulAddFMOPAF64(aT, b, c []float64, blockDim int) {
	if blockDim == 0 {
		return
	}
	n := blockDim * blockDim
	if len(aT) < n {
		panic("BlockMulAddFMOPAF64: aT slice too short")
	}
	if len(b) < n {
		panic("BlockMulAddFMOPAF64: b slice too short")
	}
	if len(c) < n {
		panic("BlockMulAddFMOPAF64: c slice too short")
	}
	block_muladd_fmopa_f64(
		unsafe.Pointer(&aT[0]),
		unsafe.Pointer(&b[0]),
		unsafe.Pointer(&c[0]),
		int64(blockDim),
	)
}

// Assembly function declarations are in block_kernel_fmopa_arm64.go (generated by GoAT)
