//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8.2-a+fp16+bf16 -O3
// source: ../c/matmul_klast_neon_arm64.c

TEXT ·matmul_klast_neon_f32(SB), $288-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf9006bf9   // str	x25, [sp, #208]                 ; 8-byte Folded Spill
	WORD $0xa90e5ff8   // stp	x24, x23, [sp, #224]            ; 16-byte Folded Spill
	WORD $0xa90f57f6   // stp	x22, x21, [sp, #240]            ; 16-byte Folded Spill
	WORD $0xa9104ff4   // stp	x20, x19, [sp, #256]            ; 16-byte Folded Spill
	WORD $0xa9117bfd   // stp	x29, x30, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xf9003fe2   // str	x2, [sp, #120]                  ; 8-byte Folded Spill
	WORD $0xf9001be1   // str	x1, [sp, #48]                   ; 8-byte Folded Spill
	WORD $0xf940006e   // ldr	x14, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf10005df   // cmp	x14, #1
	WORD $0xfa41a928   // ccmp	x9, #1, #8, ge
	BGE  BB0_2

BB0_1:
	WORD $0xa9517bfd // ldp	x29, x30, [sp, #272]            ; 16-byte Folded Reload
	WORD $0xa9504ff4 // ldp	x20, x19, [sp, #256]            ; 16-byte Folded Reload
	WORD $0xa94f57f6 // ldp	x22, x21, [sp, #240]            ; 16-byte Folded Reload
	WORD $0xa94e5ff8 // ldp	x24, x23, [sp, #224]            ; 16-byte Folded Reload
	WORD $0xf9406bf9 // ldr	x25, [sp, #208]                 ; 8-byte Folded Reload
	RET

BB0_2:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0xf94000aa // ldr	x10, [x5]
	WORD $0xf9403fe8 // ldr	x8, [sp, #120]                  ; 8-byte Folded Reload
	WORD $0x9100110b // add	x11, x8, #4
	WORD $0xf9002feb // str	x11, [sp, #88]                  ; 8-byte Folded Spill
	WORD $0x9100210b // add	x11, x8, #8
	WORD $0xf90023eb // str	x11, [sp, #64]                  ; 8-byte Folded Spill
	WORD $0x91003108 // add	x8, x8, #12
	WORD $0xa9023be8 // stp	x8, x14, [sp, #32]              ; 16-byte Folded Spill
	WORD $0x927ef548 // and	x8, x10, #0xfffffffffffffffc
	WORD $0xf9006fe8 // str	x8, [sp, #216]                  ; 8-byte Folded Spill
	WORD $0x8b0a0548 // add	x8, x10, x10, lsl #1
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0x8b0801ab // add	x11, x13, x8
	WORD $0xf9000feb // str	x11, [sp, #24]                  ; 8-byte Folded Spill
	WORD $0xd37ced51 // lsl	x17, x10, #4
	WORD $0xd37df14b // lsl	x11, x10, #3
	WORD $0x8b0b01ac // add	x12, x13, x11
	WORD $0xf9000bec // str	x12, [sp, #16]                  ; 8-byte Folded Spill
	WORD $0xd37ef54c // lsl	x12, x10, #2
	WORD $0x8b0c01ad // add	x13, x13, x12
	WORD $0xf90007ed // str	x13, [sp, #8]                   ; 8-byte Folded Spill
	WORD $0x8b080005 // add	x5, x0, x8
	WORD $0x8b0b0006 // add	x6, x0, x11
	WORD $0x8b0c0007 // add	x7, x0, x12
	B    BB0_4

BB0_3:
	WORD $0x8b1100a5 // add	x5, x5, x17
	WORD $0x8b1100c6 // add	x6, x6, x17
	WORD $0x8b1100e7 // add	x7, x7, x17
	WORD $0x8b110000 // add	x0, x0, x17
	WORD $0xf94017ee // ldr	x14, [sp, #40]                  ; 8-byte Folded Reload
	WORD $0xf9403bef // ldr	x15, [sp, #112]                 ; 8-byte Folded Reload
	WORD $0xeb0e01ff // cmp	x15, x14
	BGE  BB0_1

BB0_4:
	WORD $0xd2800015 // mov	x21, #0                         ; =0x0
	WORD $0x910011eb // add	x11, x15, #4
	WORD $0xeb0e017f // cmp	x11, x14
	WORD $0xf9003beb // str	x11, [sp, #112]                 ; 8-byte Folded Spill
	WORD $0x9a8eb16b // csel	x11, x11, x14, lt
	WORD $0xcb0f0173 // sub	x19, x11, x15
	WORD $0xb24001eb // orr	x11, x15, #0x1
	WORD $0xb27f01ec // orr	x12, x15, #0x2
	WORD $0xb24005ed // orr	x13, x15, #0x3
	WORD $0x9b097de8 // mul	x8, x15, x9
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0xf9403fee // ldr	x14, [sp, #120]                 ; 8-byte Folded Reload
	WORD $0x8b0801d4 // add	x20, x14, x8
	WORD $0xf9402fef // ldr	x15, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0x8b0801f0 // add	x16, x15, x8
	WORD $0xf90067f0 // str	x16, [sp, #200]                 ; 8-byte Folded Spill
	WORD $0xf94023f0 // ldr	x16, [sp, #64]                  ; 8-byte Folded Reload
	WORD $0x8b080201 // add	x1, x16, x8
	WORD $0xf9005be1 // str	x1, [sp, #176]                  ; 8-byte Folded Spill
	WORD $0xf94013e1 // ldr	x1, [sp, #32]                   ; 8-byte Folded Reload
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9004fe8 // str	x8, [sp, #152]                  ; 8-byte Folded Spill
	WORD $0x9b097d68 // mul	x8, x11, x9
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90063eb // str	x11, [sp, #192]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf9005feb // str	x11, [sp, #184]                 ; 8-byte Folded Spill
	WORD $0x8b080208 // add	x8, x16, x8
	WORD $0xf90047e8 // str	x8, [sp, #136]                  ; 8-byte Folded Spill
	WORD $0x9b097d88 // mul	x8, x12, x9
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90057eb // str	x11, [sp, #168]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf9004beb // str	x11, [sp, #144]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9002be8 // str	x8, [sp, #80]                   ; 8-byte Folded Spill
	WORD $0x9b097da8 // mul	x8, x13, x9
	WORD $0xa9062fe8 // stp	x8, x11, [sp, #96]              ; 16-byte Folded Spill
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90053eb // str	x11, [sp, #160]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf90043eb // str	x11, [sp, #128]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0xf90027eb // str	x11, [sp, #72]                  ; 8-byte Folded Spill
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9001fe8 // str	x8, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf9401be8 // ldr	x8, [sp, #48]                   ; 8-byte Folded Reload
	WORD $0xa940e3f0 // ldp	x16, x24, [sp, #8]              ; 16-byte Folded Reload
	WORD $0xf9400fe4 // ldr	x4, [sp, #24]                   ; 8-byte Folded Reload
	B    BB0_9

BB0_5:
	WORD $0xbc3579a0 // str	s0, [x13, x21, lsl #2]
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0x1e604041 // fmov	d1, d2

BB0_6:
	WORD $0xf94033ed // ldr	x13, [sp, #96]                  ; 8-byte Folded Reload
	WORD $0x8b0d098c // add	x12, x12, x13, lsl #2
	WORD $0xbc357980 // str	s0, [x12, x21, lsl #2]
	WORD $0x1e604020 // fmov	d0, d1

BB0_7:
	WORD $0xbc357960 // str	s0, [x11, x21, lsl #2]

BB0_8:
	WORD $0x8b110084 // add	x4, x4, x17
	WORD $0x8b110318 // add	x24, x24, x17
	WORD $0x8b110210 // add	x16, x16, x17
	WORD $0x8b110108 // add	x8, x8, x17
	WORD $0xaa0103f5 // mov	x21, x1
	WORD $0xeb09003f // cmp	x1, x9
	BGE  BB0_3

BB0_9:
	WORD $0x910012a1 // add	x1, x21, #4
	WORD $0xeb09003f // cmp	x1, x9
	WORD $0x9a89b02c // csel	x12, x1, x9, lt
	WORD $0xf100115f // cmp	x10, #4
	BGE  BB0_11
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	B    BB0_14

BB0_11:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x5280008d // mov	w13, #4                         ; =0x4
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000

BB0_12:
	WORD $0x3ceb6817 // ldr	q23, [x0, x11]
	WORD $0x3ceb68f9 // ldr	q25, [x7, x11]
	WORD $0x3ceb68da // ldr	q26, [x6, x11]
	WORD $0x3ceb68bb // ldr	q27, [x5, x11]
	WORD $0x3ceb691c // ldr	q28, [x8, x11]
	WORD $0x3ceb6a1d // ldr	q29, [x16, x11]
	WORD $0x3ceb6b1e // ldr	q30, [x24, x11]
	WORD $0x3ceb689f // ldr	q31, [x4, x11]
	WORD $0x4e37cf95 // fmla.4s	v21, v28, v23
	WORD $0x4e37cfb6 // fmla.4s	v22, v29, v23
	WORD $0x4e37cfd8 // fmla.4s	v24, v30, v23
	WORD $0x4e37cff4 // fmla.4s	v20, v31, v23
	WORD $0x4e39cf93 // fmla.4s	v19, v28, v25
	WORD $0x4e39cfb1 // fmla.4s	v17, v29, v25
	WORD $0x4e39cfd0 // fmla.4s	v16, v30, v25
	WORD $0x4e39cff2 // fmla.4s	v18, v31, v25
	WORD $0x4e3acf87 // fmla.4s	v7, v28, v26
	WORD $0x4e3acfa6 // fmla.4s	v6, v29, v26
	WORD $0x4e3acfc5 // fmla.4s	v5, v30, v26
	WORD $0x4e3acfe3 // fmla.4s	v3, v31, v26
	WORD $0x4e3bcf80 // fmla.4s	v0, v28, v27
	WORD $0x4e3bcfa1 // fmla.4s	v1, v29, v27
	WORD $0x4e3bcfc2 // fmla.4s	v2, v30, v27
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0x9100416b // add	x11, x11, #16
	WORD $0x4e3bcfe4 // fmla.4s	v4, v31, v27
	WORD $0xeb0a01bf // cmp	x13, x10
	BLE  BB0_12
	WORD $0xf9406fed // ldr	x13, [sp, #216]                 ; 8-byte Folded Reload

BB0_14:
	WORD $0x6e35d6b5 // faddp.4s	v21, v21, v21
	WORD $0x7e30dab7 // faddp.2s	s23, v21
	WORD $0x6e36d6d5 // faddp.4s	v21, v22, v22
	WORD $0x7e30dab6 // faddp.2s	s22, v21
	WORD $0x6e38d715 // faddp.4s	v21, v24, v24
	WORD $0x7e30dab5 // faddp.2s	s21, v21
	WORD $0x6e34d694 // faddp.4s	v20, v20, v20
	WORD $0x7e30da94 // faddp.2s	s20, v20
	WORD $0x6e33d673 // faddp.4s	v19, v19, v19
	WORD $0x7e30da73 // faddp.2s	s19, v19
	WORD $0x6e31d631 // faddp.4s	v17, v17, v17
	WORD $0x7e30da31 // faddp.2s	s17, v17
	WORD $0x6e30d610 // faddp.4s	v16, v16, v16
	WORD $0x7e30da10 // faddp.2s	s16, v16
	WORD $0x6e32d652 // faddp.4s	v18, v18, v18
	WORD $0x7e30da52 // faddp.2s	s18, v18
	WORD $0x6e27d4e7 // faddp.4s	v7, v7, v7
	WORD $0x7e30d8e7 // faddp.2s	s7, v7
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0x6e23d463 // faddp.4s	v3, v3, v3
	WORD $0x7e30d863 // faddp.2s	s3, v3
	WORD $0x6e20d400 // faddp.4s	v0, v0, v0
	WORD $0x7e30d800 // faddp.2s	s0, v0
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0x6e22d442 // faddp.4s	v2, v2, v2
	WORD $0x7e30d842 // faddp.2s	s2, v2
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0xeb0d014e // subs	x14, x10, x13
	BLE  BB0_17
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xd37ef5af // lsl	x15, x13, #2
	WORD $0x8b0f008d // add	x13, x4, x15
	WORD $0x8b0f0317 // add	x23, x24, x15
	WORD $0x8b0f0202 // add	x2, x16, x15
	WORD $0x8b0f0103 // add	x3, x8, x15
	WORD $0x8b0f00be // add	x30, x5, x15
	WORD $0x8b0f00d6 // add	x22, x6, x15
	WORD $0x8b0f00f9 // add	x25, x7, x15
	WORD $0x8b0f000f // add	x15, x0, x15

BB0_16:
	WORD $0xbc6b79f8 // ldr	s24, [x15, x11, lsl #2]
	WORD $0xbc6b7b39 // ldr	s25, [x25, x11, lsl #2]
	WORD $0xbc6b7ada // ldr	s26, [x22, x11, lsl #2]
	WORD $0xbc6b7bdb // ldr	s27, [x30, x11, lsl #2]
	WORD $0xbc6b787c // ldr	s28, [x3, x11, lsl #2]
	WORD $0xbc6b785d // ldr	s29, [x2, x11, lsl #2]
	WORD $0xbc6b7afe // ldr	s30, [x23, x11, lsl #2]
	WORD $0xbc6b79bf // ldr	s31, [x13, x11, lsl #2]
	WORD $0x1f1c5f17 // fmadd	s23, s24, s28, s23
	WORD $0x1f1d5b16 // fmadd	s22, s24, s29, s22
	WORD $0x1f1e5715 // fmadd	s21, s24, s30, s21
	WORD $0x1f1f5314 // fmadd	s20, s24, s31, s20
	WORD $0x1f1c4f33 // fmadd	s19, s25, s28, s19
	WORD $0x1f1d4731 // fmadd	s17, s25, s29, s17
	WORD $0x1f1e4330 // fmadd	s16, s25, s30, s16
	WORD $0x1f1f4b32 // fmadd	s18, s25, s31, s18
	WORD $0x1f1c1f47 // fmadd	s7, s26, s28, s7
	WORD $0x1f1d1b46 // fmadd	s6, s26, s29, s6
	WORD $0x1f1e1745 // fmadd	s5, s26, s30, s5
	WORD $0x1f1f0f43 // fmadd	s3, s26, s31, s3
	WORD $0x1f1c0360 // fmadd	s0, s27, s28, s0
	WORD $0x1f1d0761 // fmadd	s1, s27, s29, s1
	WORD $0x1f1e0b62 // fmadd	s2, s27, s30, s2
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x1f1f1364 // fmadd	s4, s27, s31, s4
	WORD $0xeb0b01df // cmp	x14, x11
	BNE  BB0_16

BB0_17:
	WORD $0xf100067f // cmp	x19, #1
	BLT  BB0_8
	WORD $0xcb15018b // sub	x11, x12, x21
	WORD $0xf100057f // cmp	x11, #1
	BLT  BB0_8
	WORD $0xbc357a97 // str	s23, [x20, x21, lsl #2]
	BEQ  BB0_25
	WORD $0xf94067ec // ldr	x12, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0xbc357996 // str	s22, [x12, x21, lsl #2]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB0_25
	WORD $0xf9405bec // ldr	x12, [sp, #176]                 ; 8-byte Folded Reload
	WORD $0xbc357995 // str	s21, [x12, x21, lsl #2]
	BNE  BB0_24
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB0_8
	WORD $0xa94bb7ec // ldp	x12, x13, [sp, #184]            ; 16-byte Folded Reload
	WORD $0xbc3579b3 // str	s19, [x13, x21, lsl #2]
	WORD $0xbc357991 // str	s17, [x12, x21, lsl #2]
	WORD $0x5280010c // mov	w12, #8                         ; =0x8
	B    BB0_30

BB0_24:
	WORD $0xf9404fec // ldr	x12, [sp, #152]                 ; 8-byte Folded Reload
	WORD $0xbc357994 // str	s20, [x12, x21, lsl #2]

BB0_25:
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB0_8
	WORD $0xf94063ed // ldr	x13, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0xbc3579b3 // str	s19, [x13, x21, lsl #2]
	WORD $0xf100057f // cmp	x11, #1
	BEQ  BB0_31
	WORD $0xf9405fec // ldr	x12, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0xbc357991 // str	s17, [x12, x21, lsl #2]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB0_31
	WORD $0xf94047ec // ldr	x12, [sp, #136]                 ; 8-byte Folded Reload
	WORD $0xbc357990 // str	s16, [x12, x21, lsl #2]
	BEQ  BB0_31
	WORD $0x5280018c // mov	w12, #12                        ; =0xc
	WORD $0x1e604250 // fmov	d16, d18

BB0_30:
	WORD $0x8b0c01ac // add	x12, x13, x12
	WORD $0xbc357990 // str	s16, [x12, x21, lsl #2]

BB0_31:
	WORD $0xf1000e7f // cmp	x19, #3
	BLO  BB0_8
	WORD $0xf94057ec // ldr	x12, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0xbc357987 // str	s7, [x12, x21, lsl #2]
	WORD $0xf100057f // cmp	x11, #1
	BNE  BB0_34
	WORD $0xf94053eb // ldr	x11, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB0_7
	B    BB0_8

BB0_34:
	WORD $0xf9404bec // ldr	x12, [sp, #144]                 ; 8-byte Folded Reload
	WORD $0xbc357986 // str	s6, [x12, x21, lsl #2]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB0_37
	WORD $0xf94037eb // ldr	x11, [sp, #104]                 ; 8-byte Folded Reload
	WORD $0xbc357965 // str	s5, [x11, x21, lsl #2]
	BNE  BB0_38
	WORD $0xf94053ed // ldr	x13, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0xf9402fec // ldr	x12, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0xf94027eb // ldr	x11, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB0_5
	B    BB0_8

BB0_37:
	WORD $0xa947afec // ldp	x12, x11, [sp, #120]            ; 16-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB0_6
	B    BB0_8

BB0_38:
	WORD $0xf9402beb // ldr	x11, [sp, #80]                  ; 8-byte Folded Reload
	WORD $0xbc357963 // str	s3, [x11, x21, lsl #2]
	WORD $0xf1000e7f // cmp	x19, #3
	BEQ  BB0_8
	WORD $0xf94053eb // ldr	x11, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0xbc357960 // str	s0, [x11, x21, lsl #2]
	WORD $0xf94043ed // ldr	x13, [sp, #128]                 ; 8-byte Folded Reload
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0xa943b3eb // ldp	x11, x12, [sp, #56]             ; 16-byte Folded Reload
	WORD $0x1e604041 // fmov	d1, d2
	WORD $0x1e604082 // fmov	d2, d4
	B    BB0_5

TEXT ·matmul_klast_neon_f32_aligned(SB), $160-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf9002bf9   // str	x25, [sp, #80]                  ; 8-byte Folded Spill
	WORD $0xa9065ff8   // stp	x24, x23, [sp, #96]             ; 16-byte Folded Spill
	WORD $0xa90757f6   // stp	x22, x21, [sp, #112]            ; 16-byte Folded Spill
	WORD $0xa9084ff4   // stp	x20, x19, [sp, #128]            ; 16-byte Folded Spill
	WORD $0xa9097bfd   // stp	x29, x30, [sp, #144]            ; 16-byte Folded Spill
	WORD $0xa90207e2   // stp	x2, x1, [sp, #32]               ; 16-byte Folded Spill
	WORD $0xf9400068   // ldr	x8, [x3]
	WORD $0xf940008e   // ldr	x14, [x4]
	WORD $0xf9000fe8   // str	x8, [sp, #24]                   ; 8-byte Folded Spill
	WORD $0xf100051f   // cmp	x8, #1
	WORD $0xfa41a9c8   // ccmp	x14, #1, #8, ge
	BGE  BB1_2

BB1_1:
	WORD $0xa9497bfd // ldp	x29, x30, [sp, #144]            ; 16-byte Folded Reload
	WORD $0xa9484ff4 // ldp	x20, x19, [sp, #128]            ; 16-byte Folded Reload
	WORD $0xa94757f6 // ldp	x22, x21, [sp, #112]            ; 16-byte Folded Reload
	WORD $0xa9465ff8 // ldp	x24, x23, [sp, #96]             ; 16-byte Folded Reload
	WORD $0xf9402bf9 // ldr	x25, [sp, #80]                  ; 8-byte Folded Reload
	RET

BB1_2:
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xf94000ab // ldr	x11, [x5]
	WORD $0x927ef568 // and	x8, x11, #0xfffffffffffffffc
	WORD $0xa9043be8 // stp	x8, x14, [sp, #64]              ; 16-byte Folded Spill
	WORD $0x8b0b0568 // add	x8, x11, x11, lsl #1
	WORD $0xd37ef508 // lsl	x8, x8, #2
	WORD $0xf94017ec // ldr	x12, [sp, #40]                  ; 8-byte Folded Reload
	WORD $0x8b080189 // add	x9, x12, x8
	WORD $0xf9000be9 // str	x9, [sp, #16]                   ; 8-byte Folded Spill
	WORD $0xd37ced6f // lsl	x15, x11, #4
	WORD $0xd37df169 // lsl	x9, x11, #3
	WORD $0x8b09018a // add	x10, x12, x9
	WORD $0xf90007ea // str	x10, [sp, #8]                   ; 8-byte Folded Spill
	WORD $0xd37ef56a // lsl	x10, x11, #2
	WORD $0x8b0a018c // add	x12, x12, x10
	WORD $0xf90003ec // str	x12, [sp]                       ; 8-byte Folded Spill
	WORD $0x8b080011 // add	x17, x0, x8
	WORD $0x8b090003 // add	x3, x0, x9
	WORD $0x8b0a0004 // add	x4, x0, x10
	WORD $0xf9001fef // str	x15, [sp, #56]                  ; 8-byte Folded Spill
	B    BB1_4

BB1_3:
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0x8b0f0231 // add	x17, x17, x15
	WORD $0x8b0f0063 // add	x3, x3, x15
	WORD $0x8b0f0084 // add	x4, x4, x15
	WORD $0x8b0f0000 // add	x0, x0, x15
	WORD $0xf9400fe8 // ldr	x8, [sp, #24]                   ; 8-byte Folded Reload
	WORD $0xeb0801bf // cmp	x13, x8
	BGE  BB1_1

BB1_4:
	WORD $0xd2800005 // mov	x5, #0                          ; =0x0
	WORD $0xb24001a8 // orr	x8, x13, #0x1
	WORD $0xb27f01a9 // orr	x9, x13, #0x2
	WORD $0xb24005aa // orr	x10, x13, #0x3
	WORD $0xf9001bed // str	x13, [sp, #48]                  ; 8-byte Folded Spill
	WORD $0x9b0e7dac // mul	x12, x13, x14
	WORD $0xa94257ed // ldp	x13, x21, [sp, #32]             ; 16-byte Folded Reload
	WORD $0x8b0c09a1 // add	x1, x13, x12, lsl #2
	WORD $0x9b0e7d08 // mul	x8, x8, x14
	WORD $0x8b0809a7 // add	x7, x13, x8, lsl #2
	WORD $0x9b0e7d28 // mul	x8, x9, x14
	WORD $0x8b0809b3 // add	x19, x13, x8, lsl #2
	WORD $0x9b0e7d48 // mul	x8, x10, x14
	WORD $0x8b0809b4 // add	x20, x13, x8, lsl #2
	WORD $0xa9405ff6 // ldp	x22, x23, [sp]                  ; 16-byte Folded Reload
	WORD $0xf9400bf8 // ldr	x24, [sp, #16]                  ; 8-byte Folded Reload
	WORD $0xf9002fe1 // str	x1, [sp, #88]                   ; 8-byte Folded Spill
	B    BB1_7

BB1_5:
	WORD $0xb24000be // orr	x30, x5, #0x1
	WORD $0xb27f00b9 // orr	x25, x5, #0x2
	WORD $0xb24004ad // orr	x13, x5, #0x3

BB1_6:
	WORD $0xbc257820 // str	s0, [x1, x5, lsl #2]
	WORD $0xbc3e7821 // str	s1, [x1, x30, lsl #2]
	WORD $0xbc397822 // str	s2, [x1, x25, lsl #2]
	WORD $0xbc2d7823 // str	s3, [x1, x13, lsl #2]
	WORD $0xbc2578e4 // str	s4, [x7, x5, lsl #2]
	WORD $0xbc3e78e5 // str	s5, [x7, x30, lsl #2]
	WORD $0xbc3978e6 // str	s6, [x7, x25, lsl #2]
	WORD $0xbc2d78e7 // str	s7, [x7, x13, lsl #2]
	WORD $0xbc257a70 // str	s16, [x19, x5, lsl #2]
	WORD $0xbc3e7a72 // str	s18, [x19, x30, lsl #2]
	WORD $0xbc397a75 // str	s21, [x19, x25, lsl #2]
	WORD $0xbc2d7a76 // str	s22, [x19, x13, lsl #2]
	WORD $0xbc257a97 // str	s23, [x20, x5, lsl #2]
	WORD $0x910010a5 // add	x5, x5, #4
	WORD $0x8b0f0318 // add	x24, x24, x15
	WORD $0x8b0f02f7 // add	x23, x23, x15
	WORD $0xbc3e7a93 // str	s19, [x20, x30, lsl #2]
	WORD $0x8b0f02d6 // add	x22, x22, x15
	WORD $0x8b0f02b5 // add	x21, x21, x15
	WORD $0xbc397a91 // str	s17, [x20, x25, lsl #2]
	WORD $0xbc2d7a94 // str	s20, [x20, x13, lsl #2]
	WORD $0xeb0e00bf // cmp	x5, x14
	BGE  BB1_3

BB1_7:
	WORD $0xf100117f // cmp	x11, #4
	BGE  BB1_9
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e417 // movi.2d	v23, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	B    BB1_12

BB1_9:
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x52800088 // mov	w8, #4                          ; =0x4
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x6f00e417 // movi.2d	v23, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000

BB1_10:
	WORD $0x3cec6818 // ldr	q24, [x0, x12]
	WORD $0x3cec6899 // ldr	q25, [x4, x12]
	WORD $0x3cec687a // ldr	q26, [x3, x12]
	WORD $0x3cec6a3b // ldr	q27, [x17, x12]
	WORD $0x3cec6abc // ldr	q28, [x21, x12]
	WORD $0x3cec6add // ldr	q29, [x22, x12]
	WORD $0x3cec6afe // ldr	q30, [x23, x12]
	WORD $0x3cec6b1f // ldr	q31, [x24, x12]
	WORD $0x4e38cf80 // fmla.4s	v0, v28, v24
	WORD $0x4e38cfa1 // fmla.4s	v1, v29, v24
	WORD $0x4e38cfc2 // fmla.4s	v2, v30, v24
	WORD $0x4e38cfe3 // fmla.4s	v3, v31, v24
	WORD $0x4e39cf84 // fmla.4s	v4, v28, v25
	WORD $0x4e39cfa5 // fmla.4s	v5, v29, v25
	WORD $0x4e39cfc6 // fmla.4s	v6, v30, v25
	WORD $0x4e39cfe7 // fmla.4s	v7, v31, v25
	WORD $0x4e3acf90 // fmla.4s	v16, v28, v26
	WORD $0x4e3acfb2 // fmla.4s	v18, v29, v26
	WORD $0x4e3acfd5 // fmla.4s	v21, v30, v26
	WORD $0x4e3acff6 // fmla.4s	v22, v31, v26
	WORD $0x4e3bcf97 // fmla.4s	v23, v28, v27
	WORD $0x4e3bcfb3 // fmla.4s	v19, v29, v27
	WORD $0x4e3bcfd1 // fmla.4s	v17, v30, v27
	WORD $0x91001108 // add	x8, x8, #4
	WORD $0x9100418c // add	x12, x12, #16
	WORD $0x4e3bcff4 // fmla.4s	v20, v31, v27
	WORD $0xeb0b011f // cmp	x8, x11
	BLE  BB1_10
	WORD $0xf94023ec // ldr	x12, [sp, #64]                  ; 8-byte Folded Reload

BB1_12:
	WORD $0x6e20d400 // faddp.4s	v0, v0, v0
	WORD $0x7e30d800 // faddp.2s	s0, v0
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0x6e22d442 // faddp.4s	v2, v2, v2
	WORD $0x7e30d842 // faddp.2s	s2, v2
	WORD $0x6e23d463 // faddp.4s	v3, v3, v3
	WORD $0x7e30d863 // faddp.2s	s3, v3
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0x6e27d4e7 // faddp.4s	v7, v7, v7
	WORD $0x7e30d8e7 // faddp.2s	s7, v7
	WORD $0x6e30d610 // faddp.4s	v16, v16, v16
	WORD $0x7e30da10 // faddp.2s	s16, v16
	WORD $0x6e32d652 // faddp.4s	v18, v18, v18
	WORD $0x7e30da52 // faddp.2s	s18, v18
	WORD $0x6e35d6b5 // faddp.4s	v21, v21, v21
	WORD $0x7e30dab5 // faddp.2s	s21, v21
	WORD $0x6e36d6d6 // faddp.4s	v22, v22, v22
	WORD $0x7e30dad6 // faddp.2s	s22, v22
	WORD $0x6e37d6f7 // faddp.4s	v23, v23, v23
	WORD $0x7e30daf7 // faddp.2s	s23, v23
	WORD $0x6e33d673 // faddp.4s	v19, v19, v19
	WORD $0x7e30da73 // faddp.2s	s19, v19
	WORD $0x6e31d631 // faddp.4s	v17, v17, v17
	WORD $0x7e30da31 // faddp.2s	s17, v17
	WORD $0x6e34d694 // faddp.4s	v20, v20, v20
	WORD $0x7e30da94 // faddp.2s	s20, v20
	WORD $0xeb0c0170 // subs	x16, x11, x12
	BLE  BB1_5
	WORD $0xd2800008 // mov	x8, #0                          ; =0x0
	WORD $0xb24000be // orr	x30, x5, #0x1
	WORD $0xb27f00b9 // orr	x25, x5, #0x2
	WORD $0xb24004ad // orr	x13, x5, #0x3
	WORD $0xd37ef586 // lsl	x6, x12, #2
	WORD $0x8b06030c // add	x12, x24, x6
	WORD $0x8b0602ea // add	x10, x23, x6
	WORD $0x8b0602c1 // add	x1, x22, x6
	WORD $0x8b0602a2 // add	x2, x21, x6
	WORD $0x8b06022f // add	x15, x17, x6
	WORD $0x8b060069 // add	x9, x3, x6
	WORD $0x8b06008e // add	x14, x4, x6
	WORD $0x8b060006 // add	x6, x0, x6

BB1_14:
	WORD $0xbc6878d8 // ldr	s24, [x6, x8, lsl #2]
	WORD $0xbc6879d9 // ldr	s25, [x14, x8, lsl #2]
	WORD $0xbc68793a // ldr	s26, [x9, x8, lsl #2]
	WORD $0xbc6879fb // ldr	s27, [x15, x8, lsl #2]
	WORD $0xbc68785c // ldr	s28, [x2, x8, lsl #2]
	WORD $0xbc68783d // ldr	s29, [x1, x8, lsl #2]
	WORD $0xbc68795e // ldr	s30, [x10, x8, lsl #2]
	WORD $0xbc68799f // ldr	s31, [x12, x8, lsl #2]
	WORD $0x1f1c0300 // fmadd	s0, s24, s28, s0
	WORD $0x1f1d0701 // fmadd	s1, s24, s29, s1
	WORD $0x1f1e0b02 // fmadd	s2, s24, s30, s2
	WORD $0x1f1f0f03 // fmadd	s3, s24, s31, s3
	WORD $0x1f1c1324 // fmadd	s4, s25, s28, s4
	WORD $0x1f1d1725 // fmadd	s5, s25, s29, s5
	WORD $0x1f1e1b26 // fmadd	s6, s25, s30, s6
	WORD $0x1f1f1f27 // fmadd	s7, s25, s31, s7
	WORD $0x1f1c4350 // fmadd	s16, s26, s28, s16
	WORD $0x1f1d4b52 // fmadd	s18, s26, s29, s18
	WORD $0x1f1e5755 // fmadd	s21, s26, s30, s21
	WORD $0x1f1f5b56 // fmadd	s22, s26, s31, s22
	WORD $0x1f1c5f77 // fmadd	s23, s27, s28, s23
	WORD $0x1f1d4f73 // fmadd	s19, s27, s29, s19
	WORD $0x1f1e4771 // fmadd	s17, s27, s30, s17
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0x1f1f5374 // fmadd	s20, s27, s31, s20
	WORD $0xeb08021f // cmp	x16, x8
	BNE  BB1_14
	WORD $0xf94027ee // ldr	x14, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0xf9401fef // ldr	x15, [sp, #56]                  ; 8-byte Folded Reload
	WORD $0xf9402fe1 // ldr	x1, [sp, #88]                   ; 8-byte Folded Reload
	B    BB1_6

TEXT ·matmul_klast_neon_f64(SB), $96-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf9400068   // ldr	x8, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf100051f   // cmp	x8, #1
	WORD $0xfa41a928   // ccmp	x9, #1, #8, ge
	BGE  BB2_2
	RET

BB2_2:
	WORD $0xf9000bf9 // str	x25, [sp, #16]                  ; 8-byte Folded Spill
	WORD $0xa9025ff8 // stp	x24, x23, [sp, #32]             ; 16-byte Folded Spill
	WORD $0xa90357f6 // stp	x22, x21, [sp, #48]             ; 16-byte Folded Spill
	WORD $0xa9044ff4 // stp	x20, x19, [sp, #64]             ; 16-byte Folded Spill
	WORD $0xa9057bfd // stp	x29, x30, [sp, #80]             ; 16-byte Folded Spill
	WORD $0xf94000aa // ldr	x10, [x5]
	WORD $0x9100204b // add	x11, x2, #8
	WORD $0xf100095f // cmp	x10, #2
	BGE  BB2_16
	WORD $0xd2800007 // mov	x7, #0                          ; =0x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xd37df12c // lsl	x12, x9, #3
	WORD $0x7e70d800 // faddp.2d	d0, v0
	WORD $0xd37ced2d // lsl	x13, x9, #4
	WORD $0xd37ced4e // lsl	x14, x10, #4
	WORD $0x8b0c004f // add	x15, x2, x12
	WORD $0xaa0b03f0 // mov	x16, x11
	B    BB2_5

BB2_4:
	WORD $0x8b0d018c // add	x12, x12, x13
	WORD $0x8b0d01ef // add	x15, x15, x13
	WORD $0x8b0d0210 // add	x16, x16, x13
	WORD $0xaa1103e7 // mov	x7, x17
	WORD $0xeb08023f // cmp	x17, x8
	BGE  BB2_32

BB2_5:
	WORD $0x910008f1 // add	x17, x7, #2
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0x9a88b223 // csel	x3, x17, x8, lt
	WORD $0xcb070063 // sub	x3, x3, x7
	WORD $0xf100047f // cmp	x3, #1
	BLT  BB2_4
	WORD $0xd2800004 // mov	x4, #0                          ; =0x0
	WORD $0xd2800005 // mov	x5, #0                          ; =0x0
	WORD $0x9b0a7ce6 // mul	x6, x7, x10
	WORD $0xb24000e7 // orr	x7, x7, #0x1
	WORD $0x9b0a7ce7 // mul	x7, x7, x10
	WORD $0x52800053 // mov	w19, #2                         ; =0x2
	WORD $0xaa1003f4 // mov	x20, x16
	WORD $0xaa0103f5 // mov	x21, x1
	B    BB2_9

BB2_7:
	WORD $0x8b0c02d6 // add	x22, x22, x12
	WORD $0xfc257ac1 // str	d1, [x22, x5, lsl #3]

BB2_8:
	WORD $0x910008a5 // add	x5, x5, #2
	WORD $0x8b0e02b5 // add	x21, x21, x14
	WORD $0x91004294 // add	x20, x20, #16
	WORD $0x91000a73 // add	x19, x19, #2
	WORD $0xd1000884 // sub	x4, x4, #2
	WORD $0xeb0900bf // cmp	x5, x9
	BGE  BB2_4

BB2_9:
	WORD $0xeb13013f // cmp	x9, x19
	WORD $0x9a93b136 // csel	x22, x9, x19, lt
	WORD $0x1e604004 // fmov	d4, d0
	WORD $0x1e604003 // fmov	d3, d0
	WORD $0x1e604001 // fmov	d1, d0
	WORD $0x1e604002 // fmov	d2, d0
	WORD $0xf100015f // cmp	x10, #0
	BLE  BB2_11
	WORD $0xfc677801 // ldr	d1, [x0, x7, lsl #3]
	WORD $0xfc6a7aa3 // ldr	d3, [x21, x10, lsl #3]
	WORD $0x1f430022 // fmadd	d2, d1, d3, d0
	WORD $0xfd4002a4 // ldr	d4, [x21]
	WORD $0x1f440021 // fmadd	d1, d1, d4, d0
	WORD $0xfc667805 // ldr	d5, [x0, x6, lsl #3]
	WORD $0x1f4300a3 // fmadd	d3, d5, d3, d0
	WORD $0x1f4400a4 // fmadd	d4, d5, d4, d0

BB2_11:
	WORD $0x8b0402d7 // add	x23, x22, x4
	WORD $0xf10006ff // cmp	x23, #1
	BLT  BB2_8
	WORD $0xd10006d6 // sub	x22, x22, #1
	WORD $0xfc1f8284 // stur	d4, [x20, #-8]
	WORD $0xeb0502df // cmp	x22, x5
	BNE  BB2_14
	WORD $0xaa0203f6 // mov	x22, x2
	WORD $0xf100047f // cmp	x3, #1
	BNE  BB2_7
	B    BB2_8

BB2_14:
	WORD $0xfd000283 // str	d3, [x20]
	WORD $0xf100047f // cmp	x3, #1
	BEQ  BB2_8
	WORD $0xfc2579e1 // str	d1, [x15, x5, lsl #3]
	WORD $0xaa0b03f6 // mov	x22, x11
	WORD $0x1e604041 // fmov	d1, d2
	B    BB2_7

BB2_16:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0x927ff54c // and	x12, x10, #0x7ffffffffffffffe
	WORD $0xd37df14d // lsl	x13, x10, #3
	WORD $0xd37ced4e // lsl	x14, x10, #4
	WORD $0x92410550 // and	x16, x10, #0x8000000000000001
	WORD $0x927cedb1 // and	x17, x13, #0xfffffffffffffff0
	WORD $0x8b0d0223 // add	x3, x17, x13
	WORD $0x8b030024 // add	x4, x1, x3
	WORD $0xf9000fe4 // str	x4, [sp, #24]                   ; 8-byte Folded Spill
	WORD $0x8b110024 // add	x4, x1, x17
	WORD $0xf90007e4 // str	x4, [sp, #8]                    ; 8-byte Folded Spill
	WORD $0x8b030004 // add	x4, x0, x3
	WORD $0x8b110005 // add	x5, x0, x17
	B    BB2_18

BB2_17:
	WORD $0x8b0e0000 // add	x0, x0, x14
	WORD $0x8b0e0084 // add	x4, x4, x14
	WORD $0x8b0e00a5 // add	x5, x5, x14
	WORD $0xeb0801ff // cmp	x15, x8
	BGE  BB2_32

BB2_18:
	WORD $0xd2800013 // mov	x19, #0                         ; =0x0
	WORD $0xaa0f03f1 // mov	x17, x15
	WORD $0x910009ef // add	x15, x15, #2
	WORD $0xeb0801ff // cmp	x15, x8
	WORD $0x9a88b1e3 // csel	x3, x15, x8, lt
	WORD $0xcb110066 // sub	x6, x3, x17
	WORD $0xb2400223 // orr	x3, x17, #0x1
	WORD $0x9b097e31 // mul	x17, x17, x9
	WORD $0xd37df231 // lsl	x17, x17, #3
	WORD $0x8b110047 // add	x7, x2, x17
	WORD $0x8b110174 // add	x20, x11, x17
	WORD $0x9b097c75 // mul	x21, x3, x9
	WORD $0x8b150c56 // add	x22, x2, x21, lsl #3
	WORD $0xf94007f7 // ldr	x23, [sp, #8]                   ; 8-byte Folded Reload
	WORD $0xf9400ff8 // ldr	x24, [sp, #24]                  ; 8-byte Folded Reload
	WORD $0xaa0103f9 // mov	x25, x1
	B    BB2_21

BB2_19:
	WORD $0x8b150e31 // add	x17, x17, x21, lsl #3
	WORD $0xfc337a20 // str	d0, [x17, x19, lsl #3]

BB2_20:
	WORD $0x8b0e0339 // add	x25, x25, x14
	WORD $0x8b0e0318 // add	x24, x24, x14
	WORD $0x8b0e02f7 // add	x23, x23, x14
	WORD $0xaa1e03f3 // mov	x19, x30
	WORD $0xeb0903df // cmp	x30, x9
	BGE  BB2_17

BB2_21:
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0003f1 // mov	x17, x0
	WORD $0xaa1903fe // mov	x30, x25
	WORD $0x52800043 // mov	w3, #2                          ; =0x2
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000

BB2_22:
	WORD $0x3ced6a22 // ldr	q2, [x17, x13]
	WORD $0x3cc10623 // ldr	q3, [x17], #16
	WORD $0x3dc003c6 // ldr	q6, [x30]
	WORD $0x3ced6bc7 // ldr	q7, [x30, x13]
	WORD $0x4e63ccc0 // fmla.2d	v0, v6, v3
	WORD $0x4e63cce1 // fmla.2d	v1, v7, v3
	WORD $0x4e62ccc4 // fmla.2d	v4, v6, v2
	WORD $0x4e62cce5 // fmla.2d	v5, v7, v2
	WORD $0x91000863 // add	x3, x3, #2
	WORD $0x910043de // add	x30, x30, #16
	WORD $0xeb0a007f // cmp	x3, x10
	BLE  BB2_22
	WORD $0x91000a7e // add	x30, x19, #2
	WORD $0xeb0903df // cmp	x30, x9
	WORD $0x9a89b3d1 // csel	x17, x30, x9, lt
	WORD $0x7e70d803 // faddp.2d	d3, v0
	WORD $0x7e70d822 // faddp.2d	d2, v1
	WORD $0x7e70d880 // faddp.2d	d0, v4
	WORD $0x7e70d8a1 // faddp.2d	d1, v5
	WORD $0xeb0c015f // cmp	x10, x12
	BLE  BB2_26
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0

BB2_25:
	WORD $0xfc6378a4 // ldr	d4, [x5, x3, lsl #3]
	WORD $0xfc637885 // ldr	d5, [x4, x3, lsl #3]
	WORD $0xfc637ae6 // ldr	d6, [x23, x3, lsl #3]
	WORD $0xfc637b07 // ldr	d7, [x24, x3, lsl #3]
	WORD $0x1f460c83 // fmadd	d3, d4, d6, d3
	WORD $0x1f470882 // fmadd	d2, d4, d7, d2
	WORD $0x1f4600a0 // fmadd	d0, d5, d6, d0
	WORD $0x1f4704a1 // fmadd	d1, d5, d7, d1
	WORD $0x91000463 // add	x3, x3, #1
	WORD $0xeb03021f // cmp	x16, x3
	BNE  BB2_25

BB2_26:
	WORD $0xf10004df // cmp	x6, #1
	BLT  BB2_20
	WORD $0xcb130231 // sub	x17, x17, x19
	WORD $0xf100063f // cmp	x17, #1
	BLT  BB2_20
	WORD $0xfc3378e3 // str	d3, [x7, x19, lsl #3]
	BNE  BB2_30
	WORD $0xaa0203f1 // mov	x17, x2
	WORD $0xf10004df // cmp	x6, #1
	BNE  BB2_19
	B    BB2_20

BB2_30:
	WORD $0xfc337a82 // str	d2, [x20, x19, lsl #3]
	WORD $0xf10004df // cmp	x6, #1
	BEQ  BB2_20
	WORD $0xfc337ac0 // str	d0, [x22, x19, lsl #3]
	WORD $0xaa0b03f1 // mov	x17, x11
	WORD $0x1e604020 // fmov	d0, d1
	B    BB2_19

BB2_32:
	WORD $0xa9457bfd // ldp	x29, x30, [sp, #80]             ; 16-byte Folded Reload
	WORD $0xa9444ff4 // ldp	x20, x19, [sp, #64]             ; 16-byte Folded Reload
	WORD $0xa94357f6 // ldp	x22, x21, [sp, #48]             ; 16-byte Folded Reload
	WORD $0xa9425ff8 // ldp	x24, x23, [sp, #32]             ; 16-byte Folded Reload
	WORD $0xf9400bf9 // ldr	x25, [sp, #16]                  ; 8-byte Folded Reload
	RET

TEXT ·matmul_klast_neon_f16(SB), $288-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf9006bf9   // str	x25, [sp, #208]                 ; 8-byte Folded Spill
	WORD $0xa90e5ff8   // stp	x24, x23, [sp, #224]            ; 16-byte Folded Spill
	WORD $0xa90f57f6   // stp	x22, x21, [sp, #240]            ; 16-byte Folded Spill
	WORD $0xa9104ff4   // stp	x20, x19, [sp, #256]            ; 16-byte Folded Spill
	WORD $0xa9117bfd   // stp	x29, x30, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xf9003fe2   // str	x2, [sp, #120]                  ; 8-byte Folded Spill
	WORD $0xf9001be1   // str	x1, [sp, #48]                   ; 8-byte Folded Spill
	WORD $0xf940006e   // ldr	x14, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf10005df   // cmp	x14, #1
	WORD $0xfa41a928   // ccmp	x9, #1, #8, ge
	BGE  BB3_2

BB3_1:
	WORD $0xa9517bfd // ldp	x29, x30, [sp, #272]            ; 16-byte Folded Reload
	WORD $0xa9504ff4 // ldp	x20, x19, [sp, #256]            ; 16-byte Folded Reload
	WORD $0xa94f57f6 // ldp	x22, x21, [sp, #240]            ; 16-byte Folded Reload
	WORD $0xa94e5ff8 // ldp	x24, x23, [sp, #224]            ; 16-byte Folded Reload
	WORD $0xf9406bf9 // ldr	x25, [sp, #208]                 ; 8-byte Folded Reload
	RET

BB3_2:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0xf94000aa // ldr	x10, [x5]
	WORD $0xf9403fe8 // ldr	x8, [sp, #120]                  ; 8-byte Folded Reload
	WORD $0x9100090b // add	x11, x8, #2
	WORD $0xf9002feb // str	x11, [sp, #88]                  ; 8-byte Folded Spill
	WORD $0x9100110b // add	x11, x8, #4
	WORD $0xf90023eb // str	x11, [sp, #64]                  ; 8-byte Folded Spill
	WORD $0x91001908 // add	x8, x8, #6
	WORD $0xa9023be8 // stp	x8, x14, [sp, #32]              ; 16-byte Folded Spill
	WORD $0x927ef548 // and	x8, x10, #0xfffffffffffffffc
	WORD $0xf9006fe8 // str	x8, [sp, #216]                  ; 8-byte Folded Spill
	WORD $0xd37ff948 // lsl	x8, x10, #1
	WORD $0x8b0a010b // add	x11, x8, x10
	WORD $0xd37ff96b // lsl	x11, x11, #1
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0x8b0b01ac // add	x12, x13, x11
	WORD $0xf9000fec // str	x12, [sp, #24]                  ; 8-byte Folded Spill
	WORD $0xd37df151 // lsl	x17, x10, #3
	WORD $0xd37ef54c // lsl	x12, x10, #2
	WORD $0x8b0c01b0 // add	x16, x13, x12
	WORD $0x8b0801ad // add	x13, x13, x8
	WORD $0xa900c3ed // stp	x13, x16, [sp, #8]              ; 16-byte Folded Spill
	WORD $0x8b0b0005 // add	x5, x0, x11
	WORD $0x8b0c0006 // add	x6, x0, x12
	WORD $0x8b080007 // add	x7, x0, x8
	B    BB3_4

BB3_3:
	WORD $0x8b1100a5 // add	x5, x5, x17
	WORD $0x8b1100c6 // add	x6, x6, x17
	WORD $0x8b1100e7 // add	x7, x7, x17
	WORD $0x8b110000 // add	x0, x0, x17
	WORD $0xf94017ee // ldr	x14, [sp, #40]                  ; 8-byte Folded Reload
	WORD $0xf9403bef // ldr	x15, [sp, #112]                 ; 8-byte Folded Reload
	WORD $0xeb0e01ff // cmp	x15, x14
	BGE  BB3_1

BB3_4:
	WORD $0xd2800015 // mov	x21, #0                         ; =0x0
	WORD $0x910011eb // add	x11, x15, #4
	WORD $0xeb0e017f // cmp	x11, x14
	WORD $0xf9003beb // str	x11, [sp, #112]                 ; 8-byte Folded Spill
	WORD $0x9a8eb16b // csel	x11, x11, x14, lt
	WORD $0xcb0f0173 // sub	x19, x11, x15
	WORD $0xb24001eb // orr	x11, x15, #0x1
	WORD $0xb27f01ec // orr	x12, x15, #0x2
	WORD $0xb24005ed // orr	x13, x15, #0x3
	WORD $0x9b097de8 // mul	x8, x15, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0xf9403fee // ldr	x14, [sp, #120]                 ; 8-byte Folded Reload
	WORD $0x8b0801d4 // add	x20, x14, x8
	WORD $0xf9402fef // ldr	x15, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0x8b0801f0 // add	x16, x15, x8
	WORD $0xf90067f0 // str	x16, [sp, #200]                 ; 8-byte Folded Spill
	WORD $0xf94023f0 // ldr	x16, [sp, #64]                  ; 8-byte Folded Reload
	WORD $0x8b080201 // add	x1, x16, x8
	WORD $0xf9005be1 // str	x1, [sp, #176]                  ; 8-byte Folded Spill
	WORD $0xf94013e1 // ldr	x1, [sp, #32]                   ; 8-byte Folded Reload
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9004fe8 // str	x8, [sp, #152]                  ; 8-byte Folded Spill
	WORD $0x9b097d68 // mul	x8, x11, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90063eb // str	x11, [sp, #192]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf9005feb // str	x11, [sp, #184]                 ; 8-byte Folded Spill
	WORD $0x8b080208 // add	x8, x16, x8
	WORD $0xf90047e8 // str	x8, [sp, #136]                  ; 8-byte Folded Spill
	WORD $0x9b097d88 // mul	x8, x12, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90057eb // str	x11, [sp, #168]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf9004beb // str	x11, [sp, #144]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9002be8 // str	x8, [sp, #80]                   ; 8-byte Folded Spill
	WORD $0x9b097da8 // mul	x8, x13, x9
	WORD $0xa9062fe8 // stp	x8, x11, [sp, #96]              ; 16-byte Folded Spill
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90053eb // str	x11, [sp, #160]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf90043eb // str	x11, [sp, #128]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0xf90027eb // str	x11, [sp, #72]                  ; 8-byte Folded Spill
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9001fe8 // str	x8, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf9401bf0 // ldr	x16, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xa940e3e8 // ldp	x8, x24, [sp, #8]               ; 16-byte Folded Reload
	WORD $0xf9400fe4 // ldr	x4, [sp, #24]                   ; 8-byte Folded Reload
	B    BB3_9

BB3_5:
	WORD $0x1e23c000 // fcvt	h0, s0
	WORD $0x7c3579a0 // str	h0, [x13, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0x1e604041 // fmov	d1, d2

BB3_6:
	WORD $0xf94033ed // ldr	x13, [sp, #96]                  ; 8-byte Folded Reload
	WORD $0x8b0d058c // add	x12, x12, x13, lsl #1
	WORD $0x1e23c000 // fcvt	h0, s0
	WORD $0x7c357980 // str	h0, [x12, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1

BB3_7:
	WORD $0x1e23c000 // fcvt	h0, s0
	WORD $0x7c357960 // str	h0, [x11, x21, lsl #1]

BB3_8:
	WORD $0x8b110084 // add	x4, x4, x17
	WORD $0x8b110318 // add	x24, x24, x17
	WORD $0x8b110108 // add	x8, x8, x17
	WORD $0x8b110210 // add	x16, x16, x17
	WORD $0xaa0103f5 // mov	x21, x1
	WORD $0xeb09003f // cmp	x1, x9
	BGE  BB3_3

BB3_9:
	WORD $0x910012a1 // add	x1, x21, #4
	WORD $0xeb09003f // cmp	x1, x9
	WORD $0x9a89b02c // csel	x12, x1, x9, lt
	WORD $0xf100115f // cmp	x10, #4
	BGE  BB3_11
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	B    BB3_14

BB3_11:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x5280008d // mov	w13, #4                         ; =0x4
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000

BB3_12:
	WORD $0xfc6b6817 // ldr	d23, [x0, x11]
	WORD $0xfc6b68f9 // ldr	d25, [x7, x11]
	WORD $0xfc6b68da // ldr	d26, [x6, x11]
	WORD $0xfc6b68bb // ldr	d27, [x5, x11]
	WORD $0x0e217af7 // fcvtl	v23.4s, v23.4h
	WORD $0x0e217b39 // fcvtl	v25.4s, v25.4h
	WORD $0x0e217b5a // fcvtl	v26.4s, v26.4h
	WORD $0xfc6b6a1c // ldr	d28, [x16, x11]
	WORD $0xfc6b691d // ldr	d29, [x8, x11]
	WORD $0xfc6b6b1e // ldr	d30, [x24, x11]
	WORD $0xfc6b689f // ldr	d31, [x4, x11]
	WORD $0x0e217b7b // fcvtl	v27.4s, v27.4h
	WORD $0x0e217b9c // fcvtl	v28.4s, v28.4h
	WORD $0x0e217bbd // fcvtl	v29.4s, v29.4h
	WORD $0x0e217bde // fcvtl	v30.4s, v30.4h
	WORD $0x0e217bff // fcvtl	v31.4s, v31.4h
	WORD $0x4e37cf95 // fmla.4s	v21, v28, v23
	WORD $0x4e37cfb6 // fmla.4s	v22, v29, v23
	WORD $0x4e37cfd8 // fmla.4s	v24, v30, v23
	WORD $0x4e37cff4 // fmla.4s	v20, v31, v23
	WORD $0x4e39cf93 // fmla.4s	v19, v28, v25
	WORD $0x4e39cfb1 // fmla.4s	v17, v29, v25
	WORD $0x4e39cfd0 // fmla.4s	v16, v30, v25
	WORD $0x4e39cff2 // fmla.4s	v18, v31, v25
	WORD $0x4e3acf87 // fmla.4s	v7, v28, v26
	WORD $0x4e3acfa6 // fmla.4s	v6, v29, v26
	WORD $0x4e3acfc5 // fmla.4s	v5, v30, v26
	WORD $0x4e3acfe4 // fmla.4s	v4, v31, v26
	WORD $0x4e3bcf80 // fmla.4s	v0, v28, v27
	WORD $0x4e3bcfa1 // fmla.4s	v1, v29, v27
	WORD $0x4e3bcfc2 // fmla.4s	v2, v30, v27
	WORD $0x4e3bcfe3 // fmla.4s	v3, v31, v27
	WORD $0x910011ad // add	x13, x13, #4
	WORD $0x9100216b // add	x11, x11, #8
	WORD $0xeb0a01bf // cmp	x13, x10
	BLE  BB3_12
	WORD $0xf9406fed // ldr	x13, [sp, #216]                 ; 8-byte Folded Reload

BB3_14:
	WORD $0x6e35d6b5 // faddp.4s	v21, v21, v21
	WORD $0x7e30dab7 // faddp.2s	s23, v21
	WORD $0x6e36d6d5 // faddp.4s	v21, v22, v22
	WORD $0x7e30dab6 // faddp.2s	s22, v21
	WORD $0x6e38d715 // faddp.4s	v21, v24, v24
	WORD $0x7e30dab5 // faddp.2s	s21, v21
	WORD $0x6e34d694 // faddp.4s	v20, v20, v20
	WORD $0x7e30da94 // faddp.2s	s20, v20
	WORD $0x6e33d673 // faddp.4s	v19, v19, v19
	WORD $0x7e30da73 // faddp.2s	s19, v19
	WORD $0x6e31d631 // faddp.4s	v17, v17, v17
	WORD $0x7e30da31 // faddp.2s	s17, v17
	WORD $0x6e30d610 // faddp.4s	v16, v16, v16
	WORD $0x7e30da10 // faddp.2s	s16, v16
	WORD $0x6e32d652 // faddp.4s	v18, v18, v18
	WORD $0x7e30da52 // faddp.2s	s18, v18
	WORD $0x6e27d4e7 // faddp.4s	v7, v7, v7
	WORD $0x7e30d8e7 // faddp.2s	s7, v7
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0x6e20d400 // faddp.4s	v0, v0, v0
	WORD $0x7e30d800 // faddp.2s	s0, v0
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0x6e22d442 // faddp.4s	v2, v2, v2
	WORD $0x7e30d842 // faddp.2s	s2, v2
	WORD $0x6e23d463 // faddp.4s	v3, v3, v3
	WORD $0x7e30d863 // faddp.2s	s3, v3
	WORD $0xeb0d014e // subs	x14, x10, x13
	BLE  BB3_17
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xd37ff9af // lsl	x15, x13, #1
	WORD $0x8b0f008d // add	x13, x4, x15
	WORD $0x8b0f0317 // add	x23, x24, x15
	WORD $0x8b0f0102 // add	x2, x8, x15
	WORD $0x8b0f0203 // add	x3, x16, x15
	WORD $0x8b0f00be // add	x30, x5, x15
	WORD $0x8b0f00d6 // add	x22, x6, x15
	WORD $0x8b0f00f9 // add	x25, x7, x15
	WORD $0x8b0f000f // add	x15, x0, x15

BB3_16:
	WORD $0x7c6b79f8 // ldr	h24, [x15, x11, lsl #1]
	WORD $0x1ee24318 // fcvt	s24, h24
	WORD $0x7c6b7b39 // ldr	h25, [x25, x11, lsl #1]
	WORD $0x1ee24339 // fcvt	s25, h25
	WORD $0x7c6b7ada // ldr	h26, [x22, x11, lsl #1]
	WORD $0x1ee2435a // fcvt	s26, h26
	WORD $0x7c6b7bdb // ldr	h27, [x30, x11, lsl #1]
	WORD $0x1ee2437b // fcvt	s27, h27
	WORD $0x7c6b787c // ldr	h28, [x3, x11, lsl #1]
	WORD $0x1ee2439c // fcvt	s28, h28
	WORD $0x7c6b785d // ldr	h29, [x2, x11, lsl #1]
	WORD $0x1ee243bd // fcvt	s29, h29
	WORD $0x7c6b7afe // ldr	h30, [x23, x11, lsl #1]
	WORD $0x1ee243de // fcvt	s30, h30
	WORD $0x7c6b79bf // ldr	h31, [x13, x11, lsl #1]
	WORD $0x1ee243ff // fcvt	s31, h31
	WORD $0x1f1c5f17 // fmadd	s23, s24, s28, s23
	WORD $0x1f1d5b16 // fmadd	s22, s24, s29, s22
	WORD $0x1f1e5715 // fmadd	s21, s24, s30, s21
	WORD $0x1f1f5314 // fmadd	s20, s24, s31, s20
	WORD $0x1f1c4f33 // fmadd	s19, s25, s28, s19
	WORD $0x1f1d4731 // fmadd	s17, s25, s29, s17
	WORD $0x1f1e4330 // fmadd	s16, s25, s30, s16
	WORD $0x1f1f4b32 // fmadd	s18, s25, s31, s18
	WORD $0x1f1c1f47 // fmadd	s7, s26, s28, s7
	WORD $0x1f1d1b46 // fmadd	s6, s26, s29, s6
	WORD $0x1f1e1745 // fmadd	s5, s26, s30, s5
	WORD $0x1f1f1344 // fmadd	s4, s26, s31, s4
	WORD $0x1f1c0360 // fmadd	s0, s27, s28, s0
	WORD $0x1f1d0761 // fmadd	s1, s27, s29, s1
	WORD $0x1f1e0b62 // fmadd	s2, s27, s30, s2
	WORD $0x1f1f0f63 // fmadd	s3, s27, s31, s3
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xeb0b01df // cmp	x14, x11
	BNE  BB3_16

BB3_17:
	WORD $0xf100067f // cmp	x19, #1
	BLT  BB3_8
	WORD $0xcb15018b // sub	x11, x12, x21
	WORD $0xf100057f // cmp	x11, #1
	BLT  BB3_8
	WORD $0x1e23c2f7 // fcvt	h23, s23
	WORD $0x7c357a97 // str	h23, [x20, x21, lsl #1]
	BEQ  BB3_25
	WORD $0x1e23c2d6 // fcvt	h22, s22
	WORD $0xf94067ec // ldr	x12, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0x7c357996 // str	h22, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB3_25
	WORD $0x1e23c2b5 // fcvt	h21, s21
	WORD $0xf9405bec // ldr	x12, [sp, #176]                 ; 8-byte Folded Reload
	WORD $0x7c357995 // str	h21, [x12, x21, lsl #1]
	BNE  BB3_24
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB3_8
	WORD $0x1e23c272 // fcvt	h18, s19
	WORD $0xa94bb7ec // ldp	x12, x13, [sp, #184]            ; 16-byte Folded Reload
	WORD $0x7c3579b2 // str	h18, [x13, x21, lsl #1]
	WORD $0x1e23c231 // fcvt	h17, s17
	WORD $0x7c357991 // str	h17, [x12, x21, lsl #1]
	WORD $0x5280008c // mov	w12, #4                         ; =0x4
	B    BB3_30

BB3_24:
	WORD $0x1e23c294 // fcvt	h20, s20
	WORD $0xf9404fec // ldr	x12, [sp, #152]                 ; 8-byte Folded Reload
	WORD $0x7c357994 // str	h20, [x12, x21, lsl #1]

BB3_25:
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB3_8
	WORD $0x1e23c273 // fcvt	h19, s19
	WORD $0xf94063ed // ldr	x13, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0x7c3579b3 // str	h19, [x13, x21, lsl #1]
	WORD $0xf100057f // cmp	x11, #1
	BEQ  BB3_31
	WORD $0x1e23c231 // fcvt	h17, s17
	WORD $0xf9405fec // ldr	x12, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0x7c357991 // str	h17, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB3_31
	WORD $0x1e23c210 // fcvt	h16, s16
	WORD $0xf94047ec // ldr	x12, [sp, #136]                 ; 8-byte Folded Reload
	WORD $0x7c357990 // str	h16, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BEQ  BB3_31
	WORD $0x1e604250 // fmov	d16, d18
	WORD $0x528000cc // mov	w12, #6                         ; =0x6

BB3_30:
	WORD $0x8b0c01ac // add	x12, x13, x12
	WORD $0x1e23c210 // fcvt	h16, s16
	WORD $0x7c357990 // str	h16, [x12, x21, lsl #1]

BB3_31:
	WORD $0xf1000e7f // cmp	x19, #3
	BLO  BB3_8
	WORD $0x1e23c0e7 // fcvt	h7, s7
	WORD $0xf94057ec // ldr	x12, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0x7c357987 // str	h7, [x12, x21, lsl #1]
	WORD $0xf100057f // cmp	x11, #1
	BNE  BB3_34
	WORD $0xf94053eb // ldr	x11, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB3_7
	B    BB3_8

BB3_34:
	WORD $0x1e23c0c6 // fcvt	h6, s6
	WORD $0xf9404bec // ldr	x12, [sp, #144]                 ; 8-byte Folded Reload
	WORD $0x7c357986 // str	h6, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB3_37
	WORD $0x1e23c0a5 // fcvt	h5, s5
	WORD $0xf94037eb // ldr	x11, [sp, #104]                 ; 8-byte Folded Reload
	WORD $0x7c357965 // str	h5, [x11, x21, lsl #1]
	BNE  BB3_38
	WORD $0xf94053ed // ldr	x13, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0xf9402fec // ldr	x12, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0xf94027eb // ldr	x11, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB3_5
	B    BB3_8

BB3_37:
	WORD $0xa947afec // ldp	x12, x11, [sp, #120]            ; 16-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB3_6
	B    BB3_8

BB3_38:
	WORD $0x1e23c084 // fcvt	h4, s4
	WORD $0xf9402beb // ldr	x11, [sp, #80]                  ; 8-byte Folded Reload
	WORD $0x7c357964 // str	h4, [x11, x21, lsl #1]
	WORD $0xf1000e7f // cmp	x19, #3
	BEQ  BB3_8
	WORD $0x1e23c000 // fcvt	h0, s0
	WORD $0xf94053eb // ldr	x11, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0x7c357960 // str	h0, [x11, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0xf94043ed // ldr	x13, [sp, #128]                 ; 8-byte Folded Reload
	WORD $0x1e604041 // fmov	d1, d2
	WORD $0xa943b3eb // ldp	x11, x12, [sp, #56]             ; 16-byte Folded Reload
	WORD $0x1e604062 // fmov	d2, d3
	B    BB3_5

TEXT ·matmul_klast_neon_bf16(SB), $304-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf90073f9   // str	x25, [sp, #224]                 ; 8-byte Folded Spill
	WORD $0xa90f5ff8   // stp	x24, x23, [sp, #240]            ; 16-byte Folded Spill
	WORD $0xa91057f6   // stp	x22, x21, [sp, #256]            ; 16-byte Folded Spill
	WORD $0xa9114ff4   // stp	x20, x19, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xa9127bfd   // stp	x29, x30, [sp, #288]            ; 16-byte Folded Spill
	WORD $0xf90043e2   // str	x2, [sp, #128]                  ; 8-byte Folded Spill
	WORD $0xf9001fe1   // str	x1, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf940006e   // ldr	x14, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf10005df   // cmp	x14, #1
	WORD $0xfa41a928   // ccmp	x9, #1, #8, ge
	BGE  BB4_2

BB4_1:
	WORD $0xa9527bfd // ldp	x29, x30, [sp, #288]            ; 16-byte Folded Reload
	WORD $0xa9514ff4 // ldp	x20, x19, [sp, #272]            ; 16-byte Folded Reload
	WORD $0xa95057f6 // ldp	x22, x21, [sp, #256]            ; 16-byte Folded Reload
	WORD $0xa94f5ff8 // ldp	x24, x23, [sp, #240]            ; 16-byte Folded Reload
	WORD $0xf94073f9 // ldr	x25, [sp, #224]                 ; 8-byte Folded Reload
	RET

BB4_2:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0xf94000aa // ldr	x10, [x5]
	WORD $0xf94043e8 // ldr	x8, [sp, #128]                  ; 8-byte Folded Reload
	WORD $0x9100090b // add	x11, x8, #2
	WORD $0xf90033eb // str	x11, [sp, #96]                  ; 8-byte Folded Spill
	WORD $0x9100110b // add	x11, x8, #4
	WORD $0xf90027eb // str	x11, [sp, #72]                  ; 8-byte Folded Spill
	WORD $0x91001908 // add	x8, x8, #6
	WORD $0xa902bbe8 // stp	x8, x14, [sp, #40]              ; 16-byte Folded Spill
	WORD $0x927ef548 // and	x8, x10, #0xfffffffffffffffc
	WORD $0xf9006fe8 // str	x8, [sp, #216]                  ; 8-byte Folded Spill
	WORD $0xd37ff948 // lsl	x8, x10, #1
	WORD $0x8b0a010b // add	x11, x8, x10
	WORD $0xd37ff96b // lsl	x11, x11, #1
	WORD $0xf9401fed // ldr	x13, [sp, #56]                  ; 8-byte Folded Reload
	WORD $0x8b0b01ac // add	x12, x13, x11
	WORD $0xf90013ec // str	x12, [sp, #32]                  ; 8-byte Folded Spill
	WORD $0xd37df151 // lsl	x17, x10, #3
	WORD $0xd37ef54c // lsl	x12, x10, #2
	WORD $0x8b0c01b0 // add	x16, x13, x12
	WORD $0x8b0801ad // add	x13, x13, x8
	WORD $0xa90143ed // stp	x13, x16, [sp, #16]             ; 16-byte Folded Spill
	WORD $0x8b0b0005 // add	x5, x0, x11
	WORD $0x8b0c0006 // add	x6, x0, x12
	WORD $0x8b080007 // add	x7, x0, x8
	B    BB4_4

BB4_3:
	WORD $0x8b1100a5 // add	x5, x5, x17
	WORD $0x8b1100c6 // add	x6, x6, x17
	WORD $0x8b1100e7 // add	x7, x7, x17
	WORD $0x8b110000 // add	x0, x0, x17
	WORD $0xf9401bee // ldr	x14, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xf9403fef // ldr	x15, [sp, #120]                 ; 8-byte Folded Reload
	WORD $0xeb0e01ff // cmp	x15, x14
	BGE  BB4_1

BB4_4:
	WORD $0xd2800015 // mov	x21, #0                         ; =0x0
	WORD $0x910011eb // add	x11, x15, #4
	WORD $0xeb0e017f // cmp	x11, x14
	WORD $0xf9003feb // str	x11, [sp, #120]                 ; 8-byte Folded Spill
	WORD $0x9a8eb16b // csel	x11, x11, x14, lt
	WORD $0xcb0f0173 // sub	x19, x11, x15
	WORD $0xb24001eb // orr	x11, x15, #0x1
	WORD $0xb27f01ec // orr	x12, x15, #0x2
	WORD $0xb24005ed // orr	x13, x15, #0x3
	WORD $0x9b097de8 // mul	x8, x15, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0xf94043ee // ldr	x14, [sp, #128]                 ; 8-byte Folded Reload
	WORD $0x8b0801cf // add	x15, x14, x8
	WORD $0xf90077ef // str	x15, [sp, #232]                 ; 8-byte Folded Spill
	WORD $0xf94033ef // ldr	x15, [sp, #96]                  ; 8-byte Folded Reload
	WORD $0x8b0801f0 // add	x16, x15, x8
	WORD $0xf9006bf0 // str	x16, [sp, #208]                 ; 8-byte Folded Spill
	WORD $0xf94027f0 // ldr	x16, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0x8b080201 // add	x1, x16, x8
	WORD $0xf9005fe1 // str	x1, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf94017e1 // ldr	x1, [sp, #40]                   ; 8-byte Folded Reload
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf90053e8 // str	x8, [sp, #160]                  ; 8-byte Folded Spill
	WORD $0x9b097d68 // mul	x8, x11, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90067eb // str	x11, [sp, #200]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf90063eb // str	x11, [sp, #192]                 ; 8-byte Folded Spill
	WORD $0x8b080208 // add	x8, x16, x8
	WORD $0xf9004be8 // str	x8, [sp, #144]                  ; 8-byte Folded Spill
	WORD $0x9b097d88 // mul	x8, x12, x9
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf9005beb // str	x11, [sp, #176]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf9004feb // str	x11, [sp, #152]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf9002fe8 // str	x8, [sp, #88]                   ; 8-byte Folded Spill
	WORD $0x9b097da8 // mul	x8, x13, x9
	WORD $0xa906afe8 // stp	x8, x11, [sp, #104]             ; 16-byte Folded Spill
	WORD $0xd37ff908 // lsl	x8, x8, #1
	WORD $0x8b0801cb // add	x11, x14, x8
	WORD $0xf90057eb // str	x11, [sp, #168]                 ; 8-byte Folded Spill
	WORD $0x8b0801eb // add	x11, x15, x8
	WORD $0xf90047eb // str	x11, [sp, #136]                 ; 8-byte Folded Spill
	WORD $0x8b08020b // add	x11, x16, x8
	WORD $0xf9002beb // str	x11, [sp, #80]                  ; 8-byte Folded Spill
	WORD $0x8b080028 // add	x8, x1, x8
	WORD $0xf90023e8 // str	x8, [sp, #64]                   ; 8-byte Folded Spill
	WORD $0xf9401ff0 // ldr	x16, [sp, #56]                  ; 8-byte Folded Reload
	WORD $0xa94163e8 // ldp	x8, x24, [sp, #16]              ; 16-byte Folded Reload
	WORD $0xf94013e4 // ldr	x4, [sp, #32]                   ; 8-byte Folded Reload
	B    BB4_9

BB4_5:
	WORD $0x1e634000 // bfcvt	h0, s0
	WORD $0x7c3579a0 // str	h0, [x13, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0x1e604041 // fmov	d1, d2

BB4_6:
	WORD $0xf94037ed // ldr	x13, [sp, #104]                 ; 8-byte Folded Reload
	WORD $0x8b0d058c // add	x12, x12, x13, lsl #1
	WORD $0x1e634000 // bfcvt	h0, s0
	WORD $0x7c357980 // str	h0, [x12, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1

BB4_7:
	WORD $0x1e634000 // bfcvt	h0, s0
	WORD $0x7c357960 // str	h0, [x11, x21, lsl #1]

BB4_8:
	WORD $0x8b110084 // add	x4, x4, x17
	WORD $0x8b110318 // add	x24, x24, x17
	WORD $0x8b110108 // add	x8, x8, x17
	WORD $0x8b110210 // add	x16, x16, x17
	WORD $0xaa0103f5 // mov	x21, x1
	WORD $0xeb09003f // cmp	x1, x9
	BGE  BB4_3

BB4_9:
	WORD $0x910012a1 // add	x1, x21, #4
	WORD $0xeb09003f // cmp	x1, x9
	WORD $0x9a89b02e // csel	x14, x1, x9, lt
	WORD $0xf100115f // cmp	x10, #4
	BGE  BB4_11
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	B    BB4_14

BB4_11:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x6f00e415 // movi.2d	v21, #0000000000000000
	WORD $0x6f00e416 // movi.2d	v22, #0000000000000000
	WORD $0x5280008c // mov	w12, #4                         ; =0x4
	WORD $0x6f00e418 // movi.2d	v24, #0000000000000000
	WORD $0x6f00e414 // movi.2d	v20, #0000000000000000
	WORD $0x6f00e413 // movi.2d	v19, #0000000000000000
	WORD $0x6f00e411 // movi.2d	v17, #0000000000000000
	WORD $0x6f00e410 // movi.2d	v16, #0000000000000000
	WORD $0x6f00e412 // movi.2d	v18, #0000000000000000
	WORD $0x6f00e407 // movi.2d	v7, #0000000000000000
	WORD $0x6f00e406 // movi.2d	v6, #0000000000000000
	WORD $0x6f00e405 // movi.2d	v5, #0000000000000000
	WORD $0x6f00e404 // movi.2d	v4, #0000000000000000
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0x6f00e401 // movi.2d	v1, #0000000000000000
	WORD $0x6f00e402 // movi.2d	v2, #0000000000000000
	WORD $0x6f00e403 // movi.2d	v3, #0000000000000000

BB4_12:
	WORD $0xfc6b6817 // ldr	d23, [x0, x11]
	WORD $0xfc6b68f9 // ldr	d25, [x7, x11]
	WORD $0xfc6b68da // ldr	d26, [x6, x11]
	WORD $0xfc6b68bb // ldr	d27, [x5, x11]
	WORD $0x2e613af7 // shll.4s	v23, v23, #16
	WORD $0x2e613b39 // shll.4s	v25, v25, #16
	WORD $0x2e613b5a // shll.4s	v26, v26, #16
	WORD $0xfc6b6a1c // ldr	d28, [x16, x11]
	WORD $0xfc6b691d // ldr	d29, [x8, x11]
	WORD $0xfc6b6b1e // ldr	d30, [x24, x11]
	WORD $0xfc6b689f // ldr	d31, [x4, x11]
	WORD $0x2e613b7b // shll.4s	v27, v27, #16
	WORD $0x2e613b9c // shll.4s	v28, v28, #16
	WORD $0x2e613bbd // shll.4s	v29, v29, #16
	WORD $0x2e613bde // shll.4s	v30, v30, #16
	WORD $0x2e613bff // shll.4s	v31, v31, #16
	WORD $0x4e37cf95 // fmla.4s	v21, v28, v23
	WORD $0x4e37cfb6 // fmla.4s	v22, v29, v23
	WORD $0x4e37cfd8 // fmla.4s	v24, v30, v23
	WORD $0x4e37cff4 // fmla.4s	v20, v31, v23
	WORD $0x4e39cf93 // fmla.4s	v19, v28, v25
	WORD $0x4e39cfb1 // fmla.4s	v17, v29, v25
	WORD $0x4e39cfd0 // fmla.4s	v16, v30, v25
	WORD $0x4e39cff2 // fmla.4s	v18, v31, v25
	WORD $0x4e3acf87 // fmla.4s	v7, v28, v26
	WORD $0x4e3acfa6 // fmla.4s	v6, v29, v26
	WORD $0x4e3acfc5 // fmla.4s	v5, v30, v26
	WORD $0x4e3acfe4 // fmla.4s	v4, v31, v26
	WORD $0x4e3bcf80 // fmla.4s	v0, v28, v27
	WORD $0x4e3bcfa1 // fmla.4s	v1, v29, v27
	WORD $0x4e3bcfc2 // fmla.4s	v2, v30, v27
	WORD $0x4e3bcfe3 // fmla.4s	v3, v31, v27
	WORD $0x9100118c // add	x12, x12, #4
	WORD $0x9100216b // add	x11, x11, #8
	WORD $0xeb0a019f // cmp	x12, x10
	BLE  BB4_12
	WORD $0xf9406fed // ldr	x13, [sp, #216]                 ; 8-byte Folded Reload

BB4_14:
	WORD $0x6e35d6b5 // faddp.4s	v21, v21, v21
	WORD $0x7e30dab7 // faddp.2s	s23, v21
	WORD $0x6e36d6d5 // faddp.4s	v21, v22, v22
	WORD $0x7e30dab6 // faddp.2s	s22, v21
	WORD $0x6e38d715 // faddp.4s	v21, v24, v24
	WORD $0x7e30dab5 // faddp.2s	s21, v21
	WORD $0x6e34d694 // faddp.4s	v20, v20, v20
	WORD $0x7e30da94 // faddp.2s	s20, v20
	WORD $0x6e33d673 // faddp.4s	v19, v19, v19
	WORD $0x7e30da73 // faddp.2s	s19, v19
	WORD $0x6e31d631 // faddp.4s	v17, v17, v17
	WORD $0x7e30da31 // faddp.2s	s17, v17
	WORD $0x6e30d610 // faddp.4s	v16, v16, v16
	WORD $0x7e30da10 // faddp.2s	s16, v16
	WORD $0x6e32d652 // faddp.4s	v18, v18, v18
	WORD $0x7e30da52 // faddp.2s	s18, v18
	WORD $0x6e27d4e7 // faddp.4s	v7, v7, v7
	WORD $0x7e30d8e7 // faddp.2s	s7, v7
	WORD $0x6e26d4c6 // faddp.4s	v6, v6, v6
	WORD $0x7e30d8c6 // faddp.2s	s6, v6
	WORD $0x6e25d4a5 // faddp.4s	v5, v5, v5
	WORD $0x7e30d8a5 // faddp.2s	s5, v5
	WORD $0x6e24d484 // faddp.4s	v4, v4, v4
	WORD $0x7e30d884 // faddp.2s	s4, v4
	WORD $0x6e20d400 // faddp.4s	v0, v0, v0
	WORD $0x7e30d800 // faddp.2s	s0, v0
	WORD $0x6e21d421 // faddp.4s	v1, v1, v1
	WORD $0x7e30d821 // faddp.2s	s1, v1
	WORD $0x6e22d442 // faddp.4s	v2, v2, v2
	WORD $0x7e30d842 // faddp.2s	s2, v2
	WORD $0x6e23d463 // faddp.4s	v3, v3, v3
	WORD $0x7e30d863 // faddp.2s	s3, v3
	WORD $0xeb0d014c // subs	x12, x10, x13
	BLE  BB4_17
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xd37ff9af // lsl	x15, x13, #1
	WORD $0x8b0f008d // add	x13, x4, x15
	WORD $0x8b0f0317 // add	x23, x24, x15
	WORD $0x8b0f0102 // add	x2, x8, x15
	WORD $0x8b0f0203 // add	x3, x16, x15
	WORD $0x8b0f00be // add	x30, x5, x15
	WORD $0x8b0f00d6 // add	x22, x6, x15
	WORD $0x8b0f00f9 // add	x25, x7, x15
	WORD $0x8b0f000f // add	x15, x0, x15

BB4_16:
	WORD $0x786b79f4 // ldrh	w20, [x15, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e270298 // fmov	s24, w20
	WORD $0x786b7b34 // ldrh	w20, [x25, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e270299 // fmov	s25, w20
	WORD $0x786b7ad4 // ldrh	w20, [x22, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029a // fmov	s26, w20
	WORD $0x786b7bd4 // ldrh	w20, [x30, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029b // fmov	s27, w20
	WORD $0x786b7874 // ldrh	w20, [x3, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029c // fmov	s28, w20
	WORD $0x786b7854 // ldrh	w20, [x2, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029d // fmov	s29, w20
	WORD $0x786b7af4 // ldrh	w20, [x23, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029e // fmov	s30, w20
	WORD $0x786b79b4 // ldrh	w20, [x13, x11, lsl #1]
	WORD $0x53103e94 // lsl	w20, w20, #16
	WORD $0x1e27029f // fmov	s31, w20
	WORD $0x1f1c5f17 // fmadd	s23, s24, s28, s23
	WORD $0x1f1d5b16 // fmadd	s22, s24, s29, s22
	WORD $0x1f1e5715 // fmadd	s21, s24, s30, s21
	WORD $0x1f1f5314 // fmadd	s20, s24, s31, s20
	WORD $0x1f1c4f33 // fmadd	s19, s25, s28, s19
	WORD $0x1f1d4731 // fmadd	s17, s25, s29, s17
	WORD $0x1f1e4330 // fmadd	s16, s25, s30, s16
	WORD $0x1f1f4b32 // fmadd	s18, s25, s31, s18
	WORD $0x1f1c1f47 // fmadd	s7, s26, s28, s7
	WORD $0x1f1d1b46 // fmadd	s6, s26, s29, s6
	WORD $0x1f1e1745 // fmadd	s5, s26, s30, s5
	WORD $0x1f1f1344 // fmadd	s4, s26, s31, s4
	WORD $0x1f1c0360 // fmadd	s0, s27, s28, s0
	WORD $0x1f1d0761 // fmadd	s1, s27, s29, s1
	WORD $0x1f1e0b62 // fmadd	s2, s27, s30, s2
	WORD $0x1f1f0f63 // fmadd	s3, s27, s31, s3
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0xeb0b019f // cmp	x12, x11
	BNE  BB4_16

BB4_17:
	WORD $0xf100067f // cmp	x19, #1
	BLT  BB4_8
	WORD $0xcb1501cb // sub	x11, x14, x21
	WORD $0xf100057f // cmp	x11, #1
	BLT  BB4_8
	WORD $0x1e6342f7 // bfcvt	h23, s23
	WORD $0xf94077ec // ldr	x12, [sp, #232]                 ; 8-byte Folded Reload
	WORD $0x7c357997 // str	h23, [x12, x21, lsl #1]
	WORD $0xf100057f // cmp	x11, #1
	BEQ  BB4_25
	WORD $0x1e6342d6 // bfcvt	h22, s22
	WORD $0xf9406bec // ldr	x12, [sp, #208]                 ; 8-byte Folded Reload
	WORD $0x7c357996 // str	h22, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB4_25
	WORD $0x1e6342b5 // bfcvt	h21, s21
	WORD $0xf9405fec // ldr	x12, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0x7c357995 // str	h21, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BNE  BB4_24
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB4_8
	WORD $0x1e634272 // bfcvt	h18, s19
	WORD $0xd37ffaac // lsl	x12, x21, #1
	WORD $0xa94c37ee // ldp	x14, x13, [sp, #192]            ; 16-byte Folded Reload
	WORD $0x7c2c69b2 // str	h18, [x13, x12]
	WORD $0x1e634231 // bfcvt	h17, s17
	WORD $0x7c2c69d1 // str	h17, [x14, x12]
	WORD $0x5280008c // mov	w12, #4                         ; =0x4
	B    BB4_30

BB4_24:
	WORD $0x1e634294 // bfcvt	h20, s20
	WORD $0xf94053ec // ldr	x12, [sp, #160]                 ; 8-byte Folded Reload
	WORD $0x7c357994 // str	h20, [x12, x21, lsl #1]

BB4_25:
	WORD $0xf100067f // cmp	x19, #1
	BEQ  BB4_8
	WORD $0x1e634273 // bfcvt	h19, s19
	WORD $0xf94067ed // ldr	x13, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0x7c3579b3 // str	h19, [x13, x21, lsl #1]
	WORD $0xf100057f // cmp	x11, #1
	BEQ  BB4_31
	WORD $0x1e634231 // bfcvt	h17, s17
	WORD $0xf94063ec // ldr	x12, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0x7c357991 // str	h17, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB4_31
	WORD $0x1e634210 // bfcvt	h16, s16
	WORD $0xf9404bec // ldr	x12, [sp, #144]                 ; 8-byte Folded Reload
	WORD $0x7c357990 // str	h16, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BEQ  BB4_31
	WORD $0x1e604250 // fmov	d16, d18
	WORD $0x528000cc // mov	w12, #6                         ; =0x6

BB4_30:
	WORD $0x8b0c01ac // add	x12, x13, x12
	WORD $0x1e634210 // bfcvt	h16, s16
	WORD $0x7c357990 // str	h16, [x12, x21, lsl #1]

BB4_31:
	WORD $0xf1000e7f // cmp	x19, #3
	BLO  BB4_8
	WORD $0x1e6340e7 // bfcvt	h7, s7
	WORD $0xf9405bec // ldr	x12, [sp, #176]                 ; 8-byte Folded Reload
	WORD $0x7c357987 // str	h7, [x12, x21, lsl #1]
	WORD $0xf100057f // cmp	x11, #1
	BNE  BB4_34
	WORD $0xf94057eb // ldr	x11, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB4_7
	B    BB4_8

BB4_34:
	WORD $0x1e6340c6 // bfcvt	h6, s6
	WORD $0xf9404fec // ldr	x12, [sp, #152]                 ; 8-byte Folded Reload
	WORD $0x7c357986 // str	h6, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BLO  BB4_37
	WORD $0x1e6340a5 // bfcvt	h5, s5
	WORD $0xf9403bec // ldr	x12, [sp, #112]                 ; 8-byte Folded Reload
	WORD $0x7c357985 // str	h5, [x12, x21, lsl #1]
	WORD $0xf1000d7f // cmp	x11, #3
	BNE  BB4_38
	WORD $0xf94057ed // ldr	x13, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0xf94033ec // ldr	x12, [sp, #96]                  ; 8-byte Folded Reload
	WORD $0xf9402beb // ldr	x11, [sp, #80]                  ; 8-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB4_5
	B    BB4_8

BB4_37:
	WORD $0xa9482fec // ldp	x12, x11, [sp, #128]            ; 16-byte Folded Reload
	WORD $0xf1000e7f // cmp	x19, #3
	BNE  BB4_6
	B    BB4_8

BB4_38:
	WORD $0x1e634084 // bfcvt	h4, s4
	WORD $0xf9402feb // ldr	x11, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0x7c357964 // str	h4, [x11, x21, lsl #1]
	WORD $0xf1000e7f // cmp	x19, #3
	BEQ  BB4_8
	WORD $0x1e634000 // bfcvt	h0, s0
	WORD $0xf94057eb // ldr	x11, [sp, #168]                 ; 8-byte Folded Reload
	WORD $0x7c357960 // str	h0, [x11, x21, lsl #1]
	WORD $0x1e604020 // fmov	d0, d1
	WORD $0xf94047ed // ldr	x13, [sp, #136]                 ; 8-byte Folded Reload
	WORD $0x1e604041 // fmov	d1, d2
	WORD $0xa94433eb // ldp	x11, x12, [sp, #64]             ; 16-byte Folded Reload
	WORD $0x1e604062 // fmov	d2, d3
	B    BB4_5
