//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8-a -O3
// source: ../c/matmul_blocked_neon_f32f64_arm64.c

TEXT ·blocked_matmul_neon_f32(SB), $368-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf90093f9   // str	x25, [sp, #288]                 ; 8-byte Folded Spill
	WORD $0xa9135ff8   // stp	x24, x23, [sp, #304]            ; 16-byte Folded Spill
	WORD $0xa91457f6   // stp	x22, x21, [sp, #320]            ; 16-byte Folded Spill
	WORD $0xa9154ff4   // stp	x20, x19, [sp, #336]            ; 16-byte Folded Spill
	WORD $0xa9167bfd   // stp	x29, x30, [sp, #352]            ; 16-byte Folded Spill
	WORD $0xf90087e2   // str	x2, [sp, #264]                  ; 8-byte Folded Spill
	WORD $0xf9001fe1   // str	x1, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf9005fe0   // str	x0, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf940006d   // ldr	x13, [x3]
	WORD $0xf940009e   // ldr	x30, [x4]
	WORD $0xf94000b1   // ldr	x17, [x5]
	WORD $0x9b0d7fc8   // mul	x8, x30, x13
	WORD $0xf100051f   // cmp	x8, #1
	BLT  BB0_14
	WORD $0xf1000d1f   // cmp	x8, #3
	BHI  BB0_3
	WORD $0xd2800009   // mov	x9, #0                          ; =0x0
	B    BB0_12

BB0_3:
	WORD $0xf100411f // cmp	x8, #16
	BHS  BB0_5
	WORD $0xd2800009 // mov	x9, #0                          ; =0x0
	B    BB0_9

BB0_5:
	WORD $0x927ce909 // and	x9, x8, #0x7ffffffffffffff0
	WORD $0xf94087ea // ldr	x10, [sp, #264]                 ; 8-byte Folded Reload
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0903eb // mov	x11, x9

BB0_6:
	WORD $0xad3f0140 // stp	q0, q0, [x10, #-32]
	WORD $0xac820140 // stp	q0, q0, [x10], #64
	WORD $0xf100416b // subs	x11, x11, #16
	BNE  BB0_6
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB0_14
	WORD $0xf27e051f // tst	x8, #0xc
	BEQ  BB0_12

BB0_9:
	WORD $0xaa0903eb // mov	x11, x9
	WORD $0x927ef109 // and	x9, x8, #0x7ffffffffffffffc
	WORD $0xcb09016a // sub	x10, x11, x9
	WORD $0xf94087ec // ldr	x12, [sp, #264]                 ; 8-byte Folded Reload
	WORD $0x8b0b098b // add	x11, x12, x11, lsl #2

BB0_10:
	WORD $0xa8817d7f // stp	xzr, xzr, [x11], #16
	WORD $0xb100114a // adds	x10, x10, #4
	BNE  BB0_10
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB0_14

BB0_12:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xf94087ea // ldr	x10, [sp, #264]                 ; 8-byte Folded Reload
	WORD $0x8b090949 // add	x9, x10, x9, lsl #2

BB0_13:
	WORD $0xb800453f // str	wzr, [x9], #4
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB0_13

BB0_14:
	WORD $0xf10005bf // cmp	x13, #1
	WORD $0xfa41abc8 // ccmp	x30, #1, #8, ge
	WORD $0xfa41aa28 // ccmp	x17, #1, #8, ge
	BGE  BB0_16

BB0_15:
	WORD $0xa9567bfd // ldp	x29, x30, [sp, #352]            ; 16-byte Folded Reload
	WORD $0xa9554ff4 // ldp	x20, x19, [sp, #336]            ; 16-byte Folded Reload
	WORD $0xa95457f6 // ldp	x22, x21, [sp, #320]            ; 16-byte Folded Reload
	WORD $0xa9535ff8 // ldp	x24, x23, [sp, #304]            ; 16-byte Folded Reload
	WORD $0xf94093f9 // ldr	x25, [sp, #288]                 ; 8-byte Folded Reload
	RET

BB0_16:
	WORD $0xd2800018 // mov	x24, #0                         ; =0x0
	WORD $0x8b1e07c8 // add	x8, x30, x30, lsl #1
	WORD $0xd37ae508 // lsl	x8, x8, #6
	WORD $0xf90037e8 // str	x8, [sp, #104]                  ; 8-byte Folded Spill
	WORD $0xd37ef7cc // lsl	x12, x30, #2
	WORD $0x8b110628 // add	x8, x17, x17, lsl #1
	WORD $0xf9405fe9 // ldr	x9, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0xf90027e9 // str	x9, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf9401fe9 // ldr	x9, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0x9100c12b // add	x11, x9, #48
	WORD $0x9100412a // add	x10, x9, #16
	WORD $0xa9022fea // stp	x10, x11, [sp, #32]             ; 16-byte Folded Spill
	WORD $0xd37ae50a // lsl	x10, x8, #6
	WORD $0x91008128 // add	x8, x9, #32
	WORD $0xa9012be8 // stp	x8, x10, [sp, #16]              ; 16-byte Folded Spill
	WORD $0xd37ef628 // lsl	x8, x17, #2
	WORD $0xa90ffbe8 // stp	x8, x30, [sp, #248]             ; 16-byte Folded Spill
	WORD $0xf90057f1 // str	x17, [sp, #168]                 ; 8-byte Folded Spill
	WORD $0xf9001bed // str	x13, [sp, #48]                  ; 8-byte Folded Spill
	B    BB0_18

BB0_17:
	WORD $0xf9405fe8 // ldr	x8, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf9400fe9 // ldr	x9, [sp, #24]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf9005fe8 // str	x8, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf94027e8 // ldr	x8, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf90027e8 // str	x8, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf94023e8 // ldr	x8, [sp, #64]                   ; 8-byte Folded Reload
	WORD $0xaa0803f8 // mov	x24, x8
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xeb0d011f // cmp	x8, x13
	BGE  BB0_15

BB0_18:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0x9100c308 // add	x8, x24, #48
	WORD $0xeb0d011f // cmp	x8, x13
	WORD $0xf90023e8 // str	x8, [sp, #64]                   ; 8-byte Folded Spill
	WORD $0x9a8db108 // csel	x8, x8, x13, lt
	WORD $0xf9008be8 // str	x8, [sp, #272]                  ; 8-byte Folded Spill
	WORD $0xf9400bea // ldr	x10, [sp, #16]                  ; 8-byte Folded Reload
	WORD $0xa94227e8 // ldp	x8, x9, [sp, #32]               ; 16-byte Folded Reload
	WORD $0xf9006be8 // str	x8, [sp, #208]                  ; 8-byte Folded Spill
	WORD $0xf9401fe8 // ldr	x8, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0xf90067e8 // str	x8, [sp, #200]                  ; 8-byte Folded Spill
	WORD $0xf9005bf8 // str	x24, [sp, #176]                 ; 8-byte Folded Spill
	B    BB0_20

BB0_19:
	WORD $0xa94ca3eb // ldp	x11, x8, [sp, #200]             ; 16-byte Folded Reload
	WORD $0x9103016a // add	x10, x11, #192
	WORD $0xf9402fe9 // ldr	x9, [sp, #88]                   ; 8-byte Folded Reload
	WORD $0x91030129 // add	x9, x9, #192
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xa90ca3ea // stp	x10, x8, [sp, #200]             ; 16-byte Folded Spill
	WORD $0xf94033ea // ldr	x10, [sp, #96]                  ; 8-byte Folded Reload
	WORD $0x9103014a // add	x10, x10, #192
	WORD $0xf9402be8 // ldr	x8, [sp, #80]                   ; 8-byte Folded Reload
	WORD $0xaa0803eb // mov	x11, x8
	WORD $0xeb1e011f // cmp	x8, x30
	BGE  BB0_17

BB0_20:
	WORD $0x9100c168 // add	x8, x11, #48
	WORD $0xeb1e011f // cmp	x8, x30
	WORD $0xa90527e8 // stp	x8, x9, [sp, #80]               ; 16-byte Folded Spill
	WORD $0x9a9eb119 // csel	x25, x8, x30, lt
	WORD $0xf9008feb // str	x11, [sp, #280]                 ; 8-byte Folded Spill
	WORD $0xb27e0168 // orr	x8, x11, #0x4
	WORD $0xf90063e8 // str	x8, [sp, #192]                  ; 8-byte Folded Spill
	WORD $0xeb19011f // cmp	x8, x25
	WORD $0xf90033ea // str	x10, [sp, #96]                  ; 8-byte Folded Spill
	BLE  BB0_40
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xd2800001 // mov	x1, #0                          ; =0x0
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0xf94027e5 // ldr	x5, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	WORD $0x5280060f // mov	w15, #48                        ; =0x30
	B    BB0_23

BB0_22:
	WORD $0xa94e87e5 // ldp	x5, x1, [sp, #232]              ; 16-byte Folded Reload
	WORD $0x91000421 // add	x1, x1, #1
	WORD $0x9100c1ef // add	x15, x15, #48
	WORD $0xa94da7e8 // ldp	x8, x9, [sp, #216]              ; 16-byte Folded Reload
	WORD $0x9100c129 // add	x9, x9, #48
	WORD $0xf94097ed // ldr	x13, [sp, #296]                 ; 8-byte Folded Reload
	WORD $0xd100c1ad // sub	x13, x13, #48
	WORD $0x910300a5 // add	x5, x5, #192
	WORD $0x9103014a // add	x10, x10, #192
	WORD $0xaa0803f0 // mov	x16, x8
	WORD $0xa94ae3f1 // ldp	x17, x24, [sp, #168]            ; 16-byte Folded Reload
	WORD $0xeb11011f // cmp	x8, x17
	BGE  BB0_19

BB0_23:
	WORD $0xeb0f023f // cmp	x17, x15
	WORD $0x9a8fb228 // csel	x8, x17, x15, lt
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0xf90073e9 // str	x9, [sp, #224]                  ; 8-byte Folded Spill
	WORD $0x9a89c108 // csel	x8, x8, x9, gt
	WORD $0x92400509 // and	x9, x8, #0x3
	WORD $0x92400d0b // and	x11, x8, #0xf
	WORD $0xf90097ed // str	x13, [sp, #296]                 ; 8-byte Folded Spill
	WORD $0x8b0d0108 // add	x8, x8, x13
	WORD $0xcb0b010e // sub	x14, x8, x11
	WORD $0x9100c20b // add	x11, x16, #48
	WORD $0xeb0b023f // cmp	x17, x11
	WORD $0xf9006feb // str	x11, [sp, #216]                 ; 8-byte Folded Spill
	WORD $0x9a8bb220 // csel	x0, x17, x11, lt
	WORD $0xb240020b // orr	x11, x16, #0x1
	WORD $0xeb0b001f // cmp	x0, x11
	WORD $0x9a90c40b // csinc	x11, x0, x16, gt
	WORD $0x928005ed // mov	x13, #-48                       ; =0xffffffffffffffd0
	WORD $0xa90e87e5 // stp	x5, x1, [sp, #232]              ; 16-byte Folded Spill
	WORD $0x9b0d2c21 // madd	x1, x1, x13, x11
	WORD $0xf1000c3f // cmp	x1, #3
	WORD $0xfa418bc0 // ccmp	x30, #1, #0, hi
	WORD $0x1a9f17e2 // cset	w2, eq
	WORD $0x92400d63 // and	x3, x11, #0xf
	WORD $0xcb030024 // sub	x4, x1, x3
	WORD $0x8b040206 // add	x6, x16, x4
	WORD $0x92400567 // and	x7, x11, #0x3
	WORD $0xcb07002b // sub	x11, x1, x7
	WORD $0x8b0b0213 // add	x19, x16, x11
	WORD $0xcb090114 // sub	x20, x8, x9
	WORD $0xf9405ff5 // ldr	x21, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0xaa0503ed // mov	x13, x5
	WORD $0xaa1803f7 // mov	x23, x24
	B    BB0_25

BB0_24:
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0xa94ffbe8 // ldp	x8, x30, [sp, #248]             ; 16-byte Folded Reload
	WORD $0x8b0801ad // add	x13, x13, x8
	WORD $0x8b0802b5 // add	x21, x21, x8
	WORD $0xf9408be8 // ldr	x8, [sp, #272]                  ; 8-byte Folded Reload
	WORD $0xeb0802ff // cmp	x23, x8
	BGE  BB0_22

BB0_25:
	WORD $0x9b1e7ee8 // mul	x8, x23, x30
	WORD $0xf94087e9 // ldr	x9, [sp, #264]                  ; 8-byte Folded Reload
	WORD $0x8b080938 // add	x24, x9, x8, lsl #2
	WORD $0xf94067fe // ldr	x30, [sp, #200]                 ; 8-byte Folded Reload
	WORD $0xaa0a03e9 // mov	x9, x10
	WORD $0xf9408fe8 // ldr	x8, [sp, #280]                  ; 8-byte Folded Reload
	B    BB0_27

BB0_26:
	WORD $0xbc287b00 // str	s0, [x24, x8, lsl #2]
	WORD $0x91000508 // add	x8, x8, #1
	WORD $0x91001129 // add	x9, x9, #4
	WORD $0x910013de // add	x30, x30, #4
	WORD $0xeb19011f // cmp	x8, x25
	BGE  BB0_24

BB0_27:
	WORD $0xbc687b00 // ldr	s0, [x24, x8, lsl #2]
	WORD $0x340000a2 // cbz	w2, LBB0_30
	WORD $0xf100403f // cmp	x1, #16
	BHS  BB0_31
	WORD $0xd2800011 // mov	x17, #0                         ; =0x0
	B    BB0_35

BB0_30:
	WORD $0xaa1003eb // mov	x11, x16
	B    BB0_38

BB0_31:
	WORD $0xaa0903eb // mov	x11, x9
	WORD $0xaa0d03f6 // mov	x22, x13
	WORD $0xaa0e03f1 // mov	x17, x14

BB0_32:
	WORD $0xad7f0ac1 // ldp	q1, q2, [x22, #-32]
	WORD $0xacc212c3 // ldp	q3, q4, [x22], #64
	WORD $0xad7f1965 // ldp	q5, q6, [x11, #-32]
	WORD $0xacc24167 // ldp	q7, q16, [x11], #64
	WORD $0x6e25dc21 // fmul.4s	v1, v1, v5
	WORD $0x5e1c0425 // mov	s5, v1[3]
	WORD $0x5e140431 // mov	s17, v1[2]
	WORD $0x5e0c0432 // mov	s18, v1[1]
	WORD $0x6e26dc42 // fmul.4s	v2, v2, v6
	WORD $0x5e1c0446 // mov	s6, v2[3]
	WORD $0x5e140453 // mov	s19, v2[2]
	WORD $0x5e0c0454 // mov	s20, v2[1]
	WORD $0x6e27dc63 // fmul.4s	v3, v3, v7
	WORD $0x5e1c0467 // mov	s7, v3[3]
	WORD $0x5e140475 // mov	s21, v3[2]
	WORD $0x5e0c0476 // mov	s22, v3[1]
	WORD $0x6e30dc84 // fmul.4s	v4, v4, v16
	WORD $0x5e1c0490 // mov	s16, v4[3]
	WORD $0x5e140497 // mov	s23, v4[2]
	WORD $0x5e0c0498 // mov	s24, v4[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e322800 // fadd	s0, s0, s18
	WORD $0x1e312800 // fadd	s0, s0, s17
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e342800 // fadd	s0, s0, s20
	WORD $0x1e332800 // fadd	s0, s0, s19
	WORD $0x1e262800 // fadd	s0, s0, s6
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e362800 // fadd	s0, s0, s22
	WORD $0x1e352800 // fadd	s0, s0, s21
	WORD $0x1e272800 // fadd	s0, s0, s7
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e382800 // fadd	s0, s0, s24
	WORD $0x1e372800 // fadd	s0, s0, s23
	WORD $0x1e302800 // fadd	s0, s0, s16
	WORD $0xf1004231 // subs	x17, x17, #16
	BNE  BB0_32
	WORD $0xb4fff923 // cbz	x3, LBB0_26
	WORD $0xaa0403f1 // mov	x17, x4
	WORD $0xaa0603eb // mov	x11, x6
	WORD $0xf100107f // cmp	x3, #4
	BLO  BB0_38

BB0_35:
	WORD $0xcb11028b // sub	x11, x20, x17
	WORD $0x8b110211 // add	x17, x16, x17
	WORD $0xd37ef625 // lsl	x5, x17, #2
	WORD $0x8b0503d1 // add	x17, x30, x5
	WORD $0x8b0502b6 // add	x22, x21, x5

BB0_36:
	WORD $0x3cc106c1 // ldr	q1, [x22], #16
	WORD $0x3cc10622 // ldr	q2, [x17], #16
	WORD $0x6e22dc21 // fmul.4s	v1, v1, v2
	WORD $0x5e1c0422 // mov	s2, v1[3]
	WORD $0x5e140423 // mov	s3, v1[2]
	WORD $0x5e0c0424 // mov	s4, v1[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0xf100116b // subs	x11, x11, #4
	BNE  BB0_36
	WORD $0xaa1303eb // mov	x11, x19
	WORD $0xb4fff647 // cbz	x7, LBB0_26

BB0_38:
	WORD $0x9b0b7d91 // mul	x17, x12, x11

BB0_39:
	WORD $0xbc6b7aa1 // ldr	s1, [x21, x11, lsl #2]
	WORD $0xbc716bc2 // ldr	s2, [x30, x17]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x8b0c0231 // add	x17, x17, x12
	WORD $0xeb00017f // cmp	x11, x0
	BLT  BB0_39
	B    BB0_26

BB0_40:
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xd2800013 // mov	x19, #0                         ; =0x0
	WORD $0xf9406be8 // ldr	x8, [sp, #208]                  ; 8-byte Folded Reload
	WORD $0xa90ea3e9 // stp	x9, x8, [sp, #232]              ; 16-byte Folded Spill
	WORD $0xf94027f5 // ldr	x21, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	WORD $0x5280060a // mov	w10, #48                        ; =0x30
	WORD $0xf9405ff0 // ldr	x16, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0xf94067e8 // ldr	x8, [sp, #200]                  ; 8-byte Folded Reload
	WORD $0xf90073e8 // str	x8, [sp, #224]                  ; 8-byte Folded Spill
	B    BB0_42

BB0_41:
	WORD $0xa949afed // ldp	x13, x11, [sp, #152]            ; 16-byte Folded Reload
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xf94037e8 // ldr	x8, [sp, #104]                  ; 8-byte Folded Reload
	WORD $0xf94073e9 // ldr	x9, [sp, #224]                  ; 8-byte Folded Reload
	WORD $0x8b080129 // add	x9, x9, x8
	WORD $0xf90073e9 // str	x9, [sp, #224]                  ; 8-byte Folded Spill
	WORD $0xa947abf0 // ldp	x16, x10, [sp, #120]            ; 16-byte Folded Reload
	WORD $0x91030210 // add	x16, x16, #192
	WORD $0x9100c14a // add	x10, x10, #48
	WORD $0xa948d7e9 // ldp	x9, x21, [sp, #136]             ; 16-byte Folded Reload
	WORD $0x9100c129 // add	x9, x9, #48
	WORD $0xd100c16b // sub	x11, x11, #48
	WORD $0x910302b5 // add	x21, x21, #192
	WORD $0xf94077e8 // ldr	x8, [sp, #232]                  ; 8-byte Folded Reload
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xf90077e8 // str	x8, [sp, #232]                  ; 8-byte Folded Spill
	WORD $0xf9407be8 // ldr	x8, [sp, #240]                  ; 8-byte Folded Reload
	WORD $0x91030108 // add	x8, x8, #192
	WORD $0xf9007be8 // str	x8, [sp, #240]                  ; 8-byte Folded Spill
	WORD $0xf9403be8 // ldr	x8, [sp, #112]                  ; 8-byte Folded Reload
	WORD $0xaa0803f3 // mov	x19, x8
	WORD $0xa94ae3f1 // ldp	x17, x24, [sp, #168]            ; 16-byte Folded Reload
	WORD $0xeb11011f // cmp	x8, x17
	BGE  BB0_19

BB0_42:
	WORD $0xeb0a023f // cmp	x17, x10
	WORD $0xa90827ea // stp	x10, x9, [sp, #128]             ; 16-byte Folded Spill
	WORD $0x9a8ab228 // csel	x8, x17, x10, lt
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0x9a89c108 // csel	x8, x8, x9, gt
	WORD $0x92400509 // and	x9, x8, #0x3
	WORD $0x92400d0a // and	x10, x8, #0xf
	WORD $0xa909afed // stp	x13, x11, [sp, #152]            ; 16-byte Folded Spill
	WORD $0x8b0b0108 // add	x8, x8, x11
	WORD $0xcb0a0114 // sub	x20, x8, x10
	WORD $0x9100c26a // add	x10, x19, #48
	WORD $0xeb0a023f // cmp	x17, x10
	WORD $0xa90743ea // stp	x10, x16, [sp, #112]            ; 16-byte Folded Spill
	WORD $0x9a8ab224 // csel	x4, x17, x10, lt
	WORD $0xb240026a // orr	x10, x19, #0x1
	WORD $0xeb0a009f // cmp	x4, x10
	WORD $0x9a93c48b // csinc	x11, x4, x19, gt
	WORD $0x928005ea // mov	x10, #-48                       ; =0xffffffffffffffd0
	WORD $0x9b0a2db1 // madd	x17, x13, x10, x11
	WORD $0xf1000e3f // cmp	x17, #3
	WORD $0xfa418bc0 // ccmp	x30, #1, #0, hi
	WORD $0x1a9f17ee // cset	w14, eq
	WORD $0x92400d6a // and	x10, x11, #0xf
	WORD $0xcb0a0227 // sub	x7, x17, x10
	WORD $0x8b070261 // add	x1, x19, x7
	WORD $0x92400560 // and	x0, x11, #0x3
	WORD $0xcb00022b // sub	x11, x17, x0
	WORD $0x8b0b026d // add	x13, x19, x11
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xf90097e8 // str	x8, [sp, #296]                  ; 8-byte Folded Spill
	WORD $0xf9405fe8 // ldr	x8, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf9004bf5 // str	x21, [sp, #144]                 ; 8-byte Folded Spill
	WORD $0xf9006fed // str	x13, [sp, #216]                 ; 8-byte Folded Spill
	B    BB0_44

BB0_43:
	WORD $0x91000718 // add	x24, x24, #1
	WORD $0xf9407fe9 // ldr	x9, [sp, #248]                  ; 8-byte Folded Reload
	WORD $0x8b090210 // add	x16, x16, x9
	WORD $0x8b0902b5 // add	x21, x21, x9
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf9408be9 // ldr	x9, [sp, #272]                  ; 8-byte Folded Reload
	WORD $0xeb09031f // cmp	x24, x9
	BGE  BB0_41

BB0_44:
	WORD $0xaa0003ed // mov	x13, x0
	WORD $0xaa0103e0 // mov	x0, x1
	WORD $0xaa1403e1 // mov	x1, x20
	WORD $0xaa0703f4 // mov	x20, x7
	WORD $0x9b1e7f09 // mul	x9, x24, x30
	WORD $0xf94087eb // ldr	x11, [sp, #264]                 ; 8-byte Folded Reload
	WORD $0x8b090969 // add	x9, x11, x9, lsl #2
	WORD $0xf9406be2 // ldr	x2, [sp, #208]                  ; 8-byte Folded Reload
	WORD $0xa94e9ffe // ldp	x30, x7, [sp, #232]             ; 16-byte Folded Reload
	WORD $0xf94073f6 // ldr	x22, [sp, #224]                 ; 8-byte Folded Reload
	WORD $0xf94063e6 // ldr	x6, [sp, #192]                  ; 8-byte Folded Reload
	WORD $0xf9408ff7 // ldr	x23, [sp, #280]                 ; 8-byte Folded Reload

BB0_45:
	WORD $0x8b17092b // add	x11, x9, x23, lsl #2
	WORD $0xaa0603f7 // mov	x23, x6
	WORD $0xaa1e03e3 // mov	x3, x30
	WORD $0xaa0703ef // mov	x15, x7
	WORD $0xaa0203e5 // mov	x5, x2
	WORD $0x3dc00160 // ldr	q0, [x11]
	WORD $0xaa1003e2 // mov	x2, x16
	WORD $0xaa1603e6 // mov	x6, x22
	WORD $0xaa1303e7 // mov	x7, x19

BB0_46:
	WORD $0xbc404441 // ldr	s1, [x2], #4
	WORD $0x3dc000c2 // ldr	q2, [x6]
	WORD $0x4f811040 // fmla.4s	v0, v2, v1[0]
	WORD $0x910004e7 // add	x7, x7, #1
	WORD $0x8b0c00c6 // add	x6, x6, x12
	WORD $0xeb0400ff // cmp	x7, x4
	BLT  BB0_46
	WORD $0x910012e6 // add	x6, x23, #4
	WORD $0x910042d6 // add	x22, x22, #16
	WORD $0x3d800160 // str	q0, [x11]
	WORD $0x9100407e // add	x30, x3, #16
	WORD $0x910041e7 // add	x7, x15, #16
	WORD $0x910040a2 // add	x2, x5, #16
	WORD $0xeb1900df // cmp	x6, x25
	BLE  BB0_45
	WORD $0xeb1902ff // cmp	x23, x25
	WORD $0xf94083fe // ldr	x30, [sp, #256]                 ; 8-byte Folded Reload
	WORD $0xaa1403e7 // mov	x7, x20
	WORD $0xaa0103f4 // mov	x20, x1
	WORD $0xaa0003e1 // mov	x1, x0
	WORD $0xaa0d03e0 // mov	x0, x13
	WORD $0xf9406fed // ldr	x13, [sp, #216]                 ; 8-byte Folded Reload
	BLT  BB0_50
	B    BB0_43

BB0_49:
	WORD $0xbc377920 // str	s0, [x9, x23, lsl #2]
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0x91001063 // add	x3, x3, #4
	WORD $0x910011ef // add	x15, x15, #4
	WORD $0x910010a5 // add	x5, x5, #4
	WORD $0xeb1902ff // cmp	x23, x25
	BGE  BB0_43

BB0_50:
	WORD $0xbc777920 // ldr	s0, [x9, x23, lsl #2]
	WORD $0x340000ae // cbz	w14, LBB0_53
	WORD $0xf100423f // cmp	x17, #16
	BHS  BB0_54
	WORD $0xd2800002 // mov	x2, #0                          ; =0x0
	B    BB0_58

BB0_53:
	WORD $0xaa1303eb // mov	x11, x19
	B    BB0_61

BB0_54:
	WORD $0xaa0303f6 // mov	x22, x3
	WORD $0xaa1503e6 // mov	x6, x21
	WORD $0xaa1403eb // mov	x11, x20

BB0_55:
	WORD $0xad7f08c1 // ldp	q1, q2, [x6, #-32]
	WORD $0xacc210c3 // ldp	q3, q4, [x6], #64
	WORD $0xad7f1ac5 // ldp	q5, q6, [x22, #-32]
	WORD $0xacc242c7 // ldp	q7, q16, [x22], #64
	WORD $0x6e25dc21 // fmul.4s	v1, v1, v5
	WORD $0x5e1c0425 // mov	s5, v1[3]
	WORD $0x5e140431 // mov	s17, v1[2]
	WORD $0x5e0c0432 // mov	s18, v1[1]
	WORD $0x6e26dc42 // fmul.4s	v2, v2, v6
	WORD $0x5e1c0446 // mov	s6, v2[3]
	WORD $0x5e140453 // mov	s19, v2[2]
	WORD $0x5e0c0454 // mov	s20, v2[1]
	WORD $0x6e27dc63 // fmul.4s	v3, v3, v7
	WORD $0x5e1c0467 // mov	s7, v3[3]
	WORD $0x5e140475 // mov	s21, v3[2]
	WORD $0x5e0c0476 // mov	s22, v3[1]
	WORD $0x6e30dc84 // fmul.4s	v4, v4, v16
	WORD $0x5e1c0490 // mov	s16, v4[3]
	WORD $0x5e140497 // mov	s23, v4[2]
	WORD $0x5e0c0498 // mov	s24, v4[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e322800 // fadd	s0, s0, s18
	WORD $0x1e312800 // fadd	s0, s0, s17
	WORD $0x1e252800 // fadd	s0, s0, s5
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x1e342800 // fadd	s0, s0, s20
	WORD $0x1e332800 // fadd	s0, s0, s19
	WORD $0x1e262800 // fadd	s0, s0, s6
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e362800 // fadd	s0, s0, s22
	WORD $0x1e352800 // fadd	s0, s0, s21
	WORD $0x1e272800 // fadd	s0, s0, s7
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e382800 // fadd	s0, s0, s24
	WORD $0x1e372800 // fadd	s0, s0, s23
	WORD $0x1e302800 // fadd	s0, s0, s16
	WORD $0xf100416b // subs	x11, x11, #16
	BNE  BB0_55
	WORD $0xb4fff90a // cbz	x10, LBB0_49
	WORD $0xaa0703e2 // mov	x2, x7
	WORD $0xaa0103eb // mov	x11, x1
	WORD $0xf100115f // cmp	x10, #4
	BLO  BB0_61

BB0_58:
	WORD $0xf94097eb // ldr	x11, [sp, #296]                 ; 8-byte Folded Reload
	WORD $0xcb02016b // sub	x11, x11, x2
	WORD $0xd37ef446 // lsl	x6, x2, #2

BB0_59:
	WORD $0x3ce66a01 // ldr	q1, [x16, x6]
	WORD $0x3ce669e2 // ldr	q2, [x15, x6]
	WORD $0x6e22dc21 // fmul.4s	v1, v1, v2
	WORD $0x5e1c0422 // mov	s2, v1[3]
	WORD $0x5e140423 // mov	s3, v1[2]
	WORD $0x5e0c0424 // mov	s4, v1[1]
	WORD $0x1e212800 // fadd	s0, s0, s1
	WORD $0x1e242800 // fadd	s0, s0, s4
	WORD $0x1e232800 // fadd	s0, s0, s3
	WORD $0x1e222800 // fadd	s0, s0, s2
	WORD $0x910040c6 // add	x6, x6, #16
	WORD $0xf100116b // subs	x11, x11, #4
	BNE  BB0_59
	WORD $0xaa0d03eb // mov	x11, x13
	WORD $0xb4fff640 // cbz	x0, LBB0_49

BB0_61:
	WORD $0x9b0b1582 // madd	x2, x12, x11, x5

BB0_62:
	WORD $0xbc6b7901 // ldr	s1, [x8, x11, lsl #2]
	WORD $0xbd400042 // ldr	s2, [x2]
	WORD $0x1f020020 // fmadd	s0, s1, s2, s0
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x8b0c0042 // add	x2, x2, x12
	WORD $0xeb04017f // cmp	x11, x4
	BLT  BB0_62
	B    BB0_49

TEXT ·blocked_matmul_neon_f64(SB), $304-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xa90e0bf9   // stp	x25, x2, [sp, #224]             ; 16-byte Folded Spill
	WORD $0xa90f5ff8   // stp	x24, x23, [sp, #240]            ; 16-byte Folded Spill
	WORD $0xa91057f6   // stp	x22, x21, [sp, #256]            ; 16-byte Folded Spill
	WORD $0xa9114ff4   // stp	x20, x19, [sp, #272]            ; 16-byte Folded Spill
	WORD $0xa9127bfd   // stp	x29, x30, [sp, #288]            ; 16-byte Folded Spill
	WORD $0xf9001fe1   // str	x1, [sp, #56]                   ; 8-byte Folded Spill
	WORD $0xf9005fe0   // str	x0, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf940006d   // ldr	x13, [x3]
	WORD $0xf940008e   // ldr	x14, [x4]
	WORD $0xf94000b1   // ldr	x17, [x5]
	WORD $0x9b0d7dc8   // mul	x8, x14, x13
	WORD $0xf100051f   // cmp	x8, #1
	BLT  BB1_8
	WORD $0xf100211f   // cmp	x8, #8
	BHS  BB1_3
	WORD $0xd2800009   // mov	x9, #0                          ; =0x0
	B    BB1_6

BB1_3:
	WORD $0x927ded09 // and	x9, x8, #0x7ffffffffffffff8
	WORD $0xf94077ea // ldr	x10, [sp, #232]                 ; 8-byte Folded Reload
	WORD $0x9100814a // add	x10, x10, #32
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0903eb // mov	x11, x9

BB1_4:
	WORD $0xad3f0140 // stp	q0, q0, [x10, #-32]
	WORD $0xac820140 // stp	q0, q0, [x10], #64
	WORD $0xf100216b // subs	x11, x11, #8
	BNE  BB1_4
	WORD $0xeb09011f // cmp	x8, x9
	BEQ  BB1_8

BB1_6:
	WORD $0xcb090108 // sub	x8, x8, x9
	WORD $0xf94077ea // ldr	x10, [sp, #232]                 ; 8-byte Folded Reload
	WORD $0x8b090d49 // add	x9, x10, x9, lsl #3

BB1_7:
	WORD $0xf800853f // str	xzr, [x9], #8
	WORD $0xf1000508 // subs	x8, x8, #1
	BNE  BB1_7

BB1_8:
	WORD $0xf10005bf // cmp	x13, #1
	WORD $0xfa41a9c8 // ccmp	x14, #1, #8, ge
	WORD $0xfa41aa28 // ccmp	x17, #1, #8, ge
	BGE  BB1_10

BB1_9:
	WORD $0xa9527bfd // ldp	x29, x30, [sp, #288]            ; 16-byte Folded Reload
	WORD $0xa9514ff4 // ldp	x20, x19, [sp, #272]            ; 16-byte Folded Reload
	WORD $0xa95057f6 // ldp	x22, x21, [sp, #256]            ; 16-byte Folded Reload
	WORD $0xa94f5ff8 // ldp	x24, x23, [sp, #240]            ; 16-byte Folded Reload
	WORD $0xf94073f9 // ldr	x25, [sp, #224]                 ; 8-byte Folded Reload
	RET

BB1_10:
	WORD $0xd2800001 // mov	x1, #0                          ; =0x0
	WORD $0x8b0e05c8 // add	x8, x14, x14, lsl #1
	WORD $0xd379e108 // lsl	x8, x8, #7
	WORD $0xf90037e8 // str	x8, [sp, #104]                  ; 8-byte Folded Spill
	WORD $0xd37df1cc // lsl	x12, x14, #3
	WORD $0x8b110628 // add	x8, x17, x17, lsl #1
	WORD $0xf9405fe9 // ldr	x9, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0x91008129 // add	x9, x9, #32
	WORD $0xf90027e9 // str	x9, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf9401fe9 // ldr	x9, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0x9100c12b // add	x11, x9, #48
	WORD $0x9100412a // add	x10, x9, #16
	WORD $0xa9022fea // stp	x10, x11, [sp, #32]             ; 16-byte Folded Spill
	WORD $0xd379e10a // lsl	x10, x8, #7
	WORD $0x91008128 // add	x8, x9, #32
	WORD $0xa9012be8 // stp	x8, x10, [sp, #16]              ; 16-byte Folded Spill
	WORD $0xd37df225 // lsl	x5, x17, #3
	WORD $0xf90057f1 // str	x17, [sp, #168]                 ; 8-byte Folded Spill
	WORD $0xf9001bed // str	x13, [sp, #48]                  ; 8-byte Folded Spill
	WORD $0xf9006fee // str	x14, [sp, #216]                 ; 8-byte Folded Spill
	B    BB1_12

BB1_11:
	WORD $0xf9405fe8 // ldr	x8, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf9400fe9 // ldr	x9, [sp, #24]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf9005fe8 // str	x8, [sp, #184]                  ; 8-byte Folded Spill
	WORD $0xf94027e8 // ldr	x8, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x8b090108 // add	x8, x8, x9
	WORD $0xf90027e8 // str	x8, [sp, #72]                   ; 8-byte Folded Spill
	WORD $0xf94023e8 // ldr	x8, [sp, #64]                   ; 8-byte Folded Reload
	WORD $0xaa0803e1 // mov	x1, x8
	WORD $0xf9401bed // ldr	x13, [sp, #48]                  ; 8-byte Folded Reload
	WORD $0xeb0d011f // cmp	x8, x13
	BGE  BB1_9

BB1_12:
	WORD $0xd2800014 // mov	x20, #0                         ; =0x0
	WORD $0x9100c028 // add	x8, x1, #48
	WORD $0xeb0d011f // cmp	x8, x13
	WORD $0xf90023e8 // str	x8, [sp, #64]                   ; 8-byte Folded Spill
	WORD $0x9a8db107 // csel	x7, x8, x13, lt
	WORD $0xf9400be8 // ldr	x8, [sp, #16]                   ; 8-byte Folded Reload
	WORD $0xa94257ea // ldp	x10, x21, [sp, #32]             ; 16-byte Folded Reload
	WORD $0xf9401fe9 // ldr	x9, [sp, #56]                   ; 8-byte Folded Reload
	WORD $0xa90ca7ea // stp	x10, x9, [sp, #200]             ; 16-byte Folded Spill
	WORD $0xf9005be1 // str	x1, [sp, #176]                  ; 8-byte Folded Spill
	B    BB1_14

BB1_13:
	WORD $0xa94d3be8 // ldp	x8, x14, [sp, #208]             ; 16-byte Folded Reload
	WORD $0x91060109 // add	x9, x8, #384
	WORD $0xf9402ff5 // ldr	x21, [sp, #88]                  ; 8-byte Folded Reload
	WORD $0x910602b5 // add	x21, x21, #384
	WORD $0xf94067e8 // ldr	x8, [sp, #200]                  ; 8-byte Folded Reload
	WORD $0x91060108 // add	x8, x8, #384
	WORD $0xa90ca7e8 // stp	x8, x9, [sp, #200]              ; 16-byte Folded Spill
	WORD $0xf94033e8 // ldr	x8, [sp, #96]                   ; 8-byte Folded Reload
	WORD $0x91060108 // add	x8, x8, #384
	WORD $0xf9402be9 // ldr	x9, [sp, #80]                   ; 8-byte Folded Reload
	WORD $0xaa0903f4 // mov	x20, x9
	WORD $0xeb0e013f // cmp	x9, x14
	BGE  BB1_11

BB1_14:
	WORD $0x9100c289 // add	x9, x20, #48
	WORD $0xeb0e013f // cmp	x9, x14
	WORD $0xa90557e9 // stp	x9, x21, [sp, #80]              ; 16-byte Folded Spill
	WORD $0x9a8eb139 // csel	x25, x9, x14, lt
	WORD $0xb27f0289 // orr	x9, x20, #0x2
	WORD $0xf90063e9 // str	x9, [sp, #192]                  ; 8-byte Folded Spill
	WORD $0xeb19013f // cmp	x9, x25
	WORD $0xf90033e8 // str	x8, [sp, #96]                   ; 8-byte Folded Spill
	BLE  BB1_28
	WORD $0xd280000b // mov	x11, #0                         ; =0x0
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xd2800010 // mov	x16, #0                         ; =0x0
	WORD $0xf94027e0 // ldr	x0, [sp, #72]                   ; 8-byte Folded Reload
	WORD $0x5280002e // mov	w14, #1                         ; =0x1
	WORD $0x5280060f // mov	w15, #48                        ; =0x30
	B    BB1_17

BB1_16:
	WORD $0xa949b7e0 // ldp	x0, x13, [sp, #152]             ; 16-byte Folded Reload
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0x9100c1ef // add	x15, x15, #48
	WORD $0x9100c1ce // add	x14, x14, #48
	WORD $0xf94063eb // ldr	x11, [sp, #192]                 ; 8-byte Folded Reload
	WORD $0xd100c16b // sub	x11, x11, #48
	WORD $0x91060000 // add	x0, x0, #384
	WORD $0x91060108 // add	x8, x8, #384
	WORD $0xf9404be9 // ldr	x9, [sp, #144]                  ; 8-byte Folded Reload
	WORD $0xaa0903f0 // mov	x16, x9
	WORD $0xa94a87f1 // ldp	x17, x1, [sp, #168]             ; 16-byte Folded Reload
	WORD $0xeb11013f // cmp	x9, x17
	BGE  BB1_13

BB1_17:
	WORD $0xeb0f023f // cmp	x17, x15
	WORD $0x9a8fb229 // csel	x9, x17, x15, lt
	WORD $0xeb0e013f // cmp	x9, x14
	WORD $0x9a8ec129 // csel	x9, x9, x14, gt
	WORD $0x9240092a // and	x10, x9, #0x7
	WORD $0xf90063eb // str	x11, [sp, #192]                 ; 8-byte Folded Spill
	WORD $0x8b0b0129 // add	x9, x9, x11
	WORD $0xcb0a012a // sub	x10, x9, x10
	WORD $0x9100c209 // add	x9, x16, #48
	WORD $0xeb09023f // cmp	x17, x9
	WORD $0xa90903e9 // stp	x9, x0, [sp, #144]              ; 16-byte Folded Spill
	WORD $0x9a89b224 // csel	x4, x17, x9, lt
	WORD $0xb2400209 // orr	x9, x16, #0x1
	WORD $0xeb09009f // cmp	x4, x9
	WORD $0x9a90c489 // csinc	x9, x4, x16, gt
	WORD $0x928005eb // mov	x11, #-48                       ; =0xffffffffffffffd0
	WORD $0xf90053ed // str	x13, [sp, #160]                 ; 8-byte Folded Spill
	WORD $0x9b0b25ab // madd	x11, x13, x11, x9
	WORD $0xf1001d7f // cmp	x11, #7
	WORD $0xf9406fe2 // ldr	x2, [sp, #216]                  ; 8-byte Folded Reload
	WORD $0xfa418840 // ccmp	x2, #1, #0, hi
	WORD $0x1a9f17e6 // cset	w6, eq
	WORD $0x92400933 // and	x19, x9, #0x7
	WORD $0xcb130169 // sub	x9, x11, x19
	WORD $0x8b090215 // add	x21, x16, x9
	WORD $0xf9405ff6 // ldr	x22, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0xaa0003ed // mov	x13, x0
	WORD $0xaa0103f8 // mov	x24, x1
	B    BB1_19

BB1_18:
	WORD $0x91000718 // add	x24, x24, #1
	WORD $0x8b0501ad // add	x13, x13, x5
	WORD $0x8b0502d6 // add	x22, x22, x5
	WORD $0xeb07031f // cmp	x24, x7
	BGE  BB1_16

BB1_19:
	WORD $0x9b027f09 // mul	x9, x24, x2
	WORD $0xf94077eb // ldr	x11, [sp, #232]                 ; 8-byte Folded Reload
	WORD $0x8b090d7e // add	x30, x11, x9, lsl #3
	WORD $0xf9406be3 // ldr	x3, [sp, #208]                  ; 8-byte Folded Reload
	WORD $0xaa0803e0 // mov	x0, x8
	WORD $0xaa1403f1 // mov	x17, x20
	B    BB1_21

BB1_20:
	WORD $0xfc317bc0 // str	d0, [x30, x17, lsl #3]
	WORD $0x91000631 // add	x17, x17, #1
	WORD $0x91002000 // add	x0, x0, #8
	WORD $0x91002063 // add	x3, x3, #8
	WORD $0xeb19023f // cmp	x17, x25
	BGE  BB1_18

BB1_21:
	WORD $0xfc717bc0 // ldr	d0, [x30, x17, lsl #3]
	WORD $0x340003a6 // cbz	w6, LBB1_25
	WORD $0xaa0003eb // mov	x11, x0
	WORD $0xaa0d03f7 // mov	x23, x13
	WORD $0xaa0a03e1 // mov	x1, x10

BB1_23:
	WORD $0xad7f0ae1 // ldp	q1, q2, [x23, #-32]
	WORD $0xacc212e3 // ldp	q3, q4, [x23], #64
	WORD $0xad7f1965 // ldp	q5, q6, [x11, #-32]
	WORD $0xacc24167 // ldp	q7, q16, [x11], #64
	WORD $0x6e65dc21 // fmul.2d	v1, v1, v5
	WORD $0x5e180425 // mov	d5, v1[1]
	WORD $0x6e66dc42 // fmul.2d	v2, v2, v6
	WORD $0x5e180446 // mov	d6, v2[1]
	WORD $0x6e67dc63 // fmul.2d	v3, v3, v7
	WORD $0x5e180467 // mov	d7, v3[1]
	WORD $0x6e70dc84 // fmul.2d	v4, v4, v16
	WORD $0x5e180490 // mov	d16, v4[1]
	WORD $0x1e612800 // fadd	d0, d0, d1
	WORD $0x1e652800 // fadd	d0, d0, d5
	WORD $0x1e622800 // fadd	d0, d0, d2
	WORD $0x1e662800 // fadd	d0, d0, d6
	WORD $0x1e632800 // fadd	d0, d0, d3
	WORD $0x1e672800 // fadd	d0, d0, d7
	WORD $0x1e642800 // fadd	d0, d0, d4
	WORD $0x1e702800 // fadd	d0, d0, d16
	WORD $0xf1002021 // subs	x1, x1, #8
	BNE  BB1_23
	WORD $0xaa1503e9 // mov	x9, x21
	WORD $0xb5000073 // cbnz	x19, LBB1_26
	B    BB1_20

BB1_25:
	WORD $0xaa1003e9 // mov	x9, x16

BB1_26:
	WORD $0x9b090d8b // madd	x11, x12, x9, x3

BB1_27:
	WORD $0xfc697ac1 // ldr	d1, [x22, x9, lsl #3]
	WORD $0xfd400162 // ldr	d2, [x11]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0
	WORD $0x91000529 // add	x9, x9, #1
	WORD $0x8b0c016b // add	x11, x11, x12
	WORD $0xeb04013f // cmp	x9, x4
	BLT  BB1_27
	B    BB1_20

BB1_28:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0xd280000d // mov	x13, #0                         ; =0x0
	WORD $0xd2800018 // mov	x24, #0                         ; =0x0
	WORD $0xf94027ef // ldr	x15, [sp, #72]                  ; 8-byte Folded Reload
	WORD $0x52800029 // mov	w9, #1                          ; =0x1
	WORD $0x52800608 // mov	w8, #48                         ; =0x30
	WORD $0xf9405fe0 // ldr	x0, [sp, #184]                  ; 8-byte Folded Reload
	WORD $0xf9406be2 // ldr	x2, [sp, #208]                  ; 8-byte Folded Reload
	B    BB1_30

BB1_29:
	WORD $0xa949abed // ldp	x13, x10, [sp, #152]            ; 16-byte Folded Reload
	WORD $0x910005ad // add	x13, x13, #1
	WORD $0xa946afe8 // ldp	x8, x11, [sp, #104]             ; 16-byte Folded Reload
	WORD $0x8b080042 // add	x2, x2, x8
	WORD $0xa947a3e0 // ldp	x0, x8, [sp, #120]              ; 16-byte Folded Reload
	WORD $0x91060000 // add	x0, x0, #384
	WORD $0x9100c108 // add	x8, x8, #48
	WORD $0xa948bfe9 // ldp	x9, x15, [sp, #136]             ; 16-byte Folded Reload
	WORD $0x9100c129 // add	x9, x9, #48
	WORD $0xd100c14a // sub	x10, x10, #48
	WORD $0x910601ef // add	x15, x15, #384
	WORD $0x910602b5 // add	x21, x21, #384
	WORD $0xaa0b03f8 // mov	x24, x11
	WORD $0xa94a87f1 // ldp	x17, x1, [sp, #168]             ; 16-byte Folded Reload
	WORD $0xeb11017f // cmp	x11, x17
	BGE  BB1_13

BB1_30:
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0xa90827e8 // stp	x8, x9, [sp, #128]              ; 16-byte Folded Spill
	WORD $0x9a88b228 // csel	x8, x17, x8, lt
	WORD $0xeb09011f // cmp	x8, x9
	WORD $0x9a89c108 // csel	x8, x8, x9, gt
	WORD $0x92400909 // and	x9, x8, #0x7
	WORD $0xa909abed // stp	x13, x10, [sp, #152]            ; 16-byte Folded Spill
	WORD $0x8b0a0108 // add	x8, x8, x10
	WORD $0xcb090109 // sub	x9, x8, x9
	WORD $0x9100c308 // add	x8, x24, #48
	WORD $0xeb08023f // cmp	x17, x8
	WORD $0xa90703e8 // stp	x8, x0, [sp, #112]              ; 16-byte Folded Spill
	WORD $0x9a88b22b // csel	x11, x17, x8, lt
	WORD $0xb2400308 // orr	x8, x24, #0x1
	WORD $0xeb08017f // cmp	x11, x8
	WORD $0x9a98c568 // csinc	x8, x11, x24, gt
	WORD $0x928005ea // mov	x10, #-48                       ; =0xffffffffffffffd0
	WORD $0x9b0a21aa // madd	x10, x13, x10, x8
	WORD $0xf1001d5f // cmp	x10, #7
	WORD $0xf9406fed // ldr	x13, [sp, #216]                 ; 8-byte Folded Reload
	WORD $0xfa4189a0 // ccmp	x13, #1, #0, hi
	WORD $0x1a9f17e4 // cset	w4, eq
	WORD $0x92400906 // and	x6, x8, #0x7
	WORD $0xcb060148 // sub	x8, x10, x6
	WORD $0x8b08030e // add	x14, x24, x8
	WORD $0xf9405fea // ldr	x10, [sp, #184]                 ; 8-byte Folded Reload
	WORD $0xf9004bef // str	x15, [sp, #144]                 ; 8-byte Folded Spill
	WORD $0xaa0f03ed // mov	x13, x15
	B    BB1_32

BB1_31:
	WORD $0x91000421 // add	x1, x1, #1
	WORD $0x8b050000 // add	x0, x0, x5
	WORD $0x8b0501ad // add	x13, x13, x5
	WORD $0x8b05014a // add	x10, x10, x5
	WORD $0xeb07003f // cmp	x1, x7
	BGE  BB1_29

BB1_32:
	WORD $0xf9406fe8 // ldr	x8, [sp, #216]                  ; 8-byte Folded Reload
	WORD $0x9b087c28 // mul	x8, x1, x8
	WORD $0xf94077ef // ldr	x15, [sp, #232]                 ; 8-byte Folded Reload
	WORD $0x8b080df3 // add	x19, x15, x8, lsl #3
	WORD $0xa94c47e3 // ldp	x3, x17, [sp, #192]             ; 16-byte Folded Reload
	WORD $0xaa1503ef // mov	x15, x21
	WORD $0xaa0203f6 // mov	x22, x2
	WORD $0xaa1403f7 // mov	x23, x20

BB1_33:
	WORD $0x8b170e70 // add	x16, x19, x23, lsl #3
	WORD $0xaa0303f7 // mov	x23, x3
	WORD $0xaa0f03fe // mov	x30, x15
	WORD $0xaa1103e8 // mov	x8, x17
	WORD $0x3dc00200 // ldr	q0, [x16]
	WORD $0xaa0003e3 // mov	x3, x0
	WORD $0xaa1603f1 // mov	x17, x22
	WORD $0xaa1803ef // mov	x15, x24

BB1_34:
	WORD $0xfc408461 // ldr	d1, [x3], #8
	WORD $0x3dc00222 // ldr	q2, [x17]
	WORD $0x4fc11040 // fmla.2d	v0, v2, v1[0]
	WORD $0x910005ef // add	x15, x15, #1
	WORD $0x8b0c0231 // add	x17, x17, x12
	WORD $0xeb0b01ff // cmp	x15, x11
	BLT  BB1_34
	WORD $0x91000ae3 // add	x3, x23, #2
	WORD $0x3d800200 // str	q0, [x16]
	WORD $0x910042d6 // add	x22, x22, #16
	WORD $0x910043cf // add	x15, x30, #16
	WORD $0x91004111 // add	x17, x8, #16
	WORD $0xeb19007f // cmp	x3, x25
	BLE  BB1_33
	B    BB1_37

BB1_36:
	WORD $0xfc377a60 // str	d0, [x19, x23, lsl #3]
	WORD $0x910006f7 // add	x23, x23, #1
	WORD $0x910023de // add	x30, x30, #8
	WORD $0x91002108 // add	x8, x8, #8

BB1_37:
	WORD $0xeb1902ff // cmp	x23, x25
	BGE  BB1_31
	WORD $0xfc777a60 // ldr	d0, [x19, x23, lsl #3]
	WORD $0x340003a4 // cbz	w4, LBB1_42
	WORD $0xaa1e03f1 // mov	x17, x30
	WORD $0xaa0d03e3 // mov	x3, x13
	WORD $0xaa0903f0 // mov	x16, x9

BB1_40:
	WORD $0xad7f0861 // ldp	q1, q2, [x3, #-32]
	WORD $0xacc21063 // ldp	q3, q4, [x3], #64
	WORD $0xad7f1a25 // ldp	q5, q6, [x17, #-32]
	WORD $0xacc24227 // ldp	q7, q16, [x17], #64
	WORD $0x6e65dc21 // fmul.2d	v1, v1, v5
	WORD $0x5e180425 // mov	d5, v1[1]
	WORD $0x6e66dc42 // fmul.2d	v2, v2, v6
	WORD $0x5e180446 // mov	d6, v2[1]
	WORD $0x6e67dc63 // fmul.2d	v3, v3, v7
	WORD $0x5e180467 // mov	d7, v3[1]
	WORD $0x6e70dc84 // fmul.2d	v4, v4, v16
	WORD $0x5e180490 // mov	d16, v4[1]
	WORD $0x1e612800 // fadd	d0, d0, d1
	WORD $0x1e652800 // fadd	d0, d0, d5
	WORD $0x1e622800 // fadd	d0, d0, d2
	WORD $0x1e662800 // fadd	d0, d0, d6
	WORD $0x1e632800 // fadd	d0, d0, d3
	WORD $0x1e672800 // fadd	d0, d0, d7
	WORD $0x1e642800 // fadd	d0, d0, d4
	WORD $0x1e702800 // fadd	d0, d0, d16
	WORD $0xf1002210 // subs	x16, x16, #8
	BNE  BB1_40
	WORD $0xaa0e03f0 // mov	x16, x14
	WORD $0xb5000066 // cbnz	x6, LBB1_43
	B    BB1_36

BB1_42:
	WORD $0xaa1803f0 // mov	x16, x24

BB1_43:
	WORD $0x9b10218f // madd	x15, x12, x16, x8

BB1_44:
	WORD $0xfc707941 // ldr	d1, [x10, x16, lsl #3]
	WORD $0xfd4001e2 // ldr	d2, [x15]
	WORD $0x1f420020 // fmadd	d0, d1, d2, d0
	WORD $0x91000610 // add	x16, x16, #1
	WORD $0x8b0c01ef // add	x15, x15, x12
	WORD $0xeb0b021f // cmp	x16, x11
	BLT  BB1_44
	B    BB1_36
