// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package grad

import (
	"simd/archsimd"
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
)

func BaseLayerNormBackward_avx2_Float16(gradOutput []hwy.Float16, savedXHat []hwy.Float16, savedInvStd []hwy.Float16, gamma []hwy.Float16, normSize int, gradInput []hwy.Float16, gradGamma []hwy.Float16, gradBeta []hwy.Float16) {
	size := min(len(gradOutput), min(len(savedXHat), len(gradInput)))
	if size == 0 || normSize <= 0 {
		return
	}
	numGroups := size / normSize
	invN := float32(1.0) / float32(normSize)
	lanes := 8
	for g := range numGroups {
		off := g * normSize
		invStd := savedInvStd[g]
		sumDG := asm.ZeroFloat16x8AVX2()
		sumDGXH := asm.ZeroFloat16x8AVX2()
		vInvN := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(invN)))
		ii := 0
		if gamma != nil {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gam := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gamma[ii:][0]))
				dyGamma := gOut.Mul(gam)
				sumDG = sumDG.Add(dyGamma)
				sumDGXH = dyGamma.MulAdd(xHat, sumDGXH)
				if gradGamma != nil {
					gg := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradGamma[ii:][0]))
					gg = gOut.MulAdd(xHat, gg)
					gg.StorePtr(unsafe.Pointer(&gradGamma[ii:][0]))
				}
				if gradBeta != nil {
					gb := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradBeta[ii:][0]))
					gb = gb.Add(gOut)
					gb.StorePtr(unsafe.Pointer(&gradBeta[ii:][0]))
				}
			}
			meanDGScalar := sumDG.ReduceSum()
			meanDGXHScalar := sumDGXH.ReduceSum()
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i].Float32() * gamma[i].Float32()
				meanDGScalar += dyGamma
				meanDGXHScalar += dyGamma * savedXHat[off+i].Float32()
				if gradGamma != nil {
					gradGamma[i] = hwy.Float32ToFloat16(gradGamma[i].Float32() + gradOutput[off+i].Float32()*savedXHat[off+i].Float32())
				}
				if gradBeta != nil {
					gradBeta[i] = hwy.Float32ToFloat16(gradBeta[i].Float32() + gradOutput[off+i].Float32())
				}
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(meanDG)))
			vMeanDGXH := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(meanDGXH)))
			vInvStd := asm.BroadcastFloat16x8AVX2(uint16(invStd))
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gIn := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradInput[off+ii:][0]))
				gam := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gamma[ii:][0]))
				dyGamma := gOut.Mul(gam)
				term := dyGamma.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.StorePtr(unsafe.Pointer(&gradInput[off+ii:][0]))
			}
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i].Float32() * gamma[i].Float32()
				term := dyGamma - meanDG - savedXHat[off+i].Float32()*meanDGXH
				gradInput[off+i] = hwy.Float32ToFloat16(gradInput[off+i].Float32() + invStd.Float32()*term)
			}
		} else {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				sumDG = sumDG.Add(gOut)
				sumDGXH = gOut.MulAdd(xHat, sumDGXH)
			}
			meanDGScalar := sumDG.ReduceSum()
			meanDGXHScalar := sumDGXH.ReduceSum()
			for i := ii; i < normSize; i++ {
				meanDGScalar += gradOutput[off+i].Float32()
				meanDGXHScalar += gradOutput[off+i].Float32() * savedXHat[off+i].Float32()
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(meanDG)))
			vMeanDGXH := asm.BroadcastFloat16x8AVX2(uint16(hwy.Float32ToFloat16(meanDGXH)))
			vInvStd := asm.BroadcastFloat16x8AVX2(uint16(invStd))
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gIn := asm.LoadFloat16x8AVX2Ptr(unsafe.Pointer(&gradInput[off+ii:][0]))
				term := gOut.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.StorePtr(unsafe.Pointer(&gradInput[off+ii:][0]))
			}
			for i := ii; i < normSize; i++ {
				term := gradOutput[off+i].Float32() - meanDG - savedXHat[off+i].Float32()*meanDGXH
				gradInput[off+i] = hwy.Float32ToFloat16(gradInput[off+i].Float32() + invStd.Float32()*term)
			}
		}
		_ = vInvN
	}
}

func BaseLayerNormBackward_avx2_BFloat16(gradOutput []hwy.BFloat16, savedXHat []hwy.BFloat16, savedInvStd []hwy.BFloat16, gamma []hwy.BFloat16, normSize int, gradInput []hwy.BFloat16, gradGamma []hwy.BFloat16, gradBeta []hwy.BFloat16) {
	size := min(len(gradOutput), min(len(savedXHat), len(gradInput)))
	if size == 0 || normSize <= 0 {
		return
	}
	numGroups := size / normSize
	invN := float32(1.0) / float32(normSize)
	lanes := 8
	for g := range numGroups {
		off := g * normSize
		invStd := savedInvStd[g]
		sumDG := asm.ZeroBFloat16x8AVX2()
		sumDGXH := asm.ZeroBFloat16x8AVX2()
		vInvN := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(invN)))
		ii := 0
		if gamma != nil {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gam := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gamma[ii:][0]))
				dyGamma := gOut.Mul(gam)
				sumDG = sumDG.Add(dyGamma)
				sumDGXH = dyGamma.MulAdd(xHat, sumDGXH)
				if gradGamma != nil {
					gg := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradGamma[ii:][0]))
					gg = gOut.MulAdd(xHat, gg)
					gg.StorePtr(unsafe.Pointer(&gradGamma[ii:][0]))
				}
				if gradBeta != nil {
					gb := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradBeta[ii:][0]))
					gb = gb.Add(gOut)
					gb.StorePtr(unsafe.Pointer(&gradBeta[ii:][0]))
				}
			}
			meanDGScalar := sumDG.ReduceSum()
			meanDGXHScalar := sumDGXH.ReduceSum()
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i].Float32() * gamma[i].Float32()
				meanDGScalar += dyGamma
				meanDGXHScalar += dyGamma * savedXHat[off+i].Float32()
				if gradGamma != nil {
					gradGamma[i] = hwy.Float32ToBFloat16(gradGamma[i].Float32() + gradOutput[off+i].Float32()*savedXHat[off+i].Float32())
				}
				if gradBeta != nil {
					gradBeta[i] = hwy.Float32ToBFloat16(gradBeta[i].Float32() + gradOutput[off+i].Float32())
				}
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(meanDG)))
			vMeanDGXH := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(meanDGXH)))
			vInvStd := asm.BroadcastBFloat16x8AVX2(uint16(invStd))
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gIn := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradInput[off+ii:][0]))
				gam := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gamma[ii:][0]))
				dyGamma := gOut.Mul(gam)
				term := dyGamma.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.StorePtr(unsafe.Pointer(&gradInput[off+ii:][0]))
			}
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i].Float32() * gamma[i].Float32()
				term := dyGamma - meanDG - savedXHat[off+i].Float32()*meanDGXH
				gradInput[off+i] = hwy.Float32ToBFloat16(gradInput[off+i].Float32() + invStd.Float32()*term)
			}
		} else {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				sumDG = sumDG.Add(gOut)
				sumDGXH = gOut.MulAdd(xHat, sumDGXH)
			}
			meanDGScalar := sumDG.ReduceSum()
			meanDGXHScalar := sumDGXH.ReduceSum()
			for i := ii; i < normSize; i++ {
				meanDGScalar += gradOutput[off+i].Float32()
				meanDGXHScalar += gradOutput[off+i].Float32() * savedXHat[off+i].Float32()
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(meanDG)))
			vMeanDGXH := asm.BroadcastBFloat16x8AVX2(uint16(hwy.Float32ToBFloat16(meanDGXH)))
			vInvStd := asm.BroadcastBFloat16x8AVX2(uint16(invStd))
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradOutput[off+ii:][0]))
				xHat := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&savedXHat[off+ii:][0]))
				gIn := asm.LoadBFloat16x8AVX2Ptr(unsafe.Pointer(&gradInput[off+ii:][0]))
				term := gOut.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.StorePtr(unsafe.Pointer(&gradInput[off+ii:][0]))
			}
			for i := ii; i < normSize; i++ {
				term := gradOutput[off+i].Float32() - meanDG - savedXHat[off+i].Float32()*meanDGXH
				gradInput[off+i] = hwy.Float32ToBFloat16(gradInput[off+i].Float32() + invStd.Float32()*term)
			}
		}
		_ = vInvN
	}
}

func BaseLayerNormBackward_avx2(gradOutput []float32, savedXHat []float32, savedInvStd []float32, gamma []float32, normSize int, gradInput []float32, gradGamma []float32, gradBeta []float32) {
	size := min(len(gradOutput), min(len(savedXHat), len(gradInput)))
	if size == 0 || normSize <= 0 {
		return
	}
	numGroups := size / normSize
	invN := float32(1.0) / float32(normSize)
	lanes := 8
	for g := range numGroups {
		off := g * normSize
		invStd := savedInvStd[g]
		sumDG := archsimd.BroadcastFloat32x8(0)
		sumDGXH := archsimd.BroadcastFloat32x8(0)
		vInvN := archsimd.BroadcastFloat32x8(invN)
		ii := 0
		if gamma != nil {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&savedXHat[off+ii])))
				gam := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gamma[ii])))
				dyGamma := gOut.Mul(gam)
				sumDG = sumDG.Add(dyGamma)
				sumDGXH = dyGamma.MulAdd(xHat, sumDGXH)
				if gradGamma != nil {
					gg := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradGamma[ii])))
					gg = gOut.MulAdd(xHat, gg)
					gg.Store((*[8]float32)(unsafe.Pointer(&gradGamma[ii])))
				}
				if gradBeta != nil {
					gb := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradBeta[ii])))
					gb = gb.Add(gOut)
					gb.Store((*[8]float32)(unsafe.Pointer(&gradBeta[ii])))
				}
			}
			meanDGScalar := hwy.ReduceSum_AVX2_F32x8(sumDG)
			meanDGXHScalar := hwy.ReduceSum_AVX2_F32x8(sumDGXH)
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i] * gamma[i]
				meanDGScalar += dyGamma
				meanDGXHScalar += dyGamma * savedXHat[off+i]
				if gradGamma != nil {
					gradGamma[i] += gradOutput[off+i] * savedXHat[off+i]
				}
				if gradBeta != nil {
					gradBeta[i] += gradOutput[off+i]
				}
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := archsimd.BroadcastFloat32x8(meanDG)
			vMeanDGXH := archsimd.BroadcastFloat32x8(meanDGXH)
			vInvStd := archsimd.BroadcastFloat32x8(invStd)
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&savedXHat[off+ii])))
				gIn := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradInput[off+ii])))
				gam := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gamma[ii])))
				dyGamma := gOut.Mul(gam)
				term := dyGamma.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.Store((*[8]float32)(unsafe.Pointer(&gradInput[off+ii])))
			}
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i] * gamma[i]
				term := dyGamma - meanDG - savedXHat[off+i]*meanDGXH
				gradInput[off+i] += invStd * term
			}
		} else {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&savedXHat[off+ii])))
				sumDG = sumDG.Add(gOut)
				sumDGXH = gOut.MulAdd(xHat, sumDGXH)
			}
			meanDGScalar := hwy.ReduceSum_AVX2_F32x8(sumDG)
			meanDGXHScalar := hwy.ReduceSum_AVX2_F32x8(sumDGXH)
			for i := ii; i < normSize; i++ {
				meanDGScalar += gradOutput[off+i]
				meanDGXHScalar += gradOutput[off+i] * savedXHat[off+i]
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := archsimd.BroadcastFloat32x8(meanDG)
			vMeanDGXH := archsimd.BroadcastFloat32x8(meanDGXH)
			vInvStd := archsimd.BroadcastFloat32x8(invStd)
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&savedXHat[off+ii])))
				gIn := archsimd.LoadFloat32x8((*[8]float32)(unsafe.Pointer(&gradInput[off+ii])))
				term := gOut.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.Store((*[8]float32)(unsafe.Pointer(&gradInput[off+ii])))
			}
			for i := ii; i < normSize; i++ {
				term := gradOutput[off+i] - meanDG - savedXHat[off+i]*meanDGXH
				gradInput[off+i] += invStd * term
			}
		}
		_ = vInvN
	}
}

func BaseLayerNormBackward_avx2_Float64(gradOutput []float64, savedXHat []float64, savedInvStd []float64, gamma []float64, normSize int, gradInput []float64, gradGamma []float64, gradBeta []float64) {
	size := min(len(gradOutput), min(len(savedXHat), len(gradInput)))
	if size == 0 || normSize <= 0 {
		return
	}
	numGroups := size / normSize
	invN := float64(1.0) / float64(normSize)
	lanes := 4
	for g := range numGroups {
		off := g * normSize
		invStd := savedInvStd[g]
		sumDG := archsimd.BroadcastFloat64x4(0)
		sumDGXH := archsimd.BroadcastFloat64x4(0)
		vInvN := archsimd.BroadcastFloat64x4(invN)
		ii := 0
		if gamma != nil {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&savedXHat[off+ii])))
				gam := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gamma[ii])))
				dyGamma := gOut.Mul(gam)
				sumDG = sumDG.Add(dyGamma)
				sumDGXH = dyGamma.MulAdd(xHat, sumDGXH)
				if gradGamma != nil {
					gg := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradGamma[ii])))
					gg = gOut.MulAdd(xHat, gg)
					gg.Store((*[4]float64)(unsafe.Pointer(&gradGamma[ii])))
				}
				if gradBeta != nil {
					gb := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradBeta[ii])))
					gb = gb.Add(gOut)
					gb.Store((*[4]float64)(unsafe.Pointer(&gradBeta[ii])))
				}
			}
			meanDGScalar := hwy.ReduceSum_AVX2_F64x4(sumDG)
			meanDGXHScalar := hwy.ReduceSum_AVX2_F64x4(sumDGXH)
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i] * gamma[i]
				meanDGScalar += dyGamma
				meanDGXHScalar += dyGamma * savedXHat[off+i]
				if gradGamma != nil {
					gradGamma[i] += gradOutput[off+i] * savedXHat[off+i]
				}
				if gradBeta != nil {
					gradBeta[i] += gradOutput[off+i]
				}
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := archsimd.BroadcastFloat64x4(meanDG)
			vMeanDGXH := archsimd.BroadcastFloat64x4(meanDGXH)
			vInvStd := archsimd.BroadcastFloat64x4(invStd)
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&savedXHat[off+ii])))
				gIn := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradInput[off+ii])))
				gam := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gamma[ii])))
				dyGamma := gOut.Mul(gam)
				term := dyGamma.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.Store((*[4]float64)(unsafe.Pointer(&gradInput[off+ii])))
			}
			for i := ii; i < normSize; i++ {
				dyGamma := gradOutput[off+i] * gamma[i]
				term := dyGamma - meanDG - savedXHat[off+i]*meanDGXH
				gradInput[off+i] += invStd * term
			}
		} else {
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&savedXHat[off+ii])))
				sumDG = sumDG.Add(gOut)
				sumDGXH = gOut.MulAdd(xHat, sumDGXH)
			}
			meanDGScalar := hwy.ReduceSum_AVX2_F64x4(sumDG)
			meanDGXHScalar := hwy.ReduceSum_AVX2_F64x4(sumDGXH)
			for i := ii; i < normSize; i++ {
				meanDGScalar += gradOutput[off+i]
				meanDGXHScalar += gradOutput[off+i] * savedXHat[off+i]
			}
			meanDG := meanDGScalar * invN
			meanDGXH := meanDGXHScalar * invN
			vMeanDG := archsimd.BroadcastFloat64x4(meanDG)
			vMeanDGXH := archsimd.BroadcastFloat64x4(meanDGXH)
			vInvStd := archsimd.BroadcastFloat64x4(invStd)
			ii = 0
			for ; ii+lanes <= normSize; ii += lanes {
				gOut := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradOutput[off+ii])))
				xHat := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&savedXHat[off+ii])))
				gIn := archsimd.LoadFloat64x4((*[4]float64)(unsafe.Pointer(&gradInput[off+ii])))
				term := gOut.Sub(vMeanDG)
				xhMdgxh := xHat.Mul(vMeanDGXH)
				term = term.Sub(xhMdgxh)
				contrib := vInvStd.Mul(term)
				result := gIn.Add(contrib)
				result.Store((*[4]float64)(unsafe.Pointer(&gradInput[off+ii])))
			}
			for i := ii; i < normSize; i++ {
				term := gradOutput[off+i] - meanDG - savedXHat[off+i]*meanDGXH
				gradInput[off+i] += invStd * term
			}
		}
		_ = vInvN
	}
}
