// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build amd64 && goexperiment.simd

package grad

import (
	stdmath "math"
	"simd/archsimd"
	"sync"
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
	"github.com/ajroetker/go-highway/hwy/contrib/math"
)

// Hoisted constants - lazily initialized on first use to avoid init-time crashes
var (
	BaseSiLUBackward_AVX512_vOne_f32 archsimd.Float32x16
	BaseSiLUBackward_AVX512_vOne_f64 archsimd.Float64x8
	_siluBackwardBaseHoistOnce       sync.Once
)

func _siluBackwardBaseInitHoistedConstants() {
	_siluBackwardBaseHoistOnce.Do(func() {
		BaseSiLUBackward_AVX512_vOne_f32 = archsimd.BroadcastFloat32x16(1.0)
		BaseSiLUBackward_AVX512_vOne_f64 = archsimd.BroadcastFloat64x8(1.0)
	})
}

func BaseSiLUBackward_avx512_Float16(gradOutput []hwy.Float16, savedInput []hwy.Float16, gradInput []hwy.Float16) {
	_siluBackwardBaseInitHoistedConstants()
	n := min(len(gradOutput), min(len(savedInput), len(gradInput)))
	if n == 0 {
		return
	}
	vOne := asm.BroadcastFloat16x16AVX512(uint16(hwy.Float32ToFloat16(float32(1.0))))
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= n; ii += lanes * 2 {
		gOut := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii:][0]))
		x := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii:][0]))
		gIn := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii:][0]))
		sigX := math.BaseSigmoidVec_avx512_Float16(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.StorePtr(unsafe.Pointer(&gradInput[ii:][0]))
		gOut1 := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii+16:][0]))
		x1 := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii+16:][0]))
		gIn1 := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii+16:][0]))
		sigX1 := math.BaseSigmoidVec_avx512_Float16(x1)
		oneMinusSig1 := vOne.Sub(sigX1)
		xTimesTerm1 := x1.Mul(oneMinusSig1)
		innerTerm1 := vOne.Add(xTimesTerm1)
		dSilu1 := sigX1.Mul(innerTerm1)
		result1 := gOut1.MulAdd(dSilu1, gIn1)
		result1.StorePtr(unsafe.Pointer(&gradInput[ii+16:][0]))
	}
	for ; ii+lanes <= n; ii += lanes {
		gOut := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii:][0]))
		x := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii:][0]))
		gIn := asm.LoadFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii:][0]))
		sigX := math.BaseSigmoidVec_avx512_Float16(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.StorePtr(unsafe.Pointer(&gradInput[ii:][0]))
	}
	for i := ii; i < n; i++ {
		x := float64(savedInput[i].Float32())
		sig := 1.0 / (1.0 + stdmath.Exp(-x))
		dSilu := sig * (1.0 + x*(1.0-sig))
		gradInput[i] = hwy.Float32ToFloat16(gradInput[i].Float32() + gradOutput[i].Float32()*float32(dSilu))
	}
}

func BaseSiLUBackward_avx512_BFloat16(gradOutput []hwy.BFloat16, savedInput []hwy.BFloat16, gradInput []hwy.BFloat16) {
	_siluBackwardBaseInitHoistedConstants()
	n := min(len(gradOutput), min(len(savedInput), len(gradInput)))
	if n == 0 {
		return
	}
	vOne := asm.BroadcastBFloat16x16AVX512(uint16(hwy.Float32ToBFloat16(float32(1.0))))
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= n; ii += lanes * 2 {
		gOut := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii:][0]))
		x := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii:][0]))
		gIn := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii:][0]))
		sigX := math.BaseSigmoidVec_avx512_BFloat16(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.StorePtr(unsafe.Pointer(&gradInput[ii:][0]))
		gOut1 := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii+16:][0]))
		x1 := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii+16:][0]))
		gIn1 := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii+16:][0]))
		sigX1 := math.BaseSigmoidVec_avx512_BFloat16(x1)
		oneMinusSig1 := vOne.Sub(sigX1)
		xTimesTerm1 := x1.Mul(oneMinusSig1)
		innerTerm1 := vOne.Add(xTimesTerm1)
		dSilu1 := sigX1.Mul(innerTerm1)
		result1 := gOut1.MulAdd(dSilu1, gIn1)
		result1.StorePtr(unsafe.Pointer(&gradInput[ii+16:][0]))
	}
	for ; ii+lanes <= n; ii += lanes {
		gOut := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradOutput[ii:][0]))
		x := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&savedInput[ii:][0]))
		gIn := asm.LoadBFloat16x16AVX512Ptr(unsafe.Pointer(&gradInput[ii:][0]))
		sigX := math.BaseSigmoidVec_avx512_BFloat16(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.StorePtr(unsafe.Pointer(&gradInput[ii:][0]))
	}
	for i := ii; i < n; i++ {
		x := float64(savedInput[i].Float32())
		sig := 1.0 / (1.0 + stdmath.Exp(-x))
		dSilu := sig * (1.0 + x*(1.0-sig))
		gradInput[i] = hwy.Float32ToBFloat16(gradInput[i].Float32() + gradOutput[i].Float32()*float32(dSilu))
	}
}

func BaseSiLUBackward_avx512(gradOutput []float32, savedInput []float32, gradInput []float32) {
	_siluBackwardBaseInitHoistedConstants()
	n := min(len(gradOutput), min(len(savedInput), len(gradInput)))
	if n == 0 {
		return
	}
	vOne := BaseSiLUBackward_AVX512_vOne_f32
	lanes := 16
	ii := 0
	for ; ii+lanes*2 <= n; ii += lanes * 2 {
		gOut := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradOutput[ii])))
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&savedInput[ii])))
		gIn := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradInput[ii])))
		sigX := math.BaseSigmoidVec_avx512(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.Store((*[16]float32)(unsafe.Pointer(&gradInput[ii])))
		gOut1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradOutput[ii+16])))
		x1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&savedInput[ii+16])))
		gIn1 := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradInput[ii+16])))
		sigX1 := math.BaseSigmoidVec_avx512(x1)
		oneMinusSig1 := vOne.Sub(sigX1)
		xTimesTerm1 := x1.Mul(oneMinusSig1)
		innerTerm1 := vOne.Add(xTimesTerm1)
		dSilu1 := sigX1.Mul(innerTerm1)
		result1 := gOut1.MulAdd(dSilu1, gIn1)
		result1.Store((*[16]float32)(unsafe.Pointer(&gradInput[ii+16])))
	}
	for ; ii+lanes <= n; ii += lanes {
		gOut := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradOutput[ii])))
		x := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&savedInput[ii])))
		gIn := archsimd.LoadFloat32x16((*[16]float32)(unsafe.Pointer(&gradInput[ii])))
		sigX := math.BaseSigmoidVec_avx512(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.Store((*[16]float32)(unsafe.Pointer(&gradInput[ii])))
	}
	for i := ii; i < n; i++ {
		x := float64(savedInput[i])
		sig := 1.0 / (1.0 + stdmath.Exp(-x))
		dSilu := sig * (1.0 + x*(1.0-sig))
		gradInput[i] += gradOutput[i] * float32(dSilu)
	}
}

func BaseSiLUBackward_avx512_Float64(gradOutput []float64, savedInput []float64, gradInput []float64) {
	_siluBackwardBaseInitHoistedConstants()
	n := min(len(gradOutput), min(len(savedInput), len(gradInput)))
	if n == 0 {
		return
	}
	vOne := BaseSiLUBackward_AVX512_vOne_f64
	lanes := 8
	ii := 0
	for ; ii+lanes*2 <= n; ii += lanes * 2 {
		gOut := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradOutput[ii])))
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&savedInput[ii])))
		gIn := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradInput[ii])))
		sigX := math.BaseSigmoidVec_avx512_Float64(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.Store((*[8]float64)(unsafe.Pointer(&gradInput[ii])))
		gOut1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradOutput[ii+8])))
		x1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&savedInput[ii+8])))
		gIn1 := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradInput[ii+8])))
		sigX1 := math.BaseSigmoidVec_avx512_Float64(x1)
		oneMinusSig1 := vOne.Sub(sigX1)
		xTimesTerm1 := x1.Mul(oneMinusSig1)
		innerTerm1 := vOne.Add(xTimesTerm1)
		dSilu1 := sigX1.Mul(innerTerm1)
		result1 := gOut1.MulAdd(dSilu1, gIn1)
		result1.Store((*[8]float64)(unsafe.Pointer(&gradInput[ii+8])))
	}
	for ; ii+lanes <= n; ii += lanes {
		gOut := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradOutput[ii])))
		x := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&savedInput[ii])))
		gIn := archsimd.LoadFloat64x8((*[8]float64)(unsafe.Pointer(&gradInput[ii])))
		sigX := math.BaseSigmoidVec_avx512_Float64(x)
		oneMinusSig := vOne.Sub(sigX)
		xTimesTerm := x.Mul(oneMinusSig)
		innerTerm := vOne.Add(xTimesTerm)
		dSilu := sigX.Mul(innerTerm)
		result := gOut.MulAdd(dSilu, gIn)
		result.Store((*[8]float64)(unsafe.Pointer(&gradInput[ii])))
	}
	for i := ii; i < n; i++ {
		x := float64(savedInput[i])
		sig := 1.0 / (1.0 + stdmath.Exp(-x))
		dSilu := sig * (1.0 + x*(1.0-sig))
		gradInput[i] += gradOutput[i] * float64(dSilu)
	}
}
