// Code generated by hwygen. DO NOT EDIT.
//go:build amd64 && goexperiment.simd

package matmul

import (
	"os"
	"simd/archsimd"
)

var FusedInt8MatMul func(input []float32, weights []int8, scales []float32, output []float32, M int, K int, N int, groupSize int)

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initFusedint8matmulFallback()
		return
	}
	if archsimd.X86.AVX512() {
		initFusedint8matmulAVX512()
		return
	}
	if archsimd.X86.AVX2() {
		initFusedint8matmulAVX2()
		return
	}
	initFusedint8matmulFallback()
}

func initFusedint8matmulAVX2() {
	FusedInt8MatMul = BaseFusedInt8MatMul_avx2
}

func initFusedint8matmulAVX512() {
	FusedInt8MatMul = BaseFusedInt8MatMul_avx512
}

func initFusedint8matmulFallback() {
	FusedInt8MatMul = BaseFusedInt8MatMul_fallback
}
