// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

//go:build arm64

package matmul

import (
	"unsafe"

	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/asm"
)

func BaseMatMul_neon_Float16(a []hwy.Float16, b []hwy.Float16, c []hwy.Float16, m int, n int, k int) {
	if len(a) < m*k {
		panic("matmul: A slice too short")
	}
	if len(b) < k*n {
		panic("matmul: B slice too short")
	}
	if len(c) < m*n {
		panic("matmul: C slice too short")
	}
	for i := range m {
		cRow := c[i*n : (i+1)*n]
		vZero := asm.ZeroFloat16x8()
		lanes := 8
		var j int
		for j = 0; j+lanes <= n; j += lanes {
			vZero.StorePtr(unsafe.Pointer(&cRow[j:][0]))
		}
		for ; j < n; j++ {
			cRow[j] = hwy.Float32ToFloat16(0)
		}
		for p := range k {
			aip := a[i*k+p]
			vA := asm.BroadcastFloat16x8(uint16(aip))
			bRow := b[p*n : (p+1)*n]
			for j = 0; j+lanes <= n; j += lanes {
				vB := asm.LoadFloat16x8Ptr(unsafe.Pointer(&bRow[j:][0]))
				vC := asm.LoadFloat16x8Ptr(unsafe.Pointer(&cRow[j:][0]))
				vA.MulAddAcc(vB, &vC)
				vC.StorePtr(unsafe.Pointer(&cRow[j:][0]))
			}
			for ; j < n; j++ {
				cRow[j] = hwy.Float32ToFloat16(cRow[j].Float32() + aip.Float32()*bRow[j].Float32())
			}
		}
	}
}

func BaseMatMul_neon_BFloat16(a []hwy.BFloat16, b []hwy.BFloat16, c []hwy.BFloat16, m int, n int, k int) {
	if len(a) < m*k {
		panic("matmul: A slice too short")
	}
	if len(b) < k*n {
		panic("matmul: B slice too short")
	}
	if len(c) < m*n {
		panic("matmul: C slice too short")
	}
	for i := range m {
		cRow := c[i*n : (i+1)*n]
		vZero := asm.ZeroBFloat16x8()
		lanes := 8
		var j int
		for j = 0; j+lanes <= n; j += lanes {
			vZero.StorePtr(unsafe.Pointer(&cRow[j:][0]))
		}
		for ; j < n; j++ {
			cRow[j] = hwy.Float32ToBFloat16(0)
		}
		for p := range k {
			aip := a[i*k+p]
			vA := asm.BroadcastBFloat16x8(uint16(aip))
			bRow := b[p*n : (p+1)*n]
			for j = 0; j+lanes <= n; j += lanes {
				vB := asm.LoadBFloat16x8Ptr(unsafe.Pointer(&bRow[j:][0]))
				vC := asm.LoadBFloat16x8Ptr(unsafe.Pointer(&cRow[j:][0]))
				vA.MulAddAcc(vB, &vC)
				vC.StorePtr(unsafe.Pointer(&cRow[j:][0]))
			}
			for ; j < n; j++ {
				cRow[j] = hwy.Float32ToBFloat16(cRow[j].Float32() + aip.Float32()*bRow[j].Float32())
			}
		}
	}
}

func BaseMatMul_neon(a []float32, b []float32, c []float32, m int, n int, k int) {
	if len(a) < m*k {
		panic("matmul: A slice too short")
	}
	if len(b) < k*n {
		panic("matmul: B slice too short")
	}
	if len(c) < m*n {
		panic("matmul: C slice too short")
	}
	for i := range m {
		cRow := c[i*n : (i+1)*n]
		vZero := asm.ZeroFloat32x4()
		lanes := 4
		var j int
		for j = 0; j+lanes <= n; j += lanes {
			vZero.StoreSlice(cRow[j:])
		}
		for ; j < n; j++ {
			cRow[j] = 0
		}
		for p := range k {
			aip := a[i*k+p]
			vA := asm.BroadcastFloat32x4(aip)
			bRow := b[p*n : (p+1)*n]
			for j = 0; j+lanes <= n; j += lanes {
				vB := asm.LoadFloat32x4Slice(bRow[j:])
				vC := asm.LoadFloat32x4Slice(cRow[j:])
				vA.MulAddAcc(vB, &vC)
				vC.StoreSlice(cRow[j:])
			}
			for ; j < n; j++ {
				cRow[j] += aip * bRow[j]
			}
		}
	}
}

func BaseMatMul_neon_Float64(a []float64, b []float64, c []float64, m int, n int, k int) {
	if len(a) < m*k {
		panic("matmul: A slice too short")
	}
	if len(b) < k*n {
		panic("matmul: B slice too short")
	}
	if len(c) < m*n {
		panic("matmul: C slice too short")
	}
	for i := range m {
		cRow := c[i*n : (i+1)*n]
		vZero := asm.ZeroFloat64x2()
		lanes := 2
		var j int
		for j = 0; j+lanes <= n; j += lanes {
			vZero.StoreSlice(cRow[j:])
		}
		for ; j < n; j++ {
			cRow[j] = 0
		}
		for p := range k {
			aip := a[i*k+p]
			vA := asm.BroadcastFloat64x2(aip)
			bRow := b[p*n : (p+1)*n]
			for j = 0; j+lanes <= n; j += lanes {
				vB := asm.LoadFloat64x2Slice(bRow[j:])
				vC := asm.LoadFloat64x2Slice(cRow[j:])
				vA.MulAddAcc(vB, &vC)
				vC.StoreSlice(cRow[j:])
			}
			for ; j < n; j++ {
				cRow[j] += aip * bRow[j]
			}
		}
	}
}
