// Code generated by hwygen. DO NOT EDIT.
//go:build arm64

package matmul

import (
	"os"

	"github.com/ajroetker/go-highway/hwy"
)

var PackedMicroKernel4x2Float16 func(packedA []hwy.Float16, packedB []hwy.Float16, output []hwy.Float16, outputStride int, outRowStart int, outColStart int, panelK int, lanes int)
var PackedMicroKernel4x2BFloat16 func(packedA []hwy.BFloat16, packedB []hwy.BFloat16, output []hwy.BFloat16, outputStride int, outRowStart int, outColStart int, panelK int, lanes int)
var PackedMicroKernel4x2Float32 func(packedA []float32, packedB []float32, output []float32, outputStride int, outRowStart int, outColStart int, panelK int, lanes int)
var PackedMicroKernel4x2Float64 func(packedA []float64, packedB []float64, output []float64, outputStride int, outRowStart int, outColStart int, panelK int, lanes int)
var ZeroSliceFloat16 func(s []hwy.Float16, n int)
var ZeroSliceBFloat16 func(s []hwy.BFloat16, n int)
var ZeroSliceFloat32 func(s []float32, n int)
var ZeroSliceFloat64 func(s []float64, n int)

// PackedMicroKernel4x2 is the generic API that dispatches to the appropriate SIMD implementation.
func PackedMicroKernel4x2[T hwy.Floats](packedA []T, packedB []T, output []T, outputStride int, outRowStart int, outColStart int, panelK int, lanes int) {
	switch any(packedA).(type) {
	case []hwy.Float16:
		PackedMicroKernel4x2Float16(any(packedA).([]hwy.Float16), any(packedB).([]hwy.Float16), any(output).([]hwy.Float16), outputStride, outRowStart, outColStart, panelK, lanes)
	case []hwy.BFloat16:
		PackedMicroKernel4x2BFloat16(any(packedA).([]hwy.BFloat16), any(packedB).([]hwy.BFloat16), any(output).([]hwy.BFloat16), outputStride, outRowStart, outColStart, panelK, lanes)
	case []float32:
		PackedMicroKernel4x2Float32(any(packedA).([]float32), any(packedB).([]float32), any(output).([]float32), outputStride, outRowStart, outColStart, panelK, lanes)
	case []float64:
		PackedMicroKernel4x2Float64(any(packedA).([]float64), any(packedB).([]float64), any(output).([]float64), outputStride, outRowStart, outColStart, panelK, lanes)
	}
}

// ZeroSlice is the generic API that dispatches to the appropriate SIMD implementation.
func ZeroSlice[T hwy.Floats](s []T, n int) {
	switch any(s).(type) {
	case []hwy.Float16:
		ZeroSliceFloat16(any(s).([]hwy.Float16), n)
	case []hwy.BFloat16:
		ZeroSliceBFloat16(any(s).([]hwy.BFloat16), n)
	case []float32:
		ZeroSliceFloat32(any(s).([]float32), n)
	case []float64:
		ZeroSliceFloat64(any(s).([]float64), n)
	}
}

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initPackedkernelv2Fallback()
		return
	}
	initPackedkernelv2NEON()
	return
}

func initPackedkernelv2NEON() {
	PackedMicroKernel4x2Float16 = BasePackedMicroKernel4x2_neon_Float16
	PackedMicroKernel4x2BFloat16 = BasePackedMicroKernel4x2_neon_BFloat16
	PackedMicroKernel4x2Float32 = BasePackedMicroKernel4x2_neon
	PackedMicroKernel4x2Float64 = BasePackedMicroKernel4x2_neon_Float64
	ZeroSliceFloat16 = BaseZeroSlice_neon_Float16
	ZeroSliceBFloat16 = BaseZeroSlice_neon_BFloat16
	ZeroSliceFloat32 = BaseZeroSlice_neon
	ZeroSliceFloat64 = BaseZeroSlice_neon_Float64
}

func initPackedkernelv2Fallback() {
	PackedMicroKernel4x2Float16 = BasePackedMicroKernel4x2_fallback_Float16
	PackedMicroKernel4x2BFloat16 = BasePackedMicroKernel4x2_fallback_BFloat16
	PackedMicroKernel4x2Float32 = BasePackedMicroKernel4x2_fallback
	PackedMicroKernel4x2Float64 = BasePackedMicroKernel4x2_fallback_Float64
	ZeroSliceFloat16 = BaseZeroSlice_fallback_Float16
	ZeroSliceBFloat16 = BaseZeroSlice_fallback_BFloat16
	ZeroSliceFloat32 = BaseZeroSlice_fallback
	ZeroSliceFloat64 = BaseZeroSlice_fallback_Float64
}
