// Code generated by github.com/ajroetker/go-highway/cmd/hwygen. DO NOT EDIT.

package matmul

import (
	"github.com/ajroetker/go-highway/hwy"
)

func BasePackLHS_fallback_Float16(a []hwy.Float16, packed []hwy.Float16, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	numMicroPanels := (panelRows + mr - 1) / mr
	activeRowsLast := panelRows - (numMicroPanels-1)*mr
	fullPanels := numMicroPanels
	if activeRowsLast < mr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseRow := rowStart + panel*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < mr; r++ {
				packed[packIdx] = hwy.Float32ToFloat16(a[(baseRow+r)*k+colStart+kk].Float32())
				packIdx++
			}
		}
	}
	if activeRowsLast < mr && activeRowsLast > 0 {
		baseRow := rowStart + fullPanels*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < activeRowsLast; r++ {
				packed[packIdx] = hwy.Float32ToFloat16(a[(baseRow+r)*k+colStart+kk].Float32())
				packIdx++
			}
			for r := activeRowsLast; r < mr; r++ {
				packed[packIdx] = hwy.Float32ToFloat16(0)
				packIdx++
			}
		}
	}
	return activeRowsLast
}

func BasePackLHS_fallback_BFloat16(a []hwy.BFloat16, packed []hwy.BFloat16, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	numMicroPanels := (panelRows + mr - 1) / mr
	activeRowsLast := panelRows - (numMicroPanels-1)*mr
	fullPanels := numMicroPanels
	if activeRowsLast < mr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseRow := rowStart + panel*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < mr; r++ {
				packed[packIdx] = hwy.Float32ToBFloat16(a[(baseRow+r)*k+colStart+kk].Float32())
				packIdx++
			}
		}
	}
	if activeRowsLast < mr && activeRowsLast > 0 {
		baseRow := rowStart + fullPanels*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < activeRowsLast; r++ {
				packed[packIdx] = hwy.Float32ToBFloat16(a[(baseRow+r)*k+colStart+kk].Float32())
				packIdx++
			}
			for r := activeRowsLast; r < mr; r++ {
				packed[packIdx] = hwy.Float32ToBFloat16(0)
				packIdx++
			}
		}
	}
	return activeRowsLast
}

func BasePackLHS_fallback(a []float32, packed []float32, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	numMicroPanels := (panelRows + mr - 1) / mr
	activeRowsLast := panelRows - (numMicroPanels-1)*mr
	fullPanels := numMicroPanels
	if activeRowsLast < mr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseRow := rowStart + panel*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < mr; r++ {
				packed[packIdx] = a[(baseRow+r)*k+colStart+kk]
				packIdx++
			}
		}
	}
	if activeRowsLast < mr && activeRowsLast > 0 {
		baseRow := rowStart + fullPanels*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < activeRowsLast; r++ {
				packed[packIdx] = a[(baseRow+r)*k+colStart+kk]
				packIdx++
			}
			for r := activeRowsLast; r < mr; r++ {
				packed[packIdx] = 0
				packIdx++
			}
		}
	}
	return activeRowsLast
}

func BasePackLHS_fallback_Float64(a []float64, packed []float64, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	numMicroPanels := (panelRows + mr - 1) / mr
	activeRowsLast := panelRows - (numMicroPanels-1)*mr
	fullPanels := numMicroPanels
	if activeRowsLast < mr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseRow := rowStart + panel*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < mr; r++ {
				packed[packIdx] = a[(baseRow+r)*k+colStart+kk]
				packIdx++
			}
		}
	}
	if activeRowsLast < mr && activeRowsLast > 0 {
		baseRow := rowStart + fullPanels*mr
		for kk := 0; kk < panelK; kk++ {
			for r := 0; r < activeRowsLast; r++ {
				packed[packIdx] = a[(baseRow+r)*k+colStart+kk]
				packIdx++
			}
			for r := activeRowsLast; r < mr; r++ {
				packed[packIdx] = 0
				packIdx++
			}
		}
	}
	return activeRowsLast
}

func BasePackRHS_fallback_Float16(b []hwy.Float16, packed []hwy.Float16, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	numMicroPanels := (panelCols + nr - 1) / nr
	activeColsLast := panelCols - (numMicroPanels-1)*nr
	fullPanels := numMicroPanels
	if activeColsLast < nr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseCol := colStart + panel*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < nr; c++ {
				packed[packIdx] = hwy.Float32ToFloat16(b[bRowStart+baseCol+c].Float32())
				packIdx++
			}
		}
	}
	if activeColsLast < nr && activeColsLast > 0 {
		baseCol := colStart + fullPanels*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < activeColsLast; c++ {
				packed[packIdx] = hwy.Float32ToFloat16(b[bRowStart+baseCol+c].Float32())
				packIdx++
			}
			for c := activeColsLast; c < nr; c++ {
				packed[packIdx] = hwy.Float32ToFloat16(0)
				packIdx++
			}
		}
	}
	return activeColsLast
}

func BasePackRHS_fallback_BFloat16(b []hwy.BFloat16, packed []hwy.BFloat16, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	numMicroPanels := (panelCols + nr - 1) / nr
	activeColsLast := panelCols - (numMicroPanels-1)*nr
	fullPanels := numMicroPanels
	if activeColsLast < nr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseCol := colStart + panel*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < nr; c++ {
				packed[packIdx] = hwy.Float32ToBFloat16(b[bRowStart+baseCol+c].Float32())
				packIdx++
			}
		}
	}
	if activeColsLast < nr && activeColsLast > 0 {
		baseCol := colStart + fullPanels*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < activeColsLast; c++ {
				packed[packIdx] = hwy.Float32ToBFloat16(b[bRowStart+baseCol+c].Float32())
				packIdx++
			}
			for c := activeColsLast; c < nr; c++ {
				packed[packIdx] = hwy.Float32ToBFloat16(0)
				packIdx++
			}
		}
	}
	return activeColsLast
}

func BasePackRHS_fallback(b []float32, packed []float32, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	numMicroPanels := (panelCols + nr - 1) / nr
	activeColsLast := panelCols - (numMicroPanels-1)*nr
	fullPanels := numMicroPanels
	if activeColsLast < nr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseCol := colStart + panel*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < nr; c++ {
				packed[packIdx] = b[bRowStart+baseCol+c]
				packIdx++
			}
		}
	}
	if activeColsLast < nr && activeColsLast > 0 {
		baseCol := colStart + fullPanels*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < activeColsLast; c++ {
				packed[packIdx] = b[bRowStart+baseCol+c]
				packIdx++
			}
			for c := activeColsLast; c < nr; c++ {
				packed[packIdx] = 0
				packIdx++
			}
		}
	}
	return activeColsLast
}

func BasePackRHS_fallback_Float64(b []float64, packed []float64, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	numMicroPanels := (panelCols + nr - 1) / nr
	activeColsLast := panelCols - (numMicroPanels-1)*nr
	fullPanels := numMicroPanels
	if activeColsLast < nr {
		fullPanels--
	}
	packIdx := 0
	for panel := 0; panel < fullPanels; panel++ {
		baseCol := colStart + panel*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < nr; c++ {
				packed[packIdx] = b[bRowStart+baseCol+c]
				packIdx++
			}
		}
	}
	if activeColsLast < nr && activeColsLast > 0 {
		baseCol := colStart + fullPanels*nr
		for kk := 0; kk < panelK; kk++ {
			bRowStart := (rowStart + kk) * n
			for c := 0; c < activeColsLast; c++ {
				packed[packIdx] = b[bRowStart+baseCol+c]
				packIdx++
			}
			for c := activeColsLast; c < nr; c++ {
				packed[packIdx] = 0
				packIdx++
			}
		}
	}
	return activeColsLast
}

func BasePackLHSVec_fallback_Float16(a []hwy.Float16, packed []hwy.Float16, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	return BasePackLHS_fallback_Float16(a, packed, m, k, rowStart, colStart, panelRows, panelK, mr)
}

func BasePackLHSVec_fallback_BFloat16(a []hwy.BFloat16, packed []hwy.BFloat16, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	return BasePackLHS_fallback_BFloat16(a, packed, m, k, rowStart, colStart, panelRows, panelK, mr)
}

func BasePackLHSVec_fallback(a []float32, packed []float32, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	return BasePackLHS_fallback(a, packed, m, k, rowStart, colStart, panelRows, panelK, mr)
}

func BasePackLHSVec_fallback_Float64(a []float64, packed []float64, m int, k int, rowStart int, colStart int, panelRows int, panelK int, mr int) int {
	return BasePackLHS_fallback_Float64(a, packed, m, k, rowStart, colStart, panelRows, panelK, mr)
}

func BasePackRHSVec_fallback_Float16(b []hwy.Float16, packed []hwy.Float16, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	lanes := hwy.Zero[hwy.Float16]().NumLanes()
	if nr >= lanes && nr%lanes == 0 {
		numMicroPanels := (panelCols + nr - 1) / nr
		activeColsLast := panelCols - (numMicroPanels-1)*nr
		fullPanels := numMicroPanels
		if activeColsLast < nr {
			fullPanels--
		}
		packIdx := 0
		for panel := 0; panel < fullPanels; panel++ {
			baseCol := colStart + panel*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < nr; c += lanes {
					v := hwy.Load(b[bRowStart+baseCol+c:])
					hwy.Store(v, packed[packIdx+c:])
				}
				packIdx += nr
			}
		}
		if activeColsLast < nr && activeColsLast > 0 {
			baseCol := colStart + fullPanels*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < activeColsLast; c++ {
					packed[packIdx] = hwy.Float32ToFloat16(b[bRowStart+baseCol+c].Float32())
					packIdx++
				}
				for c := activeColsLast; c < nr; c++ {
					packed[packIdx] = hwy.Float32ToFloat16(0)
					packIdx++
				}
			}
		}
		return activeColsLast
	}
	return BasePackRHS_fallback_Float16(b, packed, k, n, rowStart, colStart, panelK, panelCols, nr)
}

func BasePackRHSVec_fallback_BFloat16(b []hwy.BFloat16, packed []hwy.BFloat16, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	lanes := hwy.Zero[hwy.BFloat16]().NumLanes()
	if nr >= lanes && nr%lanes == 0 {
		numMicroPanels := (panelCols + nr - 1) / nr
		activeColsLast := panelCols - (numMicroPanels-1)*nr
		fullPanels := numMicroPanels
		if activeColsLast < nr {
			fullPanels--
		}
		packIdx := 0
		for panel := 0; panel < fullPanels; panel++ {
			baseCol := colStart + panel*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < nr; c += lanes {
					v := hwy.Load(b[bRowStart+baseCol+c:])
					hwy.Store(v, packed[packIdx+c:])
				}
				packIdx += nr
			}
		}
		if activeColsLast < nr && activeColsLast > 0 {
			baseCol := colStart + fullPanels*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < activeColsLast; c++ {
					packed[packIdx] = hwy.Float32ToBFloat16(b[bRowStart+baseCol+c].Float32())
					packIdx++
				}
				for c := activeColsLast; c < nr; c++ {
					packed[packIdx] = hwy.Float32ToBFloat16(0)
					packIdx++
				}
			}
		}
		return activeColsLast
	}
	return BasePackRHS_fallback_BFloat16(b, packed, k, n, rowStart, colStart, panelK, panelCols, nr)
}

func BasePackRHSVec_fallback(b []float32, packed []float32, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	if nr >= 1 && nr%1 == 0 {
		numMicroPanels := (panelCols + nr - 1) / nr
		activeColsLast := panelCols - (numMicroPanels-1)*nr
		fullPanels := numMicroPanels
		if activeColsLast < nr {
			fullPanels--
		}
		packIdx := 0
		for panel := 0; panel < fullPanels; panel++ {
			baseCol := colStart + panel*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < nr; c++ {
					v := b[bRowStart+baseCol+c]
					packed[packIdx+c] = v
				}
				packIdx += nr
			}
		}
		if activeColsLast < nr && activeColsLast > 0 {
			baseCol := colStart + fullPanels*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < activeColsLast; c++ {
					packed[packIdx] = b[bRowStart+baseCol+c]
					packIdx++
				}
				for c := activeColsLast; c < nr; c++ {
					packed[packIdx] = 0
					packIdx++
				}
			}
		}
		return activeColsLast
	}
	return BasePackRHS_fallback(b, packed, k, n, rowStart, colStart, panelK, panelCols, nr)
}

func BasePackRHSVec_fallback_Float64(b []float64, packed []float64, k int, n int, rowStart int, colStart int, panelK int, panelCols int, nr int) int {
	if nr >= 1 && nr%1 == 0 {
		numMicroPanels := (panelCols + nr - 1) / nr
		activeColsLast := panelCols - (numMicroPanels-1)*nr
		fullPanels := numMicroPanels
		if activeColsLast < nr {
			fullPanels--
		}
		packIdx := 0
		for panel := 0; panel < fullPanels; panel++ {
			baseCol := colStart + panel*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < nr; c++ {
					v := b[bRowStart+baseCol+c]
					packed[packIdx+c] = v
				}
				packIdx += nr
			}
		}
		if activeColsLast < nr && activeColsLast > 0 {
			baseCol := colStart + fullPanels*nr
			for kk := 0; kk < panelK; kk++ {
				bRowStart := (rowStart + kk) * n
				for c := 0; c < activeColsLast; c++ {
					packed[packIdx] = b[bRowStart+baseCol+c]
					packIdx++
				}
				for c := activeColsLast; c < nr; c++ {
					packed[packIdx] = 0
					packIdx++
				}
			}
		}
		return activeColsLast
	}
	return BasePackRHS_fallback_Float64(b, packed, k, n, rowStart, colStart, panelK, panelCols, nr)
}
